(function(g){var window=this;var hEa=function(a,b){return g.Ob(a,b)},$5=function(a,b,c){a.A.set(b,c)},a6=function(a){$5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.E)()).toString(36));
return a},b6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.zn(a.A,b,c)},iEa=function(a,b){var c=[];
g.Ak(b,function(d){try{var e=g.yo.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.xo(e)&&c.push(d)},a);
return c},jEa=function(a,b){var c=iEa(a,b);
g.A(c,function(d){g.yo.prototype.remove.call(this,d)},a)},kEa=function(a){if(a.bd){if(a.bd.locationOverrideToken)return{locationOverrideToken:a.bd.locationOverrideToken};
if(null!=a.bd.latitudeE7&&null!=a.bd.longitudeE7)return{latitudeE7:a.bd.latitudeE7,longitudeE7:a.bd.longitudeE7}}return null},lEa=function(a,b){g.jb(a,b)||a.push(b)},c6=function(a){var b=0,c;
for(c in a)b++;return b},mEa=function(a,b){var c=b instanceof g.Dc?b:g.Jc(b,/^data:image\//i.test(b));
a.src=g.Ec(c)},d6=function(){},nEa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},oEa=function(a){if(a.Wd&&"function"==typeof a.Wd)return a.Wd();
if("string"===typeof a)return a.split("");if(g.Pa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Kb(a)},pEa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Pa(a)||"string"===typeof a)g.A(a,b,void 0);else{if(a.jf&&"function"==typeof a.jf)var c=a.jf();else if(a.Wd&&"function"==typeof a.Wd)c=void 0;else if(g.Pa(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Lb(a);d=oEa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},qEa=function(a,b,c,d){var e=new g.nn(null,void 0);
a&&g.on(e,a);b&&g.pn(e,b);c&&g.qn(e,c);d&&(e.u=d);return e},e6=function(a,b){g.ep[a]=!0;
var c=g.cp();c&&c.publish.apply(c,arguments);g.ep[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.kn;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",rEa(this,a.capabilities||""),sEa(this,a.experiments||""))},rEa=function(a,b){a.capabilities.clear();
g.He(b.split(","),g.Ta(hEa,tEa)).forEach(function(c){a.capabilities.add(c)})},sEa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},uEa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},vEa=function(a){return new g6(a)},wEa=function(a){return Array.isArray(a)?g.Nc(a,vEa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return Array.isArray(a)?"["+g.Nc(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},xEa=function(a){return g.Nc(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.fb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.fb(a,function(c){return h6(c,b)})},yEa=function(){var a=(0,g.vt)();
a&&jEa(a,a.o.Th(!0))},n6=function(){var a=g.zt("yt-remote-connected-devices")||[];
g.Ab(a);return a},zEa=function(a){if(g.kb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Nc(a,function(d,e){return 0==e?d:d.substring(c.length)})},AEa=function(a){g.xt("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.zt("yt-remote-device-id");a||(a=k6(),g.xt("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.jb(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.jb(a,b);g.Bt()&&g.Cb(a,b);a=zEa(a);if(g.kb(a))try{g.Rq.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.Sq("remote_sid",a.join(","),-1)}catch(c){}},BEa=function(){return g.zt("yt-remote-session-browser-channel")},CEa=function(){return g.zt("yt-remote-local-screens")||[]},DEa=function(){g.xt("yt-remote-lounge-token-expiration",!0,86400)},EEa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Nc(CEa(),function(d){return d.loungeToken}),c=g.Nc(a,function(d){return d.loungeToken});
g.Mi(c,function(d){return!g.jb(b,d)})&&DEa();
g.xt("yt-remote-local-screens",a,31536E3)},FEa=function(a,b){g.xt("yt-remote-session-browser-channel",a);
g.xt("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.jb(c,d)||c.push(d);AEa(c);q6()},r6=function(a){a||(g.At("yt-remote-session-screen-id"),g.At("yt-remote-session-video-id"));
q6();a=n6();g.ob(a,p6());AEa(a)},GEa=function(){if(!s6){var a=g.Eo();
a&&(s6=new g.po(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},HEa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},IEa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?JEa(a.shift(),function(){t6(a)}):u6()},KEa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},JEa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},u6=function(){var a=IEa();
a&&a(!1,"No cast extension found")},MEa=function(){if(LEa){var a=2,b=IEa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;JEa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},NEa=function(){MEa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},v6=function(a,b,c){g.B.call(this);
this.F=null!=c?(0,g.x)(a,c):a;this.Jd=b;this.C=(0,g.x)(this.rG,this);this.o=!1;this.u=0;this.A=this.Ka=null;this.B=[]},w6=function(a,b,c){g.B.call(this);
this.B=null!=c?a.bind(c):a;this.Jd=b;this.A=null;this.o=!1;this.u=0;this.Ka=null},x6=function(a){a.Ka=g.gg(function(){a.Ka=null;
a.o&&!a.u&&(a.o=!1,x6(a))},a.Jd);
var b=a.A;a.A=null;a.B.apply(null,b)},y6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return nEa(a)},z6=function(){},A6=function(){},OEa=function(){},QEa=function(a){return(a=PEa(a))?new ActiveXObject(a):new XMLHttpRequest},PEa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},B6=function(a,b,c,d){this.o=a;
this.A=b;this.I=c;this.G=d||1;this.C=45E3;this.B=new g.t1(this);this.u=new g.fg;this.u.setInterval(250)},SEa=function(a,b,c){a.Zl=1;
a.Wh=a6(b.clone());a.kk=c;a.F=!0;REa(a,null)},C6=function(a,b,c,d,e){a.Zl=1;
a.Wh=a6(b.clone());a.kk=null;a.F=c;e&&(a.nD=!1);REa(a,d)},REa=function(a,b){a.Sl=(0,g.E)();
D6(a);a.Qi=a.Wh.clone();b6(a.Qi,"t",a.G);a.Bo=0;a.cd=a.o.wt(a.o.mo()?b:null);0<a.fu&&(a.xr=new w6((0,g.x)(a.iE,a,a.cd),a.fu));a.B.ma(a.cd,"readystatechange",a.PN);var c=a.Ej?g.Wb(a.Ej):{};a.kk?(a.ls="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.cd.send(a.Qi,a.ls,a.kk,c)):(a.ls="GET",a.nD&&!g.we&&(c.Connection="close"),a.cd.send(a.Qi,a.ls,null,c));a.o.Wf(1)},VEa=function(a,b,c){for(var d=!0;!a.kj&&a.Bo<c.length;){var e=TEa(a,c);
if(e==E6){4==b&&(a.ki=4,F6(15),d=!1);break}else if(e==UEa){a.ki=4;F6(16);d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.ki=1,F6(17),d=!1);a.fg=a.fg&&d;d||(H6(a),I6(a))},TEa=function(a,b){var c=a.Bo,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if(isNaN(c))return UEa;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.Bo=d+c;return e},XEa=function(a,b){a.Sl=(0,g.E)();
D6(a);var c=b?window.location.hostname:"";a.Qi=a.Wh.clone();$5(a.Qi,"DOMAIN",c);$5(a.Qi,"t",a.G);try{a.lg=new ActiveXObject("htmlfile")}catch(n){H6(a);a.ki=7;F6(22);I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)e+="\\x3c";else if(">"==h)e+="\\x3e";else{var l=h;if(l in J6)h=J6[l];else if(l in WEa)h=J6[l]=WEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)h=l;else{if(256>m){if(h="\\x",16>m||256<m)h+="0"}else h="\\u",4096>m&&(h+="0");h+=m.toString(16).toUpperCase()}h=
J6[l]=h}e+=h}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.dd(g.hc("b/12014412"),d+"</body></html>");a.lg.open();a.lg.write(g.$c(c));a.lg.close();a.lg.parentWindow.m=(0,g.x)(a.dN,a);a.lg.parentWindow.d=(0,g.x)(a.sC,a,!0);a.lg.parentWindow.rpcClose=(0,g.x)(a.sC,a,!1);c=a.lg.createElement("DIV");a.lg.parentWindow.document.body.appendChild(c);d=g.Ic(a.Qi.toString());d=g.kd(g.Ec(d));d=g.dd(g.hc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ed(c,d);a.o.Wf(1)},D6=function(a){a.ax=(0,g.E)()+a.C;
YEa(a,a.C)},YEa=function(a,b){if(null!=a.gm)throw Error("WatchDog timer not null");
a.gm=K6((0,g.x)(a.oN,a),b)},L6=function(a){a.gm&&(g.v.clearTimeout(a.gm),a.gm=null)},I6=function(a){a.o.yz()||a.kj||a.o.Vp(a)},H6=function(a){L6(a);
g.Te(a.xr);a.xr=null;a.u.stop();g.Hya(a.B);if(a.cd){var b=a.cd;a.cd=null;b.abort();b.dispose()}a.lg&&(a.lg=null)},G6=function(a,b){try{a.o.jC(a,b),a.o.Wf(4)}catch(c){}},$Ea=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;ZEa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){$Ea(a,b,c,d,f)},f)})}},ZEa=function(a,b,c){var d=new Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
mEa(d,a)},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},aFa=function(a){this.o=a;
this.u=new z6},bFa=function(a){var b=N6(a.o,a.tm,"/mail/images/cleardot.gif");
a6(b);$Ea(b.toString(),5E3,(0,g.x)(a.rF,a),3,2E3);a.Wf(1)},P6=function(a){var b=a.o.M;
if(null!=b)F6(5),b?(F6(11),O6(a.o,a,!1)):(F6(12),O6(a.o,a,!0));else if(a.ye=new B6(a,void 0,void 0,void 0),a.ye.Ej=a.du,b=a.o,b=N6(b,b.mo()?a.an:null,a.eu),F6(5),!g.ue||g.Xd(10))b6(b,"TYPE","xmlhttp"),C6(a.ye,b,!1,a.an,!1);else{b6(b,"TYPE","html");var c=a.ye;a=!!a.an;c.Zl=3;c.Wh=a6(b.clone());XEa(c,a)}},Q6=function(a){g.wf.call(this);
this.headers=new g.kn;this.T=a||null;this.A=!1;this.U=this.o=null;this.fa=this.M="";this.F=0;this.B="";this.C=this.Z=this.I=this.X=!1;this.G=0;this.N=null;this.la="";this.S=this.Y=!1},cFa=function(a){return g.ue&&g.Wd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},dFa=function(a){return"content-type"==a.toLowerCase()},fFa=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.F=5;eFa(a);R6(a)},eFa=function(a){a.X||(a.X=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},hFa=function(a){if(a.A&&"undefined"!=typeof g.y1)if(a.U[1]&&4==S6(a)&&2==a.getStatus())T6(a,"Local request error detected and ignored");
else if(a.I&&4==S6(a))g.gg(a.fC,0,a);else if(a.dispatchEvent("readystatechange"),4==S6(a)){T6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.ud(1,String(a.M));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!gFa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.F=6;try{var l=2<S6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";eFa(a)}}finally{R6(a)}}},R6=function(a,b){if(a.o){iFa(a);
var c=a.o,d=a.U[0]?g.Ma:null;a.o=null;a.U=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},iFa=function(a){a.o&&a.S&&(a.o.ontimeout=null);
a.N&&(g.v.clearTimeout(a.N),a.N=null)},S6=function(a){return a.o?a.o.readyState:0},U6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},T6=function(a,b){return b+" ["+a.fa+" "+a.M+" "+a.getStatus()+"]"},V6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new z6;this.I=a||null;this.M=null!=b?b:null;this.F=c||!1},jFa=function(a,b){this.o=a;
this.map=b;this.context=null},lFa=function(a){g.Ve.call(this,"statevent",a)},mFa=function(a,b,c,d){g.Ve.call(this,"timingevent",a);
this.size=b;this.co=d},nFa=function(a){g.Ve.call(this,"serverreachability",a)},qFa=function(a){oFa(a);
if(3==a.o){var b=a.In++,c=a.Fp.clone();$5(c,"SID",a.A);$5(c,"RID",b);$5(c,"TYPE","terminate");W6(a,c);b=new B6(a,a.A,b,void 0);b.Zl=2;b.Wh=a6(c.clone());mEa(new Image,b.Wh.toString());b.Sl=(0,g.E)();D6(b)}pFa(a)},rFa=function(a){a.PF(1,0);
a.Fp=N6(a,null,a.cu);X6(a)},oFa=function(a){a.Yh&&(a.Yh.abort(),a.Yh=null);
a.Dc&&(a.Dc.cancel(),a.Dc=null);a.Xg&&(g.v.clearTimeout(a.Xg),a.Xg=null);Y6(a);a.oe&&(a.oe.cancel(),a.oe=null);a.ci&&(g.v.clearTimeout(a.ci),a.ci=null)},sFa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new jFa(a.NJ++,b));2!=a.o&&3!=a.o||X6(a)},X6=function(a){a.oe||a.ci||(a.ci=K6((0,g.x)(a.rC,a),0),a.Tk=0)},uFa=function(a,b){if(1==a.o){if(!b){a.In=Math.floor(1E5*Math.random());
var c=a.In++,d=new B6(a,"",c,void 0);d.Ej=a.al;var e=Z6(a),f=a.Fp.clone();$5(f,"RID",c);$5(f,"CVER","1");W6(a,f);SEa(d,f,e);a.oe=d;a.o=2}}else 3==a.o&&(b?tFa(a,b):0==a.u.length||a.oe||tFa(a))},tFa=function(a,b){if(b)if(6<a.lj){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.In-1;var d=Z6(a)}else c=b.I,d=b.kk;else c=a.In++,d=Z6(a);var e=a.Fp.clone();$5(e,"SID",a.A);$5(e,"RID",c);$5(e,"AID",a.sl);W6(a,e);c=new B6(a,a.A,c,a.Tk+1);c.Ej=a.al;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.oe=c;SEa(c,e,d)},W6=function(a,b){if(a.Gd){var c=a.Gd.Xy();
c&&g.Eb(c,function(d,e){$5(b,e,d)})}},Z6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.lj&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,h=a.u[e].map;f=6>=a.lj?e:f-d;try{g.Eb(h,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},vFa=function(a){a.Dc||a.Xg||(a.G=1,a.Xg=K6((0,g.x)(a.qC,a),0),a.Hk=0)},$6=function(a){if(a.Dc||a.Xg||3<=a.Hk)return!1;
a.G++;a.Xg=K6((0,g.x)(a.qC,a),wFa(a,a.Hk));a.Hk++;return!0},O6=function(a,b,c){a.hs=c;
a.vg=b.ph;a.F||rFa(a)},Y6=function(a){null!=a.pj&&(g.v.clearTimeout(a.pj),a.pj=null)},wFa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.Gd&&(c=null);var d=(0,g.x)(a.wO,a);c||(c=new g.nn("//www.google.com/images/cleardot.gif"),a6(c));ZEa(c.toString(),1E4,d)}else F6(2);xFa(a,b)},xFa=function(a,b){a.o=0;
a.Gd&&a.Gd.ny(b);pFa(a);oFa(a)},pFa=function(a){a.o=0;
a.vg=-1;if(a.Gd)if(0==a.B.length&&0==a.u.length)a.Gd.ct();else{g.rb(a.B);var b=g.rb(a.u);a.B.length=0;a.u.length=0;a.Gd.ct(b)}},N6=function(a,b,c){var d=g.vn(c);
if(""!=d.o)b&&g.pn(d,b+"."+d.o),g.qn(d,d.B);else{var e=window.location;d=qEa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Nm&&g.Eb(a.Nm,function(f,h){$5(d,h,f)});
$5(d,"VER",a.lj);W6(a,d);return d},K6=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},F6=function(a){b7.dispatchEvent(new lFa(b7,a))},yFa=function(){},zFa=function(){this.o=[];
this.u=[]},AFa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.B.call(this);
this.o=new g.G(this.WM,0,this);g.C(this,this.o);this.Jd=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.x)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},d7=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
this.N=a;this.F=b;this.A=new g.oo;this.u=new c7(this.bO,this);this.o=null;this.Pc=!1;this.C=null;this.M="";this.I=this.B=0;this.G=[];this.U=c;this.S=d},BFa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.hs,sessionId:a.o.A,arrayId:a.o.sl}},CFa=function(a,b){a.I=b||0;
a.u.stop();e7(a);a.o&&(3==a.o.o&&uFa(a.o),qFa(a.o));a.I=0},f7=function(a){return!!a.o&&3==a.o.o},e7=function(a){if(a.o){var b=a.S(),c=a.o.al||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.o.al=c}},DFa=function(a,b){(a.F.loungeIdToken=b)||a.u.stop()},g7=function(a){this.scheme="https";
this.port=this.domain="";this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.ud(4,a))||"";b&&(this.port=":"+b);this.domain=g.vd(a)||"";a=g.Tc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Bc(a,"10.0")&&(this.u=!1))},h7=function(a,b){var c=a.o;
a.u&&(c=a.scheme+"://"+a.domain+a.port+a.o);return g.Gd(c+b,{})},i7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ta(a.B,d,!0),onError:g.Ta(a.A,e),Se:g.Ta(a.C,e)};c&&(a.Gb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Kq(b,a)},HFa=function(){var a=EFa;
FFa();j7.push(a);GFa(j7)},k7=function(a,b){FFa();
var c=j7,d=IFa(a,String(b));g.kb(c)?JFa(d):(GFa(c),g.A(c,function(e){e(d)}))},FFa=function(){j7||(j7=g.La("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",j7,void 0))},JFa=function(a){var b=(l7+1)%50;
l7=b;m7[b]=a;n7||(n7=49==b)},GFa=function(a){var b=m7;
if(b[0]){var c=l7,d=n7?c:-1;do{d=(d+1)%50;var e=b[d];g.A(a,function(f){f(e)})}while(d!=c);
m7=Array(50);l7=-1;n7=!1}},IFa=function(a,b){var c=((0,g.E)()-KFa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},o7=function(a){g.N.call(this);
this.F=a;this.screens=[]},LFa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},MFa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.He(a.screens,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=LFa(a,b[d])||c;return c},NFa=function(a,b){var c=a.screens.length;
a.screens=g.He(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},p7=function(a,b,c,d){g.N.call(this);
this.F=a;this.C=b;this.A=c;this.B=d;this.u=0;this.o=null;this.Ka=NaN},r7=function(a){o7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;q7(this);this.info("Initializing with "+j6(this.screens))},OFa=function(a){if(a.screens.length){var b=g.Nc(a.screens,function(d){return d.id}),c=h7(a.u,"/pairing/get_lounge_token_batch");
i7(a.u,c,{screen_ids:b.join(",")},(0,g.x)(a.AG,a),(0,g.x)(a.zG,a))}},q7=function(a){var b=wEa(CEa());
b=g.He(b,function(c){return!c.uuid});
return MFa(a,b)},s7=function(a,b){EEa(g.Nc(a.screens,uEa));
b&&DEa()},u7=function(a,b){g.N.call(this);
this.F=b;var c=g.zt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.jb(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;t7("Initialized with "+g.bl(this.o))},PFa=function(a,b,c){var d=h7(a.C,"/pairing/get_screen_availability");
i7(a.C,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},v7=function(a,b){a:if(c6(b)!=c6(a.o))var c=!1;
else{c=g.Lb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(t7("Updated online screens: "+g.bl(a.o)),a.o=b,a.R("screenChange"));QFa(a)},w7=function(a){isNaN(a.A)||g.bp(a.A);
a.A=g.$o((0,g.x)(a.Xv,a),0<a.B&&a.B<(0,g.E)()?2E4:1E4)},t7=function(a){k7("OnlineScreenService",a)},RFa=function(a){var b={};
g.A(a.F(),function(c){c.token?b[c.token]=c.id:this.pc("Requesting availability of screen w/o lounge token.")});
return b},QFa=function(a){a=g.Lb(g.Fb(a.o,function(b){return b}));
g.Ab(a);a.length?g.xt("yt-remote-online-screen-ids",a.join(","),60):g.At("yt-remote-online-screen-ids")},x7=function(a){o7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};SFa(this)},UFa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var h=a.Ke();if(h=(c?m6(h,c):null)||m6(h,b)){h.uuid=b;var l=y7(a,h);PFa(a.o,l,function(m){e(m?l:null)})}else c?TFa(a,c,(0,g.x)(function(m){var n=y7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));PFa(this.o,n,function(p){e(p?n:null)})},a),f):e(null)},VFa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},TFa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Gb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Kq(h7(a.C,"/pairing/get_lounge_token_batch"),e)},WFa=function(a){a.screens=a.u.Ke();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.screens))},SFa=function(a){z7(a);
a.u=new r7(a.C);a.u.subscribe("screenChange",(0,g.x)(a.HG,a));WFa(a);a.A=wEa(g.zt("yt-remote-automatic-screen-cache")||[]);z7(a);a.info("Initializing automatic screens: "+j6(a.A));a.o=new u7(a.C,(0,g.x)(a.Ke,a,!0));a.o.subscribe("screenChange",(0,g.x)(function(){this.R("onlineScreenChange")},a))},y7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.xt("yt-remote-automatic-screen-cache",g.Nc(a.A,uEa)));z7(a);a.B[b.uuid]=b.id;g.xt("yt-remote-device-id-map",a.B,31536E3);return b},z7=function(a){a.B=g.zt("yt-remote-device-id-map")||{}},A7=function(a,b,c){g.N.call(this);
this.U=c;this.I=a;this.o=b;this.G=null},B7=function(a,b){k7(a.U,b)},C7=function(a,b){A7.call(this,a,b,"CastSession");
this.u=null;this.A=0;this.C=(0,g.x)(this.dP,this);this.B=(0,g.x)(this.wN,this);this.A=g.$o((0,g.x)(function(){XFa(this,null)},this),12E4)},YFa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.bl(void 0));
var b={type:"getMdxSessionStatus"};a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ma,(0,g.x)(function(){B7(this,"Failed to send message: getMdxSessionStatus.")},a)):B7(a,"Sending yt message without session: "+g.bl(b))},XFa=function(a,b){g.bp(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.x)(a.kr,a),d=(0,g.x)(a.Re,a);a.pz(b,c,d,5)}}else a.Re(Error("Waiting for session status timed out."))},D7=function(a,b,c){A7.call(this,a,b,"DialSession");
this.A=this.F=null;this.M="";this.T=c;this.N=null;this.C=g.Ma;this.B=NaN;this.S=(0,g.x)(this.gP,this);this.u=g.Ma},ZFa=function(a){a.u=a.I.pE(a.M,a.o.label,a.o.friendlyName,(0,g.x)(function(b){this.u=g.Ma;
this.kr(b)},a),(0,g.x)(function(b){this.u=g.Ma;
this.Re(b)},a))},$Fa=function(a){var b={};
b.pairingCode=a.M;b.theme=a.T;GEa()&&(b.env_useStageMdx=1);return g.Ed(b)},E7=function(a,b){A7.call(this,a,b,"ManualSession");
this.u=g.$o((0,g.x)(this.ul,this,null),150)},F7=function(a,b,c,d){g.N.call(this);
this.u=a;this.G=b||"233637DE";this.F=c||"cl";this.I=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.x)(this.lM,this)},aGa=function(a,b){return b?g.fb(a.A,function(c){return h6(b,c.label)},a):null},G7=function(a){k7("Controller",a)},EFa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},H7=function(a){return a.C||!!a.A.length||!!a.o},I7=function(a,b,c){b!=a.o&&(g.Te(a.o),(a.o=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.o):a.R("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.x)(a.oC,a,b)),b.getScreen()?a.R("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.ul(null)):a.R("yt-remote-cast2-session-change",null))},bGa=function(a){var b=a.u.oE(),c=a.o&&a.o.o;
a=g.Nc(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=aGa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},hGa=function(a,b,c,d,e,f,h){cGa()?dGa(b,e,f,h)&&(K7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?eGa(a,c):(window.__onGCastApiAvailable=function(l,m){l?eGa(a,c):(L7("Failed to load cast API: "+m),M7(!1),K7(!1),g.At("yt-remote-cast-available"),g.At("yt-remote-cast-receiver"),fGa(),c(!1))},d?g.lp("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?NEa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(MEa(),t6(gGa.map(KEa))))):J7("Cannot initialize because not running Chrome")},fGa=function(){J7("dispose");
var a=N7();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);iGa(!1);g.hp(O7);O7.length=0},P7=function(){return!!g.zt("yt-remote-cast-installed")},jGa=function(){var a=g.zt("yt-remote-cast-receiver");
return a?a.friendlyName:null},kGa=function(){J7("clearCurrentReceiver");
g.At("yt-remote-cast-receiver")},lGa=function(){return P7()?N7()?N7().getCastSession():(L7("getCastSelector: Cast is not initialized."),null):(L7("getCastSelector: Cast API is not installed!"),null)},R7=function(){P7()?N7()?Q7()?(J7("Requesting cast selector."),N7().requestSession()):(J7("Wait for cast API to be ready to request the session."),O7.push(g.gp("yt-remote-cast2-api-ready",R7))):L7("requestCastSelector: Cast is not initialized."):L7("requestCastSelector: Cast API is not installed!")},S7=
function(a,b){Q7()?N7().setConnectedScreenStatus(a,b):L7("setConnectedScreenStatus called before ready.")},cGa=function(){var a=0<=g.Tc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Qx||a},mGa=function(a,b){N7().init(a,b)},dGa=function(a,b,c,d){var e=!1;
N7()||(a=new F7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.xt("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){J7("onReceiverSelected: "+f.friendlyName);
g.xt("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){J7("onReceiverResumed: "+f.friendlyName);
g.xt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){J7("onSessionChange: "+i6(f));
f||g.At("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
J7("cloudview.createSingleton_: "+e);return e},N7=function(){return g.La("yt.mdx.remote.cloudview.instance_")},eGa=function(a,b){M7(!0);
K7(!1);mGa(a,function(c){c?(iGa(!0),g.ip("yt-remote-cast2-api-ready")):(L7("Failed to initialize cast API."),M7(!1),g.At("yt-remote-cast-available"),g.At("yt-remote-cast-receiver"),fGa());b(c)})},J7=function(a){k7("cloudview",a)},L7=function(a){k7("cloudview",a)},M7=function(a){J7("setCastInstalled_ "+a);
g.xt("yt-remote-cast-installed",a)},Q7=function(){return!!g.La("yt.mdx.remote.cloudview.apiReady_")},iGa=function(a){J7("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},K7=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},T7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.wg=!1;this.M=this.I=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},U7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.wg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.E)();a.C=0;a.u=0;a.I=0;a.M=0;a.B=NaN;a.A=!1},V7=function(a){return a.sb()?((0,g.E)()-a.F)/1E3:0},W7=function(a,b){a.G=b;
a.F=(0,g.E)()},X7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.E)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Y7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&U7(a)},Z7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Xb(a.o);b.hasPrevious=a.wg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.I;b.loadedTime=a.M;b.liveIngestionTime=a.B;return b},a8=function(a,b){g.N.call(this);
this.o=0;this.B=a;this.F=[];this.C=new zFa;this.A=this.u=null;this.M=(0,g.x)(this.wK,this);this.G=(0,g.x)(this.Mn,this);this.I=(0,g.x)(this.vK,this);this.N=(0,g.x)(this.EK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.dx,this),nGa(this))):c=3;0!=c&&(b?this.dx(c):g.$o((0,g.x)(function(){this.dx(c)},this),0));
var d=lGa();d&&$7(this,d);this.subscribe("yt-remote-cast2-session-change",this.N)},b8=function(a){return new T7(a.B.getPlayerContextData())},nGa=function(a){g.A("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Ta(this.hM,b),this))},a)},oGa=function(a){g.A(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},c8=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},e8=function(a,b,c){var d=b8(a);
W7(d,c);-1E3!=d.playerState&&(d.playerState=b);d8(a,d)},f8=function(a,b,c){a.B.sendMessage(b,c)},d8=function(a,b){oGa(a);
a.B.setPlayerContextData(Z7(b));nGa(a)},$7=function(a,b){a.A&&(a.A.removeUpdateListener(a.M),a.A.removeMediaListener(a.G),a.Mn(null));
a.A=b;a.A&&(k7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.M),a.A.addMediaListener(a.G),a.A.media.length&&a.Mn(a.A.media[0]))},pGa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=b8(a);b.contentId!=d.videoId&&k7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;W7(d,a.u.getEstimatedTime());d8(a,d)}else k7("CP","No cast media video. Ignoring state update.")},g8=function(a,b,c){return(0,g.x)(function(d){this.pc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.pc("Retrying "+b+" using MDx browser channel."),f8(this,b,c))},a)},h8=function(a,b,c){g.N.call(this);
this.C=NaN;this.S=!1;this.I=this.G=this.M=this.N=NaN;this.U=[];this.B=this.F=this.A=this.ib=this.o=null;this.X=a;this.U.push(g.wp(window,"beforeunload",(0,g.x)(this.tG,this)));this.u=[];this.ib=new T7;this.T=b.id;this.o=qGa(this,c);this.o.subscribe("handlerOpened",this.AK,this);this.o.subscribe("handlerClosed",this.xK,this);this.o.subscribe("handlerError",this.yK,this);this.o.subscribe("handlerMessage",this.zK,this);DFa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.ib.videoId;
g.Bt()&&g.xt("yt-remote-session-video-id",d)},this)},i8=function(a){k7("conn",a)},qGa=function(a,b){return new d7(h7(a.X,"/bc"),b,!1,function(){return a.lE()})},j8=function(a,b){a.R("proxyStateChange",b)},rGa=function(a){a.C=g.$o((0,g.x)(function(){i8("Connecting timeout");
this.Pk(1)},a),2E4)},k8=function(a){g.bp(a.C);
a.C=NaN},l8=function(a){g.bp(a.N);
a.N=NaN},sGa=function(a){m8(a);
a.M=g.$o((0,g.x)(function(){n8(this,"getNowPlaying")},a),2E4)},m8=function(a){g.bp(a.M);
a.M=NaN},uGa=function(a,b){b&&(k8(a),l8(a));
b==(f7(a.o)&&isNaN(a.C))?b&&(j8(a,1),n8(a,"getSubtitlesTrack")):b?(a.nz()&&a.ib.reset(),j8(a,1),n8(a,"getNowPlaying"),tGa(a)):a.Pk(1)},vGa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ib.videoId&&(g.Rb(b.params)?a.ib.o=null:a.ib.o=b.params,a.R("remotePlayerChange"))},wGa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.ib.listId=b.params.listId||a.ib.listId;Y7(a.ib,c,d);a.R("remoteQueueChange")},yGa=function(a,b){b.params=b.params||{};
wGa(a,b);xGa(a,b);a.R("autoplayDismissed")},xGa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
W7(a.ib,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.ib.playerState&&(c=-1E3);a.ib.playerState=c;c=Number(b.params.loadedTime);a.ib.M=isNaN(c)?0:c;c=Number(b.params.duration);a.ib.I=isNaN(c)?0:c;c=a.ib;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.ib;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.ib.playerState?sGa(a):m8(a);a.R("remotePlayerChange")},zGa=function(a,b){if(-1E3!=
a.ib.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ib.playerState=c;c=parseInt(b.params.currentTime,10);W7(a.ib,isNaN(c)?0:c);a.R("remotePlayerChange")}},AGa=function(a,b){var c="true"==b.params.muted;
a.ib.volume=parseInt(b.params.volume,10);a.ib.muted=c;a.R("remotePlayerChange")},BGa=function(a,b){a.F=b.params.videoId;
a.R("nowAutoplaying",parseInt(b.params.timeout,10))},CGa=function(a,b){var c="true"==b.params.hasNext;
a.ib.wg="true"==b.params.hasPrevious;a.ib.hasNext=c;a.R("previousNextChange")},tGa=function(a){g.bp(a.I);
a.I=g.$o((0,g.x)(a.Pk,a,1),864E5)},n8=function(a,b,c){c?i8("Sending: action="+b+", params="+g.bl(c)):i8("Sending: action="+b);
a.o.sendMessage(b,c)},o8=function(a){o7.call(this,"ScreenServiceProxy");
this.Id=a;this.o=[];this.o.push(this.Id.$_s("screenChange",(0,g.x)(this.bP,this)));this.o.push(this.Id.$_s("onlineScreenChange",(0,g.x)(this.LL,this)))},HGa=function(a,b){b=g.K("MDX_CONFIG")||b;
yEa();q6();p8||(p8=new g7(b?b.loungeApiHost:void 0),GEa()&&(p8.o="/api/loungedev"));q8||(q8=g.La("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",q8,void 0));DGa();var c=r8();if(!c){var d=new x7(p8);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=r8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);hGa(a,d,function(m){m?s8()&&S7(s8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){e6("yt-remote-receiver-availability-change")})},
e,f,h,l)}b&&!g.La("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),t8("Initializing: "+g.bl(b)),u8.push(g.gp("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),u8.push(g.gp("yt-remote-cast2-receiver-selected",function(){v8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),u8.push(g.gp("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),u8.push(g.gp("yt-remote-cast2-session-change",EGa)),u8.push(g.gp("yt-remote-connection-change",function(m){m?S7(s8(),"YouTube TV"):w8()||(S7(null,null),kGa())})),e=x8(),b.isAuto&&(e.id+="#dial"),g.Qo("desktop_enable_autoplay")&&(e.capabilities=["atp"]),e.name=b.device,e.app=b.app,(h=b.theme)&&(e.theme=h),t8(" -- with channel params: "+
g.bl(e)),FGa(e),c.start(),s8()||GGa())},JGa=function(){var a=IGa();
P7()&&g.zt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},IGa=function(){var a=r8().Id.$_gos();
var b=y8();b&&z8()&&(l6(a,b)||a.push(b));return xEa(a)},A8=function(){var a=KGa();
!a&&P7()&&jGa()&&(a={key:"cast-selector-receiver",name:jGa()});return a},KGa=function(){var a=IGa(),b=y8();
b||(b=w8());return g.fb(a,function(c){return b&&h6(b,c.key)?!0:!1})},y8=function(){var a=s8();
if(!a)return null;var b=r8().Ke();return m6(b,a)},EGa=function(a){t8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=y8();b&&b.id==a.id?S7(b.id,"YouTube TV"):(b&&B8(),C8(a,1))}else z8()&&B8()},B8=function(){Q7()?N7().stopSession():L7("stopSession called before API ready.");
var a=z8();a&&(a.disconnect(1),D8(null))},E8=function(){var a=z8();
return!!a&&3!=a.getProxyState()},t8=function(a){k7("remote",a)},r8=function(){if(!F8){var a=g.La("yt.mdx.remote.screenService_");
F8=a?new o8(a):null}return F8},s8=function(){return g.La("yt.mdx.remote.currentScreenId_")},LGa=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},MGa=function(){return g.La("yt.mdx.remote.connectData_")},v8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},z8=function(){return g.La("yt.mdx.remote.connection_")},D8=function(a){var b=z8();
v8(null);a||LGa("");g.Ha("yt.mdx.remote.connection_",a,void 0);q8&&(g.A(q8,function(c){c(a)}),q8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},w8=function(){var a=g.Bt();
if(!a)return null;var b=r8();if(!b)return null;b=b.Ke();return m6(b,a)},C8=function(a,b){s8();
y8()&&y8();if(G8)H8=a;else{LGa(a.id);var c=new h8(p8,a,x8());c.connect(b,MGa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){z8()&&(z8(),D8(null))});
D8(c)}},GGa=function(){var a=w8();
a?(t8("Resume connection to: "+i6(a)),C8(a,0)):(r6(),kGa(),t8("Skipping connecting because no session screen found."))},DGa=function(){var a=x8();
if(g.Rb(a)){a=p6();var b=g.zt("yt-remote-session-name")||"",c=g.zt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},x8=function(){return g.La("yt.mdx.remote.channelParams_")||{}},FGa=function(a){a?(g.xt("yt-remote-session-app",a.app),g.xt("yt-remote-session-name",a.name)):(g.At("yt-remote-session-app"),g.At("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.B.call(this);
var d=this;this.module=a;this.H=b;this.Ya=c;this.events=new g.Bs(this);this.M=this.events.K(this.H,"onVolumeChange",this.QB);this.B=!1;this.suggestion=null;this.C=new g.HI(64);this.o=new g.G(this.wD,500,this);this.u=new g.G(this.xD,1E3,this);this.G=new v6(this.GO,0,this);this.A={};this.I=new g.G(this.YD,1E3,this);this.F=new w6(this.seekTo,1E3,this);this.N=g.Ma;g.C(this,this.events);this.events.K(b,"onCaptionsTrackListChanged",this.nL);this.events.K(b,"captionschanged",this.uK);this.events.K(b,"captionssettingschanged",
this.AD);this.events.K(b,"videoplayerreset",this.lr);this.events.K(b,"mdxautoplaycancel",function(){d.Ya.Fy()});
a=this.Ya;a.ga();a.subscribe("proxyStateChange",this.iC,this);a.subscribe("remotePlayerChange",this.Sn,this);a.subscribe("remoteQueueChange",this.lr,this);a.subscribe("previousNextChange",this.eC,this);a.subscribe("nowAutoplaying",this.aC,this);a.subscribe("autoplayDismissed",this.AB,this);g.C(this,this.o);g.C(this,this.u);g.C(this,this.G);g.C(this,this.I);g.C(this,this.F);this.AD();this.lr();this.Sn()},NGa=function(a){a.Wb(0);
a.o.stop();a.Nc(new g.HI(64))},K8=function(a,b){if(J8(a)&&!a.B){var c=null;
b&&(c={style:a.H.getSubtitlesUserSettings()},g.Zb(c,b));a.Ya.mE(a.H.getVideoData(1).videoId,c);a.A=b8(a.Ya).o}},L8=function(a,b){var c=a.H.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.H.getVideoData(1);a.Ya.playVideo(c.videoId,b,d,e,c.playerParams,c.Me,kEa(c));a.Nc(new g.HI(1))},OGa=function(a,b){if(b){var c=a.H.getOption("captions","tracklist",{Qz:1});
c&&c.length?(a.H.setOption("captions","track",b),a.B=!1):(a.H.loadModule("captions"),a.B=!0)}else a.H.setOption("captions","track",{})},J8=function(a){return b8(a.Ya).videoId===a.H.getVideoData(1).videoId},M8=function(){g.T.call(this,{D:"div",
J:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},L:[{D:"div",J:"ytp-mdx-manual-pairing-popup-dialog-inner-content",L:[{D:"div",J:"ytp-mdx-manual-pairing-popup-title",V:"Connecting to your TV on web using a code will be going away soon"},{D:"div",J:"ytp-mdx-manual-pairing-popup-buttons",L:[{D:"button",da:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],V:"Learn more"},{D:"button",da:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],V:"OK"}]}]}]});this.o=new g.rO(this,250);this.learnMoreButton=
this.ba("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ba("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.o);this.K(this.learnMoreButton,"click",this.u);this.K(this.okButton,"click",this.A)},N8=function(){g.T.call(this,{D:"div",
J:"ytp-mdx-popup-dialog",P:{role:"dialog"},L:[{D:"div",J:"ytp-mdx-popup-dialog-inner-content",L:[{D:"div",J:"ytp-mdx-popup-title",V:"You're signed out"},{D:"div",J:"ytp-mdx-popup-description",V:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",J:"ytp-mdx-privacy-popup-buttons",L:[{D:"button",da:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"Cancel"},{D:"button",da:["ytp-button","ytp-mdx-privacy-popup-confirm"],
V:"Confirm"}]}]}]});this.o=new g.rO(this,250);this.cancelButton=this.ba("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ba("ytp-mdx-privacy-popup-confirm");g.C(this,this.o);this.K(this.cancelButton,"click",this.u);this.K(this.confirmButton,"click",this.A)},O8=function(a){g.T.call(this,{D:"div",
J:"ytp-remote",L:[{D:"div",J:"ytp-remote-display-status",L:[{D:"div",J:"ytp-remote-display-status-icon",L:[g.tO()]},{D:"div",J:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.api=a;this.o=new g.rO(this,250);g.C(this,this.o);this.K(a,"presentingplayerstatechange",this.u);PGa(this,g.VD(a))},PGa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.W(b,128)?g.wD("Error on $RECEIVER_NAME",c):b.sb()||g.W(b,4)?g.wD("Playing on $RECEIVER_NAME",c):g.wD("Connected to $RECEIVER_NAME",c);a.oa("statustext",c);a.o.show()}else a.o.hide()},P8=function(a,b){g.kS.call(this,"Play on",0,a,b);
this.H=a;this.Pi={};this.K(a,"onMdxReceiversChange",this.B);this.K(a,"presentingplayerstatechange",this.B);this.B()},Q8=function(a){g.XN.call(this,a);
this.Qf={key:k6(),name:"This computer"};this.og=null;this.subscriptions=[];this.Hv=this.Ya=null;this.Pi=[this.Qf];this.ai=this.Qf;this.Tb=new g.HI(64);this.iA=0;this.jd=-1;this.wl=null;this.Tn=this.xq=!1;this.jk=this.Ol=null;if(!g.vz(this.player.O())){a=this.player;var b=g.lN(a);b&&(b=b.Bj())&&(b=new P8(a,b),g.C(this,b));b=new O8(a);g.C(this,b);g.LN(a,b.element,4);this.Ol=new N8;g.C(this,this.Ol);g.LN(a,this.Ol.element,4);g.P(this.player.O().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.wl=new M8,g.C(this,this.wl),g.LN(a,this.wl.element,4));this.Tn=!!w8();this.xq=!!g.zt("yt-remote-manual-pairing-warning-shown")}},R8=function(a){a.jk&&(a.player.removeEventListener("presentingplayerstatechange",a.jk),a.jk=null)},QGa=function(a,b,c){a.Tb=c;
a.player.R("presentingplayerstatechange",new g.EK(c,b))},RGa=function(a,b,c){var d=!1;
1===b?d=!a.Tn:2===b&&(d=!a.xq);d&&g.GK(c,8)&&(a.player.pauseVideo(),R8(a))},S8=function(a,b){if(b.key!==a.ai.key)if(b.key===a.Qf.key)B8();
else{if(a.wl&&!a.xq&&b!==a.Qf&&"cast-selector-receiver"!==b.key&&g.Ez(a.player.O()))SGa(a);else{var c;(c=!g.P(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.K("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.K("SESSION_INDEX")&&!g.K("LOGGED_IN")))||a.Tn||!a.Ol);(c?0:g.Ez(a.player.O())||g.Iz(a.player.O()))&&TGa(a)}a.ai=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.P(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Aa(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Me,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=kEa(c))&&(d.locationInfo=c);c=d}t8("Connecting to: "+g.bl(b));"cast-selector-receiver"==b.key?(v8(c||null),c=
c||null,Q7()?N7().setLaunchParams(c):L7("setLaunchParams called before ready.")):!c&&E8()&&s8()==b.key?e6("yt-remote-connection-change",!0):(B8(),v8(c||null),c=r8().Ke(),(c=m6(c,b.key))&&C8(c,1))}},TGa=function(a){g.VD(a.player).sb()?a.player.pauseVideo():(a.jk=function(b){RGa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.jk));
a.Ol&&a.Ol.Nb();z8()||(G8=!0)},SGa=function(a){g.VD(a.player).sb()?a.player.pauseVideo():(a.jk=function(b){RGa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.jk));
a.wl&&a.wl.Nb();z8()||(G8=!0)},WEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},J6={"'":"\\'"},UGa={},tEa={HP:"atp",vS:"ska",gS:"que",wR:"mus",uS:"sus",EQ:"dsp",nS:"seq"},s6,o6="",LEa=HEa("loadCastFramework")||HEa("loadCastApplicationFramework"),gGa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Va(v6,g.B);g.k=v6.prototype;g.k.qG=function(a){this.B=arguments;this.o=!1;this.Ka?this.A=(0,g.E)()+this.Jd:this.Ka=g.gg(this.C,this.Jd)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null);this.A=null;this.o=!1;this.B=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.k.W=function(){this.stop();v6.tc.W.call(this)};
g.k.rG=function(){this.A?(this.Ka=g.gg(this.C,this.A-(0,g.E)()),this.A=null):(this.Ka=null,this.u?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};g.t(w6,g.B);g.k=w6.prototype;g.k.wA=function(a){this.A=arguments;this.Ka||this.u?this.o=!0:x6(this)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null,this.o=!1,this.A=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.o||this.Ka||(this.o=!1,x6(this))};
g.k.W=function(){g.B.prototype.W.call(this);this.stop()};z6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
z6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};A6.prototype.o=null;A6.prototype.getOptions=function(){var a;(a=this.o)||(a={},PEa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var T8;g.Va(OEa,A6);T8=new OEa;g.k=B6.prototype;g.k.Ej=null;g.k.fg=!1;g.k.gm=null;g.k.ax=null;g.k.Sl=null;g.k.Zl=null;g.k.Wh=null;g.k.Qi=null;g.k.kk=null;g.k.cd=null;g.k.Bo=0;g.k.lg=null;g.k.ls=null;g.k.ki=null;g.k.bn=-1;g.k.nD=!0;g.k.kj=!1;g.k.fu=0;g.k.xr=null;var UEa={},E6={};g.k=B6.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.PN=function(a){a=a.target;var b=this.xr;b&&3==S6(a)?b.wA():this.iE(a)};
g.k.iE=function(a){try{if(a==this.cd)a:{var b=S6(this.cd),c=this.cd.F,d=this.cd.getStatus();if(g.ue&&!g.Xd(10)||g.we&&!g.Wd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ph&&!U6(this.cd))break a;this.kj||4!=b||7==c||(8==c||0>=d?this.o.Wf(3):this.o.Wf(2));L6(this);var e=this.cd.getStatus();this.bn=e;var f=U6(this.cd);(this.fg=200==e)?(4==b&&H6(this),this.F?(VEa(this,b,f),g.Ph&&this.fg&&3==b&&(this.B.ma(this.u,"tick",this.JN),this.u.start())):G6(this,f),this.fg&&!this.kj&&(4==b?this.o.Vp(this):(this.fg=
!1,D6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ki=3,F6(13)):(this.ki=0,F6(14)),H6(this),I6(this))}}catch(h){this.cd&&U6(this.cd)}finally{}};
g.k.JN=function(){var a=S6(this.cd),b=U6(this.cd);this.Bo<b.length&&(L6(this),VEa(this,a,b),this.fg&&4!=a&&D6(this))};
g.k.dN=function(a){K6((0,g.x)(this.cN,this,a),0)};
g.k.cN=function(a){this.kj||(L6(this),G6(this,a),D6(this))};
g.k.sC=function(a){K6((0,g.x)(this.bN,this,a),0)};
g.k.bN=function(a){this.kj||(H6(this),this.fg=a,this.o.Vp(this),this.o.Wf(4))};
g.k.cancel=function(){this.kj=!0;H6(this)};
g.k.oN=function(){this.gm=null;var a=(0,g.E)();0<=a-this.ax?(2!=this.Zl&&this.o.Wf(3),H6(this),this.ki=2,F6(18),I6(this)):YEa(this,this.ax-a)};
g.k.getLastError=function(){return this.ki};g.k=aFa.prototype;g.k.du=null;g.k.ye=null;g.k.yr=!1;g.k.zz=null;g.k.Dp=null;g.k.Fu=null;g.k.eu=null;g.k.lf=null;g.k.ph=-1;g.k.an=null;g.k.tm=null;g.k.connect=function(a){this.eu=a;a=N6(this.o,null,this.eu);F6(3);this.zz=(0,g.E)();var b=this.o.I;null!=b?(this.an=b[0],(this.tm=b[1])?(this.lf=1,bFa(this)):(this.lf=2,P6(this))):(b6(a,"MODE","init"),this.ye=new B6(this,void 0,void 0,void 0),this.ye.Ej=this.du,C6(this.ye,a,!1,null,!0),this.lf=0)};
g.k.rF=function(a){if(a)this.lf=2,P6(this);else{F6(4);var b=this.o;b.vg=b.Yh.ph;a7(b,9)}a&&this.Wf(2)};
g.k.wt=function(a){return this.o.wt(a)};
g.k.abort=function(){this.ye&&(this.ye.cancel(),this.ye=null);this.ph=-1};
g.k.yz=function(){return!1};
g.k.jC=function(a,b){this.ph=a.bn;if(0==this.lf)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.vg=this.ph;a7(c,2);return}this.an=c[0];this.tm=c[1]}else c=this.o,c.vg=this.ph,a7(c,2);else if(2==this.lf)if(this.yr)F6(7),this.Fu=(0,g.E)();else if("11111"==b){if(F6(6),this.yr=!0,this.Dp=(0,g.E)(),c=this.Dp-this.zz,!g.ue||g.Xd(10)||500>c)this.ph=200,this.ye.cancel(),F6(12),O6(this.o,this,!0)}else F6(8),this.Dp=this.Fu=(0,g.E)(),this.yr=!1};
g.k.Vp=function(){this.ph=this.ye.bn;if(this.ye.fg)0==this.lf?this.tm?(this.lf=1,bFa(this)):(this.lf=2,P6(this)):2==this.lf&&((!g.ue||g.Xd(10)?!this.yr:200>this.Fu-this.Dp)?(F6(11),O6(this.o,this,!1)):(F6(12),O6(this.o,this,!0)));else{0==this.lf?F6(9):2==this.lf&&F6(10);var a=this.o;this.ye.getLastError();a.vg=this.ph;a7(a,2)}};
g.k.mo=function(){return this.o.mo()};
g.k.isActive=function(){return this.o.isActive()};
g.k.Wf=function(a){this.o.Wf(a)};g.Va(Q6,g.wf);var gFa=/^https?$/i,VGa=["POST","PUT"];g.k=Q6.prototype;
g.k.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.M+"; newUri="+a);b=b?b.toUpperCase():"GET";this.M=a;this.B="";this.F=0;this.fa=b;this.X=!1;this.A=!0;this.o=this.T?QEa(this.T):QEa(T8);this.U=this.T?this.T.getOptions():T8.getOptions();this.o.onreadystatechange=(0,g.x)(this.fC,this);try{d6(T6(this,"Opening Xhr")),this.Z=!0,this.o.open(b,String(a),!0),this.Z=!1}catch(f){d6(T6(this,"Error opening Xhr: "+f.message));fFa(this,f);return}a=c||
"";var e=this.headers.clone();d&&pEa(d,function(f,h){e.set(h,f)});
d=g.fb(e.jf(),dFa);c=g.v.FormData&&a instanceof g.v.FormData;!g.jb(VGa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.o.setRequestHeader(h,f)},this);
this.la&&(this.o.responseType=this.la);"withCredentials"in this.o&&this.o.withCredentials!==this.Y&&(this.o.withCredentials=this.Y);try{iFa(this),0<this.G&&(this.S=cFa(this.o),d6(T6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.S)),this.S?(this.o.timeout=this.G,this.o.ontimeout=(0,g.x)(this.Az,this)):this.N=g.gg(this.Az,this.G,this)),d6(T6(this,"Sending request")),this.I=!0,this.o.send(a),this.I=!1}catch(f){d6(T6(this,"Send error: "+f.message)),fFa(this,f)}};
g.k.Az=function(){"undefined"!=typeof g.y1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.F=8,T6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.o&&this.A&&(T6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.F=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),R6(this))};
g.k.W=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),R6(this,!0));Q6.tc.W.call(this)};
g.k.fC=function(){this.ga()||(this.Z||this.I||this.C?hFa(this):this.kM())};
g.k.kM=function(){hFa(this)};
g.k.isActive=function(){return!!this.o};
g.k.getStatus=function(){try{return 2<S6(this)?this.o.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.k=V6.prototype;g.k.al=null;g.k.Nm=null;g.k.oe=null;g.k.Dc=null;g.k.cu=null;g.k.Fp=null;g.k.dy=null;g.k.Up=null;g.k.In=0;g.k.NJ=0;g.k.Gd=null;g.k.ci=null;g.k.Xg=null;g.k.pj=null;g.k.Yh=null;g.k.hs=null;g.k.sl=-1;g.k.hA=-1;g.k.vg=-1;g.k.Tk=0;g.k.Hk=0;g.k.lj=8;var b7=new g.wf;g.Va(lFa,g.Ve);g.Va(mFa,g.Ve);g.Va(nFa,g.Ve);g.k=V6.prototype;g.k.connect=function(a,b,c,d,e){F6(0);this.cu=b;this.Nm=c||{};d&&void 0!==e&&(this.Nm.OSID=d,this.Nm.OAID=e);this.F?(K6((0,g.x)(this.ty,this,a),100),rFa(this)):this.ty(a)};
g.k.ty=function(a){this.Yh=new aFa(this);this.Yh.du=this.al;this.Yh.u=this.C;this.Yh.connect(a)};
g.k.yz=function(){return 0==this.o};
g.k.rC=function(a){this.ci=null;uFa(this,a)};
g.k.qC=function(){this.Xg=null;this.Dc=new B6(this,this.A,"rpc",this.G);this.Dc.Ej=this.al;this.Dc.fu=0;var a=this.dy.clone();$5(a,"RID","rpc");$5(a,"SID",this.A);$5(a,"CI",this.hs?"0":"1");$5(a,"AID",this.sl);W6(this,a);if(!g.ue||g.Xd(10))$5(a,"TYPE","xmlhttp"),C6(this.Dc,a,!0,this.Up,!1);else{$5(a,"TYPE","html");var b=this.Dc,c=!!this.Up;b.Zl=3;b.Wh=a6(a.clone());XEa(b,c)}};
g.k.jC=function(a,b){if(0!=this.o&&(this.Dc==a||this.oe==a))if(this.vg=a.bn,this.oe==a&&3==this.o)if(7<this.lj){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Xg){if(this.Dc)if(this.Dc.Sl+3E3<this.oe.Sl)Y6(this),this.Dc.cancel(),this.Dc=null;else break a;$6(this);F6(19)}}else this.hA=c[1],0<this.hA-this.sl&&37500>c[2]&&this.hs&&0==this.Hk&&!this.pj&&(this.pj=K6((0,g.x)(this.qK,this),6E3));else a7(this,11)}else b!=UGa.eQ.o&&a7(this,11);else if(this.Dc==
a&&Y6(this),!g.pc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.sl=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.Up=e[2],e=e[3],null!=e?this.lj=e:this.lj=6,this.o=3,this.Gd&&this.Gd.py(),this.dy=N6(this,this.mo()?this.Up:null,this.cu),vFa(this)):"stop"==e[0]&&a7(this,7):3==this.o&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.Gd&&this.Gd.oy(e),this.Hk=0)}}};
g.k.qK=function(){null!=this.pj&&(this.pj=null,this.Dc.cancel(),this.Dc=null,$6(this),F6(20))};
g.k.Vp=function(a){if(this.Dc==a){Y6(this);this.Dc=null;var b=2}else if(this.oe==a)this.oe=null,b=1;else return;this.vg=a.bn;if(0!=this.o)if(a.fg)1==b?(b=(0,g.E)()-a.Sl,b7.dispatchEvent(new mFa(b7,a.kk?a.kk.length:0,b,this.Tk)),X6(this),this.B.length=0):vFa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.vg)){if(d=1==b)this.oe||this.ci||1==this.o||2<=this.Tk?d=!1:(this.ci=K6((0,g.x)(this.rC,this,a),wFa(this,this.Tk)),this.Tk++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,
5);break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.k.PF=function(a){if(!g.jb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.k.wO=function(a){a?F6(2):(F6(1),xFa(this,8))};
g.k.wt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new Q6;a.Y=!1;return a};
g.k.isActive=function(){return!!this.Gd&&this.Gd.isActive(this)};
g.k.Wf=function(a){b7.dispatchEvent(new nFa(b7,a))};
g.k.mo=function(){return!(!g.ue||g.Xd(10))};
g.k=yFa.prototype;g.k.py=function(){};
g.k.oy=function(){};
g.k.ny=function(){};
g.k.ct=function(){};
g.k.Xy=function(){return{}};
g.k.isActive=function(){return!0};g.k=zFa.prototype;g.k.isEmpty=function(){return g.kb(this.o)&&g.kb(this.u)};
g.k.clear=function(){this.o=[];this.u=[]};
g.k.contains=function(a){return g.jb(this.o,a)||g.jb(this.u,a)};
g.k.remove=function(a){var b=this.o;var c=(0,g.Mya)(b,a);0<=c?(g.nb(b,c),b=!0):b=!1;return b||g.ob(this.u,a)};
g.k.Wd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Va(c7,g.B);g.k=c7.prototype;g.k.WM=function(){this.Jd=Math.min(3E5,2*this.Jd);this.A();this.u&&this.start()};
g.k.start=function(){var a=this.Jd+15E3*Math.random();this.o.gb(a);this.u=(0,g.E)()+a};
g.k.stop=function(){this.o.stop();this.u=0};
g.k.isActive=function(){return this.o.isActive()};
g.k.reset=function(){this.o.stop();this.Jd=5E3};g.Va(d7,yFa);g.k=d7.prototype;g.k.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.k.Gi=function(a){return this.A.Fj(a)};
g.k.R=function(a,b){return this.A.R.apply(this.A,arguments)};
g.k.dispose=function(){this.Pc||(this.Pc=!0,g.Te(this.A),CFa(this),g.Te(this.u),this.u=null,this.S=function(){return""})};
g.k.ga=function(){return this.Pc};
g.k.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.M="";this.u.stop();this.C=a||null;this.B=b||0;a=this.N+"/test";b=this.N+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.U),e=this.o;e&&(e.Gd=null);d.Gd=this;this.o=d;e7(this);e?this.o.connect(a,b,this.F,e.A,e.sl):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Zb(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):f7(this)&&(e7(this),sFa(this.o,c))};
g.k.py=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)sFa(this.o,a[b])}this.R("handlerOpened")};
g.k.ny=function(a){var b=2==a&&401==this.o.vg;4==a||b||this.u.start();this.R("handlerError",a)};
g.k.ct=function(a){if(!this.u.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.k.Xy=function(){var a={v:2};this.M&&(a.gsessionid=this.M);0!=this.B&&(a.ui=""+this.B);0!=this.I&&(a.ui=""+this.I);this.C&&g.Zb(a,this.C);return a};
g.k.oy=function(a){"S"==a[0]?this.M=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),qFa(this.o)):this.R("handlerMessage",new AFa(a[0],a[1]))};
g.k.bO=function(){this.u.isActive();var a=this.o,b=0;a.Dc&&b++;a.oe&&b++;0==b&&this.connect(this.C,this.B)};g7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
g7.prototype.C=function(a){a(Error("request timed out"))};var KFa=(0,g.E)(),j7=null,m7=Array(50),l7=-1,n7=!1;g.Va(o7,g.N);o7.prototype.Ke=function(){return this.screens};
o7.prototype.contains=function(a){return!!l6(this.screens,a)};
o7.prototype.get=function(a){return a?m6(this.screens,a):null};
o7.prototype.info=function(a){k7(this.F,a)};g.t(p7,g.N);g.k=p7.prototype;g.k.start=function(){!this.o&&isNaN(this.Ka)&&this.nE()};
g.k.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ka)||(g.bp(this.Ka),this.Ka=NaN)};
g.k.W=function(){this.stop();g.N.prototype.W.call(this)};
g.k.nE=function(){this.Ka=NaN;this.o=g.Kq(h7(this.F,"/pairing/get_screen"),{method:"POST",Gb:{pairing_code:this.C},timeout:5E3,onSuccess:(0,g.x)(this.ZO,this),onError:(0,g.x)(this.YO,this),Se:(0,g.x)(this.aP,this)})};
g.k.ZO=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.R("pairingComplete",new g6(c))};
g.k.YO=function(a){this.o=null;a.status&&404==a.status?this.u>=WGa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=WGa[this.u],this.Ka=g.$o((0,g.x)(this.nE,this),a),this.u++):this.R("pairingFailed",Error("Server error "+a.status))};
g.k.aP=function(){this.o=null;this.R("pairingFailed",Error("Server not responding"))};
var WGa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Va(r7,o7);g.k=r7.prototype;g.k.start=function(){q7(this)&&this.R("screenChange");!g.zt("yt-remote-lounge-token-expiration")&&OFa(this);g.bp(this.o);this.o=g.$o((0,g.x)(this.start,this),1E4)};
g.k.add=function(a,b){q7(this);LFa(this,a);s7(this,!1);this.R("screenChange");b(a);a.token||OFa(this)};
g.k.remove=function(a,b){var c=q7(this);NFa(this,a)&&(s7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.k.ds=function(a,b,c,d){var e=q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,s7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.k.W=function(){g.bp(this.o);r7.tc.W.call(this)};
g.k.AG=function(a){q7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}s7(this,!b);b&&k7(this.F,"Missed "+b+" lounge tokens.")};
g.k.zG=function(a){k7(this.F,"Requesting lounge tokens failed: "+a)};g.t(u7,g.N);g.k=u7.prototype;g.k.start=function(){var a=parseInt(g.zt("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.E)()-144E5<a?0:a)?w7(this):(this.B=(0,g.E)()+3E5,g.xt("yt-remote-fast-check-period",this.B),this.Xv())};
g.k.isEmpty=function(){return g.Rb(this.o)};
g.k.update=function(){t7("Updating availability on schedule.");var a=this.F(),b=g.Fb(this.o,function(c,d){return c&&!!m6(a,d)},this);
v7(this,b)};
g.k.W=function(){g.bp(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.N.prototype.W.call(this)};
g.k.Xv=function(){g.bp(this.A);this.A=NaN;this.u&&this.u.abort();var a=RFa(this);if(c6(a)){var b=h7(this.C,"/pairing/get_screen_availability");this.u=i7(this.C,b,{lounge_token:g.Lb(a).join(",")},(0,g.x)(this.FM,this,a),(0,g.x)(this.EM,this))}else v7(this,{}),w7(this)};
g.k.FM=function(a,b){this.u=null;var c=g.Lb(RFa(this));if(g.Bb(c,g.Lb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;v7(this,d);w7(this)}else this.pc("Changing Screen set during request."),this.Xv()};
g.k.EM=function(a){this.pc("Screen availability failed: "+a);this.u=null;w7(this)};
g.k.pc=function(a){k7("OnlineScreenService",a)};g.Va(x7,o7);g.k=x7.prototype;g.k.start=function(){this.u.start();this.o.start();this.screens.length&&(this.R("screenChange"),this.o.isEmpty()||this.R("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.k.ds=function(a,b,c,d){this.u.contains(a)?this.u.ds(a,b,c,d):(a="Updating name of unknown screen: "+a.name,k7(this.F,a),d(Error(a)))};
g.k.Ke=function(a){return a?this.screens:g.qb(this.screens,g.He(this.A,function(b){return!this.contains(b)},this))};
g.k.oE=function(){return g.He(this.Ke(!0),function(a){return!!this.o.o[a.id]},this)};
g.k.pE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new p7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(h){g.Te(f);d(y7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Te(f);e(h)});
f.start();return(0,g.x)(f.stop,f)};
g.k.cP=function(a,b,c,d){g.Kq(h7(this.C,"/pairing/get_screen"),{method:"POST",Gb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var h=new g6(f.screen||{});if(!h.name||VFa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);VFa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(y7(this,h))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Se:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.k.W=function(){g.Te(this.u);g.Te(this.o);x7.tc.W.call(this)};
g.k.HG=function(){WFa(this);this.R("screenChange");this.o.update()};
x7.prototype.dispose=x7.prototype.dispose;g.Va(A7,g.N);g.k=A7.prototype;g.k.getScreen=function(){return this.G};
g.k.kr=function(a){this.G=a;this.R("sessionScreen",this.G)};
g.k.Re=function(a){this.ga()||(a&&B7(this,""+a),this.G=null,this.R("sessionScreen",null))};
g.k.info=function(a){k7(this.U,a)};
g.k.rE=function(){return null};
g.k.jw=function(a){var b=this.o;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){B7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.W=function(){this.jw("");A7.tc.W.call(this)};g.t(C7,A7);g.k=C7.prototype;g.k.iw=function(a){if(this.u){if(this.u==a)return;B7(this,"Overriding cast sesison with new session object");this.u.removeUpdateListener(this.C);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.u=a;this.u.addUpdateListener(this.C);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);YFa(this)};
g.k.ul=function(a){this.info("launchWithParams no-op for Cast: "+g.bl(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.x)(function(){this.Re()},this),(0,g.x)(function(){this.Re(Error("Failed to stop receiver app."))},this)):this.Re(Error("Stopping cast device witout session."))};
g.k.jw=function(){};
g.k.W=function(){this.info("disposeInternal");g.bp(this.A);this.A=0;this.u&&(this.u.removeUpdateListener(this.C),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.u=null;A7.prototype.W.call(this)};
g.k.wN=function(a,b){if(!this.ga())if(b){var c=y6(b);if(g.Qa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.bl(c));switch(d){case "mdxSessionStatus":XFa(this,c.screenId);break;default:B7(this,"Unknown youtube message: "+d)}}else B7(this,"Unable to parse message.")}else B7(this,"No data in message.")};
g.k.pz=function(a,b,c,d){UFa(this.I,this.o.label,a,this.o.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(B7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.$o((0,g.x)(this.pz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.rE=function(){return this.u};
g.k.dP=function(a){this.ga()||a||(B7(this,"Cast session died."),this.Re())};g.t(D7,A7);g.k=D7.prototype;g.k.iw=function(a){this.A=a;this.A.addUpdateListener(this.S)};
g.k.ul=function(a){this.N=a;this.C()};
g.k.stop=function(){this.u();this.u=g.Ma;g.bp(this.B);this.A?this.A.stop((0,g.x)(this.Re,this,null),(0,g.x)(this.Re,this,"Failed to stop DIAL device.")):this.Re()};
g.k.W=function(){this.u();this.u=g.Ma;g.bp(this.B);this.A&&this.A.removeUpdateListener(this.S);this.A=null;A7.prototype.W.call(this)};
g.k.gP=function(a){this.ga()||a||(B7(this,"DIAL session died."),this.u(),this.u=g.Ma,this.Re())};
g.k.nu=function(a){this.M=k6();if(this.N){var b=new chrome.cast.DialLaunchResponse(!0,$Fa(this));a(b);ZFa(this)}else this.C=(0,g.x)(function(){g.bp(this.B);this.C=g.Ma;this.B=NaN;var c=new chrome.cast.DialLaunchResponse(!0,$Fa(this));a(c);ZFa(this)},this),this.B=g.$o((0,g.x)(function(){this.C()},this),100)};
g.k.YG=function(a,b,c){UFa(this.I,this.F.receiver.label,a,this.o.friendlyName,(0,g.x)(function(d){d&&d.token?(this.kr(d),b(new chrome.cast.DialLaunchResponse(!1))):this.nu(b,c)},this),(0,g.x)(function(d){B7(this,"Failed to get DIAL screen: "+d);
this.nu(b,c)},this))};g.t(E7,A7);E7.prototype.stop=function(){this.Re()};
E7.prototype.iw=function(){};
E7.prototype.ul=function(){g.bp(this.u);this.u=NaN;var a=m6(this.I.Ke(),this.o.label);a?this.kr(a):this.Re(Error("No such screen"))};
E7.prototype.W=function(){g.bp(this.u);this.u=NaN;A7.prototype.W.call(this)};g.t(F7,g.N);g.k=F7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.I||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.pM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.mC,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.JK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ga()||
(chrome.cast.addReceiverActionListener(this.B),HFa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.qE,this)),this.A=bGa(this),chrome.cast.setCustomReceivers(this.A,g.Ma,(0,g.x)(function(h){this.pc("Failed to set initial custom receivers: "+g.bl(h))},this)),this.R("yt-remote-cast2-availability-change",H7(this)),b(!0))},this),(0,g.x)(function(h){this.pc("Failed to initialize API: "+g.bl(h));
b(!1)},this))};
g.k.hO=function(a,b){G7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)G7("Unsetting old screen status: "+this.o.o.friendlyName),I7(this,null)}if(a&&b){if(!this.o){c=m6(this.u.Ke(),a);if(!c){G7("setConnectedScreenStatus: Unknown screen.");return}var d=aGa(this,c);d||(G7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Ma,(0,g.x)(function(e){this.pc("Failed to set initial custom receivers: "+g.bl(e))},this)));
G7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);I7(this,new E7(this.u,d),!0)}this.o.jw(b)}else G7("setConnectedScreenStatus: no screen.")};
g.k.iO=function(a){this.ga()?this.pc("Setting connection data on disposed cast v2"):this.o?this.o.ul(a):this.pc("Setting connection data without a session")};
g.k.fP=function(){this.ga()?this.pc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),I7(this,null)):G7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.mC,this),(0,g.x)(this.IM,this))};
g.k.W=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.qE,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=EFa,b=g.La("yt.mdx.remote.debug.handlers_");g.ob(b||[],a);g.Te(this.o);g.N.prototype.W.call(this)};
g.k.pc=function(a){k7("Controller",a)};
g.k.oC=function(a,b){this.o==a&&(b||I7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.k.lM=function(a,b){if(!this.ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),G7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.o.label!=a.label)G7("onReceiverAction_: Stopping active receiver: "+this.o.o.friendlyName),this.o.stop();else{G7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.R("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:I7(this,
new E7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:I7(this,new D7(this.u,a,this.F));break;case chrome.cast.ReceiverType.CAST:I7(this,new C7(this.u,a));break;default:this.pc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.o.label==a.label?this.o.stop():this.pc("Stopping receiver w/o session: "+a.friendlyName)}else this.pc("onReceiverAction_ called without receiver.")};
g.k.JK=function(a){if(this.ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.pc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.o:null;if(!c||c.label!=b.label)return this.pc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return G7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.pc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);I7(this,new D7(this.u,b,this.F))}b=this.o;b.F=a;return b.F.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.YG,b,(b.F.extraData||{}).screenId||null)):new Promise((0,g.x)(b.nu,b))};
g.k.mC=function(a){if(!this.ga()){G7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)G7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),I7(this,new C7(this.u,b),!0);else{this.pc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.o,d=m6(this.u.Ke(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(G7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Te(this.o),this.o=new C7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.oC,this,this.o)),this.o.ul(null));this.o.iw(a)}}};
g.k.eP=function(){return this.o?this.o.rE():null};
g.k.IM=function(a){this.ga()||(this.pc("Failed to estabilish a session: "+g.bl(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&I7(this,null))};
g.k.pM=function(a){G7("Receiver availability updated: "+a);if(!this.ga()){var b=H7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;H7(this)!=b&&this.R("yt-remote-cast2-availability-change",H7(this))}};
g.k.qE=function(){this.ga()||(this.A=bGa(this),G7("Updating custom receivers: "+g.bl(this.A)),chrome.cast.setCustomReceivers(this.A,g.Ma,(0,g.x)(function(){this.pc("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",H7(this)))};
F7.prototype.setLaunchParams=F7.prototype.iO;F7.prototype.setConnectedScreenStatus=F7.prototype.hO;F7.prototype.stopSession=F7.prototype.fP;F7.prototype.getCastSession=F7.prototype.eP;F7.prototype.requestSession=F7.prototype.requestSession;F7.prototype.init=F7.prototype.init;F7.prototype.dispose=F7.prototype.dispose;var O7=[];g.k=T7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";U7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.wg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.I=a.duration,this.M=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.k.sb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.A?this.I+V7(this):this.I};
g.k.clone=function(){return new T7(Z7(this))};g.t(a8,g.N);g.k=a8.prototype;g.k.play=function(){1==this.o?(this.u?this.u.play(null,g.Ma,g8(this,"play")):f8(this,"play"),e8(this,1,X7(b8(this))),this.R("remotePlayerChange")):c8(this,this.play)};
g.k.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ma,g8(this,"pause")):f8(this,"pause"),e8(this,2,X7(b8(this))),this.R("remotePlayerChange")):c8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.o){if(this.u){var b=b8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.sb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ma,g8(this,"seekTo",{newTime:a}))}else f8(this,"seekTo",{newTime:a});e8(this,3,a);this.R("remotePlayerChange")}else c8(this,g.Ta(this.seekTo,a))};
g.k.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ma,g8(this,"stopVideo")):f8(this,"stopVideo");var a=b8(this);a.index=-1;a.videoId="";U7(a);d8(this,a);this.R("remotePlayerChange")}else c8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.o){var c=b8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){k7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.pc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){k7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.pc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f8(this,"setVolume",e)}c.muted=b;c.volume=a;d8(this,c)}else c8(this,g.Ta(this.setVolume,a,b))};
g.k.mE=function(a,b){if(1==this.o){var c=b8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.bl(b.style),g.Zb(d,c.o));f8(this,"setSubtitlesTrack",d);d8(this,c)}else c8(this,g.Ta(this.mE,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();f8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=b8(this);d.audioTrackId=c;d8(this,d)}else c8(this,g.Ta(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=b8(this);c=c||0;var m={videoId:a,currentIndex:c};Y7(l,a,c);void 0!==b&&(W7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.bl(h));f8(this,"setPlaylist",m);d||d8(this,l)};
g.k.tr=function(a,b){if(1==this.o){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"previous")}else c8(this,g.Ta(this.tr,a,b))};
g.k.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"next")}else c8(this,g.Ta(this.nextVideo,a,b))};
g.k.Fy=function(){1==this.o?f8(this,"dismissAutoplay"):c8(this,this.Fy)};
g.k.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.R("proxyStateChange",a,this.o)}g.N.prototype.dispose.call(this)};
g.k.W=function(){oGa(this);this.B=null;this.C.clear();$7(this,null);g.N.prototype.W.call(this)};
g.k.dx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.kb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.k.hM=function(a,b){this.R(a,b)};
g.k.wK=function(a){if(!a)this.Mn(null),$7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=b8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)k7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d8(this,b)}};
g.k.Mn=function(a){k7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.I);if(this.u=a)this.u.addUpdateListener(this.I),pGa(this),this.R("remotePlayerChange")};
g.k.vK=function(a){a?(pGa(this),this.R("remotePlayerChange")):this.Mn(null)};
g.k.Bw=function(){f8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.EK=function(){var a=lGa();a&&$7(this,a)};
g.k.pc=function(a){k7("CP",a)};g.t(h8,g.N);g.k=h8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.ib.listId=c);this.ib.videoId=d;this.ib.index=h||0;this.ib.state=3;W7(this.ib,m);this.B="UNSUPPORTED";i8("Connecting with setPlaylist and params: "+g.bl(l));this.o.connect({method:"setPlaylist",
params:g.bl(l)},a,BEa())}else i8("Connecting without params"),this.o.connect({},a,BEa());rGa(this)};
g.k.dispose=function(){this.ga()||(this.R("beforeDispose"),j8(this,3));g.N.prototype.dispose.call(this)};
g.k.W=function(){k8(this);m8(this);l8(this);g.bp(this.G);this.G=NaN;g.bp(this.I);this.I=NaN;this.A=null;g.xp(this.U);this.U.length=0;this.o.dispose();g.N.prototype.W.call(this);this.B=this.F=this.u=this.ib=this.o=null};
g.k.tG=function(){this.Pk(2)};
g.k.AK=function(){i8("Channel opened");this.S&&(this.S=!1,l8(this),this.N=g.$o((0,g.x)(function(){i8("Timing out waiting for a screen.");this.Pk(1)},this),15E3));
FEa(BFa(this.o),this.T)};
g.k.xK=function(){i8("Channel closed");isNaN(this.C)?r6(!0):r6();this.dispose()};
g.k.yK=function(a){r6();isNaN(this.Wm())?(i8("Channel error: "+a+" without reconnection"),this.dispose()):(this.S=!0,i8("Channel error: "+a+" with reconnection in "+this.Wm()+" ms"),j8(this,2))};
g.k.zK=function(a){a.params?i8("Received: action="+a.action+", params="+g.bl(a.params)):i8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=y6(a.params.devices);this.u=g.Nc(a,function(c){return new f6(c)});
a=!!g.fb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
uGa(this,a);break;case "loungeScreenDisconnected":g.pb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
uGa(this,!1);break;case "remoteConnected":var b=new f6(y6(a.params.device));g.fb(this.u,function(c){return b?c.id==b.id:!1})||lEa(this.u,b);
break;case "remoteDisconnected":b=new f6(y6(a.params.device));g.pb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":wGa(this,a);break;case "nowPlaying":yGa(this,a);break;case "onStateChange":xGa(this,a);break;case "onAdStateChange":zGa(this,a);break;case "onVolumeChanged":AGa(this,a);break;case "onSubtitlesTrackChanged":vGa(this,a);break;case "nowAutoplaying":BGa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.R("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.R("autoplayModeChange",this.B);"DISABLED"==this.B&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":CGa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:i8("Unrecognized action: "+a.action)}};
g.k.XN=function(){if(this.A){var a=this.A;this.A=null;this.ib.videoId!=a&&n8(this,"getNowPlaying")}};
g.k.kG=function(){var a=3;this.ga()||(a=0,isNaN(this.Wm())?f7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Pk=function(a){i8("Disconnecting with "+a);k8(this);this.R("beforeDisconnect",a);1==a&&r6();CFa(this.o,a);this.dispose()};
g.k.iG=function(){var a=this.ib;this.A&&(a=this.ib.clone(),Y7(a,this.A,a.index));return Z7(a)};
g.k.jO=function(a){var b=new T7(a);b.videoId&&b.videoId!=this.ib.videoId&&(this.A=b.videoId,g.bp(this.G),this.G=g.$o((0,g.x)(this.XN,this),5E3));var c=[];this.ib.listId==b.listId&&this.ib.videoId==b.videoId&&this.ib.index==b.index||c.push("remoteQueueChange");this.ib.playerState==b.playerState&&this.ib.volume==b.volume&&this.ib.muted==b.muted&&X7(this.ib)==X7(b)&&g.bl(this.ib.o)==g.bl(b.o)||c.push("remotePlayerChange");this.ib.reset(a);g.A(c,function(d){this.R(d)},this)};
g.k.nz=function(){var a=this.o.F.id,b=g.fb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Wm=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.E)():NaN};
g.k.XF=function(){return this.B||"UNSUPPORTED"};
g.k.YF=function(){return this.F||""};
g.k.XO=function(){if(!isNaN(this.Wm())){var a=this.o.u;g.Sn(a.o);a.start()}};
g.k.fO=function(a,b){n8(this,a,b);tGa(this)};
g.k.lE=function(){var a=g.Tq("SID","")||"",b=g.Tq("SAPISID","")||"";if(!a&&!b)return"";a=g.Hg(g.mg(a),2);b=g.Hg(g.mg(b),2);return g.Hg(g.mg(a+","+b),2)};
h8.prototype.subscribe=h8.prototype.subscribe;h8.prototype.unsubscribeByKey=h8.prototype.Gi;h8.prototype.getProxyState=h8.prototype.kG;h8.prototype.disconnect=h8.prototype.Pk;h8.prototype.getPlayerContextData=h8.prototype.iG;h8.prototype.setPlayerContextData=h8.prototype.jO;h8.prototype.getOtherConnectedRemoteId=h8.prototype.nz;h8.prototype.getReconnectTimeout=h8.prototype.Wm;h8.prototype.getAutoplayMode=h8.prototype.XF;h8.prototype.getAutoplayVideoId=h8.prototype.YF;h8.prototype.reconnect=h8.prototype.XO;
h8.prototype.sendMessage=h8.prototype.fO;h8.prototype.getXsrfToken=h8.prototype.lE;g.t(o8,o7);g.k=o8.prototype;g.k.Ke=function(a){return this.Id.$_gs(a)};
g.k.contains=function(a){return!!this.Id.$_c(a)};
g.k.get=function(a){return this.Id.$_g(a)};
g.k.start=function(){this.Id.$_st()};
g.k.add=function(a,b,c){this.Id.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Id.$_r(a,b,c)};
g.k.ds=function(a,b,c,d){this.Id.$_un(a,b,c,d)};
g.k.W=function(){for(var a=0,b=this.o.length;a<b;++a)this.Id.$_ubk(this.o[a]);this.o.length=0;this.Id=null;o7.prototype.W.call(this)};
g.k.bP=function(){this.R("screenChange")};
g.k.LL=function(){this.R("onlineScreenChange")};
x7.prototype.$_st=x7.prototype.start;x7.prototype.$_gspc=x7.prototype.cP;x7.prototype.$_gsppc=x7.prototype.pE;x7.prototype.$_c=x7.prototype.contains;x7.prototype.$_g=x7.prototype.get;x7.prototype.$_a=x7.prototype.add;x7.prototype.$_un=x7.prototype.ds;x7.prototype.$_r=x7.prototype.remove;x7.prototype.$_gs=x7.prototype.Ke;x7.prototype.$_gos=x7.prototype.oE;x7.prototype.$_s=x7.prototype.subscribe;x7.prototype.$_ubk=x7.prototype.Gi;var H8=null,G8=!1,p8=null,q8=null,F8=null,u8=[];g.t(I8,g.B);g.k=I8.prototype;g.k.W=function(){g.B.prototype.W.call(this);this.o.stop();this.u.stop();this.G.stop();this.N();var a=this.Ya;a.unsubscribe("proxyStateChange",this.iC,this);a.unsubscribe("remotePlayerChange",this.Sn,this);a.unsubscribe("remoteQueueChange",this.lr,this);a.unsubscribe("previousNextChange",this.eC,this);a.unsubscribe("nowAutoplaying",this.aC,this);a.unsubscribe("autoplayDismissed",this.AB,this);this.Ya=this.module=null};
g.k.MA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Ya.o)if(J8(this)){if(!b8(this.Ya).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":b8(this.Ya).sb()?this.Ya.pause():this.Ya.play();break;case "control_play":this.Ya.play();break;case "control_pause":this.Ya.pause();break;case "control_seek":this.F.wA(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.H.getCurrentTime();L8(this,0===c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.uK=function(a){this.G.qG(a)};
g.k.GO=function(a){this.MA("control_subtitles_set_track",g.Rb(a)?null:a)};
g.k.AD=function(){var a=this.H.getOption("captions","track");g.Rb(a)||K8(this,a)};
g.k.Wb=function(a){this.module.Wb(a,this.H.getVideoData().lengthSeconds)};
g.k.QB=function(a){if(J8(this)){this.Ya.unsubscribe("remotePlayerChange",this.Sn,this);var b=Math.round(a.volume);a=!!a.muted;var c=b8(this.Ya);if(b!==c.volume||a!==c.muted)this.Ya.setVolume(b,a),this.I.start();this.Ya.subscribe("remotePlayerChange",this.Sn,this)}};
g.k.nL=function(){g.Rb(this.A)||OGa(this,this.A);this.B=!1};
g.k.iC=function(a,b){this.u.stop();2===b&&this.xD()};
g.k.Sn=function(){if(J8(this)){this.o.stop();var a=b8(this.Ya);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.jd=1;break;case 1082:case 1083:this.module.jd=0;break;default:this.module.jd=-1}switch(a.playerState){case 1081:case 1:this.Nc(new g.HI(8));this.wD();break;case 1085:case 3:this.Nc(new g.HI(9));break;case 1083:case 0:this.Nc(new g.HI(2));this.F.stop();this.Wb(this.H.getVideoData().lengthSeconds);break;case 1084:this.Nc(new g.HI(4));break;case 2:this.Nc(new g.HI(4));
this.Wb(X7(a));break;case -1:this.Nc(new g.HI(64));break;case -1E3:this.Nc(new g.HI(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=b8(this.Ya).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,OGa(this,a));a=b8(this.Ya);-1===a.volume||Math.round(this.H.getVolume())===a.volume&&this.H.isMuted()===a.muted||this.I.isActive()||this.YD()}else NGa(this)};
g.k.eC=function(){this.H.R("mdxpreviousnextchange")};
g.k.lr=function(){J8(this)||NGa(this)};
g.k.aC=function(a){isNaN(a)||this.H.R("mdxnowautoplaying",a)};
g.k.AB=function(){this.H.R("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J8(this)&&this.Ya.setAudioTrack(this.H.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===b8(this.Ya).playerState?L8(this,a):b&&this.Ya.seekTo(a)};
g.k.YD=function(){if(J8(this)){var a=b8(this.Ya);this.events.qb(this.M);a.muted?this.H.mute():this.H.unMute();this.H.setVolume(a.volume);this.M=this.events.K(this.H,"onVolumeChange",this.QB)}};
g.k.wD=function(){this.o.stop();if(!this.Ya.ga()){var a=b8(this.Ya);a.sb()&&this.Nc(new g.HI(8));this.Wb(X7(a));this.o.start()}};
g.k.xD=function(){this.u.stop();this.o.stop();var a=this.Ya.B.getReconnectTimeout();2==this.Ya.o&&!isNaN(a)&&this.u.start()};
g.k.Nc=function(a){this.u.stop();var b=this.C;if(!g.MI(b,a)){var c=g.W(a,2);c!==g.W(this.C,2)&&g.PU(this.H.app,c);this.C=a;QGa(this.module,b,a)}};g.t(M8,g.T);M8.prototype.Nb=function(){this.o.show()};
M8.prototype.Sa=function(){this.o.hide()};
M8.prototype.u=function(){g.XO("https://support.google.com/youtube/answer/7640706")};
M8.prototype.A=function(){e6("mdx-manual-pairing-popup-ok");this.Sa()};g.t(N8,g.T);N8.prototype.Nb=function(){this.o.show()};
N8.prototype.Sa=function(){this.o.hide()};
N8.prototype.u=function(){e6("mdx-privacy-popup-cancel");this.Sa()};
N8.prototype.A=function(){e6("mdx-privacy-popup-confirm");this.Sa()};g.t(O8,g.T);O8.prototype.u=function(a){PGa(this,a.state)};g.t(P8,g.kS);P8.prototype.B=function(){var a=this.H.getOption("remote","receivers");a&&1<a.length&&!this.H.getOption("remote","quickCast")?(this.Pi=g.Db(a,this.o,this),g.mS(this,g.Nc(a,this.o)),a=this.H.getOption("remote","currentReceiver"),this.Pb(this.o(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.o=function(a){return a.key};
P8.prototype.Tf=function(a){return"cast-selector-receiver"===a?"Cast...":this.Pi[a].name};
P8.prototype.td=function(a){g.kS.prototype.td.call(this,a);this.H.setOption("remote","currentReceiver",this.Pi[a]);this.Ha.Sa()};g.t(Q8,g.XN);g.k=Q8.prototype;
g.k.create=function(){var a=this.player.O(),b=g.lz(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.P(a.experiments,"mdx_load_cast_api_bootstrap_script")};HGa(b,a);this.subscriptions.push(g.gp("yt-remote-before-disconnect",this.sK,this));this.subscriptions.push(g.gp("yt-remote-connection-change",this.qM,this));this.subscriptions.push(g.gp("yt-remote-receiver-availability-change",this.gC,this));this.subscriptions.push(g.gp("yt-remote-auto-connect",this.oM,this));this.subscriptions.push(g.gp("yt-remote-receiver-resumed",
this.nM,this));this.subscriptions.push(g.gp("mdx-privacy-popup-confirm",this.NN,this));this.subscriptions.push(g.gp("mdx-privacy-popup-cancel",this.MN,this));this.subscriptions.push(g.gp("mdx-manual-pairing-popup-ok",this.nH,this));this.gC()};
g.k.load=function(){this.player.cancelPlayback();g.XN.prototype.load.call(this);this.og=new I8(this,this.player,this.Ya);var a=(a=MGa())?a.currentTime:0;var b=E8()?new a8(z8(),void 0):null;0==a&&b&&(a=X7(b8(b)));0!==a&&this.Wb(a);QGa(this,this.Tb,this.Tb);g.VU(this.player.app,6)};
g.k.unload=function(){this.player.R("mdxautoplaycanceled");this.ai=this.Qf;g.Ue(this.og,this.Ya);this.Ya=this.og=null;g.XN.prototype.unload.call(this);g.VU(this.player.app,5);R8(this)};
g.k.W=function(){g.hp(this.subscriptions);g.XN.prototype.W.call(this)};
g.k.Ig=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.og.MA.apply(this.og,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.jd};
g.k.mG=function(){return this.loaded?this.og.suggestion:null};
g.k.wg=function(){return this.Ya?b8(this.Ya).wg:!1};
g.k.hasNext=function(){return this.Ya?b8(this.Ya).hasNext:!1};
g.k.Wb=function(a,b){this.iA=a||0;this.player.R("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.iA};
g.k.getProgressState=function(){var a=b8(this.Ya),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.hd():!a.isAdPlaying()&&this.player.hd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+V7(a):a.B,isAtLiveHead:1>=(a.A?a.u+V7(a):a.u)-this.getCurrentTime(),loaded:a.M,seekableEnd:a.A?a.u+V7(a):a.u,seekableStart:0<a.C?a.C+
V7(a):a.C}};
g.k.nextVideo=function(){this.Ya&&this.Ya.nextVideo()};
g.k.tr=function(){this.Ya&&this.Ya.tr()};
g.k.sK=function(a){1===a&&(this.Hv=this.Ya?b8(this.Ya):null)};
g.k.qM=function(){var a=E8()?new a8(z8(),void 0):null;if(a){var b=this.ai;this.loaded&&this.unload();this.Ya=a;this.Hv=null;b.key!==this.Qf.key&&(this.ai=b,this.load())}else g.Te(this.Ya),this.Ya=null,this.loaded&&(this.unload(),(a=this.Hv)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,X7(a)));this.player.R("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.gC=function(){this.Pi=[this.Qf].concat(JGa());var a=A8()||this.Qf;S8(this,a);this.player.na("onMdxReceiversChange")};
g.k.oM=function(){var a=A8();S8(this,a)};
g.k.nM=function(){this.ai=A8()};
g.k.NN=function(){this.Tn=!0;R8(this);G8=!1;H8&&C8(H8,1);H8=null};
g.k.MN=function(){this.Tn=!1;R8(this);S8(this,this.Qf);this.ai=this.Qf;G8=!1;H8=null;this.player.playVideo()};
g.k.nH=function(){this.xq=!0;R8(this);g.xt("yt-remote-manual-pairing-warning-shown",!0,2592E3);G8=!1;H8&&C8(H8,1);H8=null};
g.k.dd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Pi;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?R7():S8(this,b)),this.loaded?this.ai:this.Qf;case "quickCast":return 2===this.Pi.length&&"cast-selector-receiver"===this.Pi[1].key?(b&&R7(),!0):!1}};
g.k.Bw=function(){this.Ya.Bw()};
g.k.eg=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.hO.remote=Q8;})(_yt_player);
