(function(g){var window=this;var Fpa=function(a,b){return g.Wb(a,b)},Q4=function(a,b,c){a.l.set(b,c)},R4=function(a){Q4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.A)()).toString(36));
return a},S4=function(a,b,c){g.La(c)||(c=[String(c)]);
g.Wm(a.l,b,c)},Gpa=function(a,b){var c=[];
g.$i(b,function(d){try{var e=g.Gn.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.Fn(e)&&c.push(d):c.push(d)},a);
return c},Hpa=function(a,b){var c=Gpa(a,b);
(0,g.z)(c,function(d){g.Gn.prototype.remove.call(this,d)},a)},T4=function(a){if(a.Zc){if(a.Zc.locationOverrideToken)return{locationOverrideToken:a.Zc.locationOverrideToken};
if(null!=a.Zc.latitudeE7&&null!=a.Zc.longitudeE7)return{latitudeE7:a.Zc.latitudeE7,longitudeE7:a.Zc.longitudeE7}}return null},Ipa=function(a,b){g.ab(a,b)||a.push(b)},U4=function(a){var b=0,c;
for(c in a)b++;return b},V4=function(a,b){var c=b instanceof g.xc?b:g.Cc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},W4=function(){},Jpa=function(a){try{return g.u.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Kpa=function(a){if(a.wd&&"function"==typeof a.wd)return a.wd();
if(g.Da(a))return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Sb(a)},Lpa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||g.Da(a))(0,g.z)(a,b,void 0);else{if(a.Wd&&"function"==typeof a.Wd)var c=a.Wd();else if(a.wd&&"function"==typeof a.wd)c=void 0;else if(g.Ma(a)||g.Da(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Tb(a);d=Kpa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Mpa=function(a,b,c,d){var e=new g.Km(null,void 0);
a&&g.Lm(e,a);b&&g.Mm(e,b);c&&g.Nm(e,c);d&&(e.i=d);return e},X4=function(a,b){g.Io[a]=!0;
var c=g.Go();c&&c.publish.apply(c,arguments);g.Io[a]=!1},Y4=function(a){try{var b=(0,g.Ux)(),c=(0,g.Tx)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Npa=function(){var a=(0,g.Tx)();
a&&Hpa(a,a.g.af(!0))},Z4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Hm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Opa(this,a.capabilities||""),Ppa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},Opa=function(a,b){a.capabilities.clear();
(0,g.Wd)(b.split(","),g.Ra(Fpa,Qpa)).forEach(function(c){a.capabilities.add(c)})},Ppa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},$4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},a5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},b5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Rpa=function(a){return new $4(a)},c5=function(a){return g.La(a)?(0,g.fe)(a,Rpa):[]},d5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},e5=function(a){return g.La(a)?"["+(0,g.fe)(a,d5).join(",")+"]":"null"},f5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Spa=function(a){return(0,g.fe)(a,function(b){return{key:b.id,
name:b.name}})},g5=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},h5=function(a,b){return g.Ya(a,function(c){return a5(c,b)})},i5=function(){var a=g.Wx("yt-remote-connected-devices")||[];
g.rb(a);return a},Tpa=function(a){if(g.bb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.fe)(a,function(d,e){return 0==e?d:d.substring(c.length)})},j5=function(a){g.Vx("yt-remote-connected-devices",a,86400)},l5=function(){if(k5)return k5;
var a=g.Wx("yt-remote-device-id");a||(a=f5(),g.Vx("yt-remote-device-id",a,31536E3));for(var b=i5(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return k5=d},m5=function(){var a=i5(),b=l5();
g.ab(a,b);g.aL()&&g.tb(a,b);a=Tpa(a);if(g.bb(a))try{g.vr("remote_sid")}catch(c){}else try{g.ur("remote_sid",a.join(","),-1)}catch(c){}},n5=function(){return g.Wx("yt-remote-session-browser-channel")},o5=function(){return g.Wx("yt-remote-local-screens")||[]},p5=function(){g.Vx("yt-remote-lounge-token-expiration",!0,86400)},Upa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.fe)(o5(),function(d){return d.loungeToken}),c=(0,g.fe)(a,function(d){return d.loungeToken});
(0,g.$g)(c,function(d){return!g.ab(b,d)})&&p5();
g.Vx("yt-remote-local-screens",a,31536E3)},Vpa=function(a,b){g.Vx("yt-remote-session-browser-channel",a);
g.Vx("yt-remote-session-screen-id",b);var c=i5(),d=l5();g.ab(c,d)||c.push(d);j5(c);m5()},q5=function(a){a||(Y4("yt-remote-session-screen-id"),Y4("yt-remote-session-video-id"));
m5();a=i5();g.eb(a,l5());j5(a)},s5=function(){if(!r5){var a=g.Qn();
a&&(r5=new g.An(a))}return r5?!!r5.get("yt-remote-use-staging-server"):!1},t5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},u5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},w5=function(a){a.length?v5(a.shift(),function(){w5(a)}):x5()},Wpa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},v5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},x5=function(){var a=u5();
a&&a(!1,"No cast extension found")},y5=function(){if(Xpa){var a=2,b=u5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;v5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",x5,c)}},Ypa=function(){y5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);w5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},z5=function(a,b,c){g.F.call(this);
this.w=null!=c?(0,g.x)(a,c):a;this.Sc=b;this.u=(0,g.x)(this.XB,this);this.g=!1;this.i=0;this.l=this.Aa=null;this.o=[]},A5=function(a){if(g.u.JSON)try{return g.u.JSON.parse(a)}catch(b){}return Jpa(a)},B5=function(){},C5=function(){},D5=function(){},F5=function(a){return(a=E5(a))?new ActiveXObject(a):new XMLHttpRequest},E5=function(a){if(!a.i&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.i=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.i},G5=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.w=d||1;this.o=45E3;this.ba=new g.cZ(this);this.i=new g.hl;this.i.setInterval(250)},I5=function(a,b,c){a.Kh=1;
a.Kf=R4(b.clone());a.fh=c;a.u=!0;H5(a,null)},J5=function(a,b,c,d,e){a.Kh=1;
a.Kf=R4(b.clone());a.fh=null;a.u=c;e&&(a.Sy=!1);H5(a,d)},H5=function(a,b){a.pi=(0,g.A)();
K5(a);a.rg=a.Kf.clone();S4(a.rg,"t",a.w);a.Ek=0;a.oc=a.g.Io(a.g.qk()?b:null);0<a.lp&&(a.hn=new g.kl((0,g.x)(a.Qz,a,a.oc),a.lp));a.ba.ea(a.oc,"readystatechange",a.RK);var c=a.Ng?g.bc(a.Ng):{};a.fh?(a.Nn="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.oc.send(a.rg,a.Nn,a.fh,c)):(a.Nn="GET",a.Sy&&!g.Ld&&(c.Connection="close"),a.oc.send(a.rg,a.Nn,null,c));a.g.me(1)},R5=function(a,b,c){for(var d=!0;!a.Cg&&a.Ek<c.length;){var e=Zpa(a,c);
if(e==L5){4==b&&(a.cg=4,M5(15),d=!1);break}else if(e==N5){a.cg=4;M5(16);d=!1;break}else O5(a,e)}4==b&&0==c.length&&(a.cg=1,M5(17),d=!1);a.ne=a.ne&&d;d||(P5(a),Q5(a))},Zpa=function(a,b){var c=a.Ek,d=b.indexOf("\n",c);
if(-1==d)return L5;c=Number(b.substring(c,d));if(isNaN(c))return N5;d+=1;if(d+c>b.length)return L5;var e=b.substr(d,c);a.Ek=d+c;return e},U5=function(a,b){a.pi=(0,g.A)();
K5(a);var c=b?window.location.hostname:"";a.rg=a.Kf.clone();Q4(a.rg,"DOMAIN",c);Q4(a.rg,"t",a.w);try{a.re=new ActiveXObject("htmlfile")}catch(n){P5(a);a.cg=7;M5(22);Q5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in S5)k=S5[l];else if(l in T5)k=S5[l]=T5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
S5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.qc("b/12014412"),d+"</body></html>");a.re.open();a.re.write(g.Mc(c));a.re.close();a.re.parentWindow.m=(0,g.x)(a.hK,a);a.re.parentWindow.d=(0,g.x)(a.Zx,a,!0);a.re.parentWindow.rpcClose=(0,g.x)(a.Zx,a,!1);c=a.re.createElement("DIV");a.re.parentWindow.document.body.appendChild(c);d=g.Bc(a.rg.toString());d=g.Zc(g.zc(d));d=g.Rc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.g.me(1)},K5=function(a){a.Ur=(0,g.A)()+a.o;
V5(a,a.o)},V5=function(a,b){if(null!=a.Gi)throw Error("WatchDog timer not null");
a.Gi=W5((0,g.x)(a.pK,a),b)},X5=function(a){a.Gi&&(g.u.clearTimeout(a.Gi),a.Gi=null)},Q5=function(a){a.g.Tu()||a.Cg||a.g.Ym(a)},P5=function(a){X5(a);
g.Di(a.hn);a.hn=null;a.i.stop();g.eZ(a.ba);if(a.oc){var b=a.oc;a.oc=null;b.abort();b.dispose()}a.re&&(a.re=null)},O5=function(a,b){try{a.g.Tx(a,b),a.g.me(4)}catch(c){}},Z5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Y5(a,b,function(k){k?c(!0):g.u.setTimeout(function(){Z5(a,b,c,d,f)},f)})}},Y5=function(a,b,c){var d=new Image;
d.onload=function(){try{$5(d),c(!0)}catch(e){}};
d.onerror=function(){try{$5(d),c(!1)}catch(e){}};
d.onabort=function(){try{$5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{$5(d),c(!1)}catch(e){}};
g.u.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
V4(d,a)},$5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},a6=function(a){this.g=a;
this.i=new B5},c6=function(a){var b=b6(a.g,a.Qi,"/mail/images/cleardot.gif");
R4(b);Z5(b.toString(),5E3,(0,g.x)(a.cB,a),3,2E3);a.me(1)},e6=function(a){var b=a.g.D;
if(null!=b)M5(5),b?(M5(11),d6(a.g,a,!1)):(M5(12),d6(a.g,a,!0));else if(a.Ad=new G5(a,void 0,void 0,void 0),a.Ad.Ng=a.jp,b=a.g,b=b6(b,b.qk()?a.pj:null,a.kp),M5(5),!g.Jd||g.md(10))S4(b,"TYPE","xmlhttp"),J5(a.Ad,b,!1,a.pj,!1);else{S4(b,"TYPE","html");var c=a.Ad;a=!!a.pj;c.Kh=3;c.Kf=R4(b.clone());U5(c,a)}},f6=function(a){g.xk.call(this);
this.headers=new g.Hm;this.M=a||null;this.l=!1;this.R=this.g=null;this.W=this.D="";this.w=0;this.o="";this.u=this.aa=this.C=this.P=!1;this.B=0;this.G=null;this.X="";this.I=this.S=!1},$pa=function(a){return g.Jd&&g.ld(9)&&g.Fa(a.timeout)&&g.Ca(a.ontimeout)},aqa=function(a){return"content-type"==a.toLowerCase()},i6=function(a,b){a.l=!1;
a.g&&(a.u=!0,a.g.abort(),a.u=!1);a.o=b;a.w=5;g6(a);h6(a)},g6=function(a){a.P||(a.P=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},l6=function(a){if(a.l&&"undefined"!=typeof g.iZ)if(a.R[1]&&4==j6(a)&&2==a.getStatus())k6(a,"Local request error detected and ignored");
else if(a.C&&4==j6(a))g.il(a.Vu,0,a);else if(a.dispatchEvent("readystatechange"),4==j6(a)){k6(a,"Request complete");a.l=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.uf(1,String(a.D));if(!f&&g.u.self&&g.u.self.location){var k=g.u.self.location.protocol;f=k.substr(0,k.length-1)}e=!bqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.w=6;try{var l=2<j6(a)?a.g.statusText:""}catch(m){l=""}a.o=l+" ["+a.getStatus()+"]";g6(a)}}finally{h6(a)}}},h6=function(a,b){if(a.g){m6(a);
var c=a.g,d=a.R[0]?g.Ha:null;a.g=null;a.R=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},m6=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.G&&(g.u.clearTimeout(a.G),a.G=null)},j6=function(a){return a.g?a.g.readyState:0},n6=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},k6=function(a,b){return b+" ["+a.W+" "+a.D+" "+a.getStatus()+"]"},o6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new B5;this.C=a||null;this.D=null!=b?b:null;this.w=c||!1},cqa=function(a,b){this.g=a;
this.map=b;this.context=null},p6=function(a){g.ak.call(this,"statevent",a)},q6=function(a,b){g.ak.call(this,"timingevent",a);
this.size=b},r6=function(a){g.ak.call(this,"serverreachability",a)},v6=function(a){s6(a);
if(3==a.g){var b=a.Vj++,c=a.Gl.clone();Q4(c,"SID",a.l);Q4(c,"RID",b);Q4(c,"TYPE","terminate");t6(a,c);b=new G5(a,a.l,b,void 0);b.Kh=2;b.Kf=R4(c.clone());V4(new Image,b.Kf.toString());b.pi=(0,g.A)();K5(b)}u6(a)},x6=function(a){a.wB(1,0);
a.Gl=b6(a,null,a.ip);w6(a)},s6=function(a){a.Qf&&(a.Qf.abort(),a.Qf=null);
a.Mb&&(a.Mb.cancel(),a.Mb=null);a.bf&&(g.u.clearTimeout(a.bf),a.bf=null);y6(a);a.td&&(a.td.cancel(),a.td=null);a.Xf&&(g.u.clearTimeout(a.Xf),a.Xf=null)},z6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new cqa(a.vG++,b));2!=a.g&&3!=a.g||w6(a)},w6=function(a){a.td||a.Xf||(a.Xf=W5((0,g.x)(a.Yx,a),0),a.Dh=0)},C6=function(a,b){if(1==a.g){if(!b){a.Vj=Math.floor(1E5*Math.random());
var c=a.Vj++,d=new G5(a,"",c,void 0);d.Ng=null;var e=A6(a),f=a.Gl.clone();Q4(f,"RID",c);Q4(f,"CVER","1");t6(a,f);I5(d,f,e);a.td=d;a.g=2}}else 3==a.g&&(b?B6(a,b):0==a.i.length||a.td||B6(a))},B6=function(a,b){if(b)if(6<a.Dg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Vj-1;var d=A6(a)}else c=b.B,d=b.fh;else c=a.Vj++,d=A6(a);var e=a.Gl.clone();Q4(e,"SID",a.l);Q4(e,"RID",c);Q4(e,"AID",a.Wh);t6(a,e);c=new G5(a,a.l,c,a.Dh+1);c.Ng=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.td=c;I5(c,e,d)},t6=function(a,b){if(a.Pc){var c=a.Pc.vu();
c&&g.Mb(c,function(d,e){Q4(b,e,d)})}},A6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Dg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Dg?e:f-d;try{g.Mb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},D6=function(a){a.Mb||a.bf||(a.B=1,a.bf=W5((0,g.x)(a.Xx,a),0),a.xh=0)},F6=function(a){if(a.Mb||a.bf||3<=a.xh)return!1;
a.B++;a.bf=W5((0,g.x)(a.Xx,a),E6(a,a.xh));a.xh++;return!0},d6=function(a,b,c){a.Ln=c;
a.we=b.qf;a.w||x6(a)},y6=function(a){null!=a.Gg&&(g.u.clearTimeout(a.Gg),a.Gg=null)},E6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},H6=function(a,b){if(2==b||9==b){var c=null;
a.Pc&&(c=null);var d=(0,g.x)(a.xL,a);c||(c=new g.Km("//www.google.com/images/cleardot.gif"),R4(c));Y5(c.toString(),1E4,d)}else M5(2);G6(a,b)},G6=function(a,b){a.g=0;
a.Pc&&a.Pc.Ht(b);u6(a);s6(a)},u6=function(a){a.g=0;
a.we=-1;if(a.Pc)if(0==a.o.length&&0==a.i.length)a.Pc.Bo();else{g.ib(a.o);var b=g.ib(a.i);a.o.length=0;a.i.length=0;a.Pc.Bo(b)}},b6=function(a,b,c){var d=g.Sm(c);
if(""!=d.g)b&&g.Mm(d,b+"."+d.g),g.Nm(d,d.u);else{var e=window.location;d=Mpa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.cj&&g.Mb(a.cj,function(f,k){Q4(d,k,f)});
Q4(d,"VER",a.Dg);t6(a,d);return d},W5=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.u.setTimeout(function(){a()},b)},M5=function(a){I6.dispatchEvent(new p6(I6,a))},J6=function(){},K6=function(){this.g=[];
this.i=[]},dqa=function(a,b){this.action=a;
this.params=b||{}},L6=function(a,b){g.F.call(this);
this.g=new g.J(this.YJ,0,this);g.H(this,this.g);this.Sc=5E3;this.i=0;if(g.Na(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},M6=function(a,b,c){this.G=a;
this.w=b;this.l=new g.zn;this.i=new L6(this.bL,this);this.g=null;this.bb=!1;this.u=null;this.D="";this.C=this.o=0;this.B=[];this.I=c||!1},eqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Ln,sessionId:a.g.l,arrayId:a.g.Wh}},N6=function(a,b){a.C=b||0;
a.i.stop();a.g&&(3==a.g.g&&C6(a.g),v6(a.g));a.C=0},O6=function(a){return!!a.g&&3==a.g.g},fqa=function(a,b){(a.w.loungeIdToken=b)||a.i.stop()},P6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.uf(4,a))||"";b&&(this.port=":"+b);this.domain=g.vf(a)||"";a=g.Kb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Jb(a,"10.0")&&(this.i=!1))},Q6=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Ef(c+b,{})},R6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.o,d,!0),onError:g.Ra(a.l,e),Nd:g.Ra(a.u,e)};c&&(a.rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Bp(b,a)},gqa=function(){var a=S6;
T6();U6.push(a);V6(U6)},W6=function(a,b){T6();
var c=U6,d=hqa(a,String(b));g.bb(c)?iqa(d):(V6(c),(0,g.z)(c,function(e){e(d)}))},T6=function(){U6||(U6=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",U6,void 0))},iqa=function(a){var b=(X6+1)%50;
X6=b;Y6[b]=a;Z6||(Z6=49==b)},V6=function(a){var b=Y6;
if(b[0]){var c=X6,d=Z6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
Y6=Array(50);X6=-1;Z6=!1}},hqa=function(a,b){var c=((0,g.A)()-jqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},$6=function(a){g.O.call(this);
this.B=a;this.g=[]},a7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},kqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Wd)(a.g,function(f){return!!g5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=a7(a,b[d])||c;return c},lqa=function(a,b){var c=a.g.length;
a.g=(0,g.Wd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},b7=function(a,b,c,d){g.O.call(this);
this.w=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Aa=NaN},d7=function(a){$6.call(this,"LocalScreenService");
this.l=a;this.i=NaN;c7(this);this.info("Initializing with "+e5(this.g))},e7=function(a){if(a.g.length){var b=(0,g.fe)(a.g,function(d){return d.id}),c=Q6(a.l,"/pairing/get_lounge_token_batch");
R6(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.hC,a),(0,g.x)(a.gC,a))}},c7=function(a){var b=c5(o5());
b=(0,g.Wd)(b,function(c){return!c.uuid});
return kqa(a,b)},f7=function(a,b){Upa((0,g.fe)(a.g,b5));
b&&p5()},h7=function(a,b){g.O.call(this);
this.w=b;var c=g.Wx("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.w(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;g7("Initialized with "+g.Aj(this.g))},i7=function(a,b,c){var d=Q6(a.u,"/pairing/get_screen_availability");
R6(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},j7=function(a,b){a:if(U4(b)!=U4(a.g))var c=!1;
else{c=g.Tb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(g7("Updated online screens: "+g.Aj(a.g)),a.g=b,a.N("screenChange"));mqa(a)},k7=function(a){isNaN(a.l)||g.Fo(a.l);
a.l=g.Do((0,g.x)(a.ir,a),0<a.o&&a.o<(0,g.A)()?2E4:1E4)},g7=function(a){W6("OnlineScreenService",a)},l7=function(a){var b={};
(0,g.z)(a.w(),function(c){c.token?b[c.token]=c.id:this.Fb("Requesting availability of screen w/o lounge token.")});
return b},mqa=function(a){a=g.Tb(g.Nb(a.g,function(b){return b}));
g.rb(a);a.length?g.Vx("yt-remote-online-screen-ids",a.join(","),60):Y4("yt-remote-online-screen-ids")},m7=function(a){$6.call(this,"ScreenService");
this.w=a;this.i=this.l=null;this.o=[];this.u={};nqa(this)},o7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Kd();if(k=(c?h5(k,c):null)||h5(k,b)){k.uuid=b;var l=n7(a,k);i7(a.i,l,function(m){e(m?l:null)})}else c?oqa(a,c,(0,g.x)(function(m){var n=n7(this,new $4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));i7(this.i,n,function(q){e(q?n:null)})},a),f):e(null)},p7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},oqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Bp(Q6(a.w,"/pairing/get_lounge_token_batch"),e)},q7=function(a){a.g=a.l.Kd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+e5(a.g))},nqa=function(a){r7(a);
a.l=new d7(a.w);a.l.subscribe("screenChange",(0,g.x)(a.oC,a));q7(a);a.o=c5(g.Wx("yt-remote-automatic-screen-cache")||[]);r7(a);a.info("Initializing automatic screens: "+e5(a.o));a.i=new h7(a.w,(0,g.x)(a.Kd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.N("onlineScreenChange")},a))},n7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=h5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Vx("yt-remote-automatic-screen-cache",(0,g.fe)(a.o,b5)));r7(a);a.u[b.uuid]=b.id;g.Vx("yt-remote-device-id-map",a.u,31536E3);return b},r7=function(a){a.u=g.Wx("yt-remote-device-id-map")||{}},s7=function(a,b,c){g.O.call(this);
this.R=c;this.D=a;this.i=b;this.l=null},t7=function(a,b){W6(a.R,b)},v7=function(a,b){s7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.w=(0,g.x)(this.dM,this);this.u=(0,g.x)(this.AK,this);this.o=g.Do((0,g.x)(function(){u7(this,null)},this),12E4)},pqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Aj(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.x)(function(){t7(this,"Failed to send message: getMdxSessionStatus.")},a)):t7(a,"Sending yt message without session: "+g.Aj(b))},u7=function(a,b){g.Fo(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.an,a),d=(0,g.x)(a.Md,a);a.Ou(b,c,d,5)}}else a.Md(Error("Waiting for session status timed out."))},w7=function(a,b,c){s7.call(this,a,b,"DialSession");
this.o=this.C=null;this.G="";this.M=c;this.u=null;this.B=g.Ha;this.w=NaN;this.I=(0,g.x)(this.gM,this);this.g=g.Ha},x7=function(a){a.g=a.D.Wz(a.G,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ha;
this.an(b)},a),(0,g.x)(function(b){this.g=g.Ha;
this.Md(b)},a))},y7=function(a){var b={};
b.pairingCode=a.G;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}s5()&&(b.env_useStageMdx=1);return g.Cf(b)},z7=function(a,b){s7.call(this,a,b,"ManualSession");
this.g=g.Do((0,g.x)(this.Xh,this,null),150)},A7=function(a,b,c,d){g.O.call(this);
this.i=a;this.B=b||"233637DE";this.w=c||"cl";this.C=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.hJ,this)},B7=function(a,b){return b?g.Ya(a.l,function(c){return a5(b,c.label)},a):null},C7=function(a){W6("Controller",a)},S6=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},D7=function(a){return a.u||!!a.l.length||!!a.g},E7=function(a,b,c){b!=a.g&&(g.Di(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.Wx,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.Xh(null)):a.N("yt-remote-cast2-session-change",null))},F7=function(a){var b=a.i.Vz(),c=a.g&&a.g.i;
a=(0,g.fe)(b,function(d){c&&a5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=B7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},tqa=function(a,b,c,d,e,f,k){qqa()?rqa(b,e,f,k)&&(H7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?I7(a,c):(window.__onGCastApiAvailable=function(l,m){l?I7(a,c):(J7("Failed to load cast API: "+m),K7(!1),H7(!1),Y4("yt-remote-cast-available"),Y4("yt-remote-cast-receiver"),L7(),c(!1))},d?g.Qo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Ypa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?x5():(y5(),w5(sqa.map(Wpa))))):G7("Cannot initialize because not running Chrome")},L7=function(){G7("dispose");
var a=M7();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);N7(!1);g.Lo(O7);O7.length=0},P7=function(){return!!g.Wx("yt-remote-cast-installed")},Q7=function(){var a=g.Wx("yt-remote-cast-receiver");
return a?a.friendlyName:null},R7=function(){G7("clearCurrentReceiver");
Y4("yt-remote-cast-receiver")},S7=function(){return P7()?M7()?M7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},U7=function(){P7()?M7()?T7()?(G7("Requesting cast selector."),M7().requestSession()):(G7("Wait for cast API to be ready to request the session."),O7.push(g.Ko("yt-remote-cast2-api-ready",U7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},V7=function(a,
b){T7()?M7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},qqa=function(){var a=0<=g.Kb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Ds||a},uqa=function(a,b){M7().init(a,b)},rqa=function(a,b,c,d){var e=!1;
M7()||(a=new A7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Vx("yt-remote-cast-available",f);X4("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){G7("onReceiverSelected: "+f.friendlyName);
g.Vx("yt-remote-cast-receiver",f);X4("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){G7("onReceiverResumed: "+f.friendlyName);
g.Vx("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){G7("onSessionChange: "+d5(f));
f||Y4("yt-remote-cast-receiver");X4("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
G7("cloudview.createSingleton_: "+e);return e},M7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},I7=function(a,b){K7(!0);
H7(!1);uqa(a,function(c){c?(N7(!0),g.No("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),Y4("yt-remote-cast-available"),Y4("yt-remote-cast-receiver"),L7());b(c)})},G7=function(a){W6("cloudview",a)},J7=function(a){W6("cloudview",a)},K7=function(a){G7("setCastInstalled_ "+a);
g.Vx("yt-remote-cast-installed",a)},T7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},N7=function(a){G7("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},H7=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},W7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.w=this.B=0;this.g=null;this.hasNext=this.xe=!1;this.D=this.C=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},X7=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.xe=!1;a.hasNext=!1;a.B=0;a.w=(0,g.A)();a.o=0;a.i=0;a.C=0;a.D=0;a.l=NaN;a.u=!1},Y7=function(a){return 1==a.playerState?((0,g.A)()-a.w)/1E3:0},Z7=function(a,b){a.B=b;
a.w=(0,g.A)()},$7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.A)()-a.w)/1E3+a.B;
case -1E3:return 0}return a.B},a8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&X7(a)},b8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.xe;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.w;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.C;b.loadedTime=a.D;b.liveIngestionTime=a.l;return b},e8=function(a,b){g.O.call(this);
this.g=0;this.o=a;this.w=[];this.u=new K6;this.l=this.i=null;this.D=(0,g.x)(this.dH,this);this.B=(0,g.x)(this.Yj,this);this.C=(0,g.x)(this.cH,this);this.G=(0,g.x)(this.pH,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Xr,this),c8(this))):c=3;0!=c&&(b?this.Xr(c):g.Do((0,g.x)(function(){this.Xr(c)},this),0));
var d=S7();d&&d8(this,d);this.subscribe("yt-remote-cast2-session-change",this.G)},f8=function(a){return new W7(a.o.getPlayerContextData())},c8=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.w.push(this.o.subscribe(b,g.Ra(this.eJ,b),this))},a)},g8=function(a){(0,g.z)(a.w,function(b){this.o.unsubscribeByKey(b)},a);
a.w.length=0},h8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},j8=function(a,b,c){var d=f8(a);
Z7(d,c);-1E3!=d.playerState&&(d.playerState=b);i8(a,d)},k8=function(a,b,c){a.o.sendMessage(b,c)},i8=function(a,b){g8(a);
a.o.setPlayerContextData(b8(b));c8(a)},d8=function(a,b){a.l&&(a.l.removeUpdateListener(a.D),a.l.removeMediaListener(a.B),a.Yj(null));
a.l=b;a.l&&(W6("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.D),a.l.addMediaListener(a.B),a.l.media.length&&a.Yj(a.l.media[0]))},l8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=f8(a);b.contentId!=d.videoId&&W6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;Z7(d,a.i.getEstimatedTime());i8(a,d)}else W6("CP","No cast media video. Ignoring state update.")},m8=function(a,b,c){return(0,g.x)(function(d){this.Fb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Fb("Retrying "+b+" using MDx browser channel."),k8(this,b,c))},a)},n8=function(a,b,c){g.O.call(this);
this.u=NaN;this.I=!1;this.C=this.B=this.D=this.G=NaN;this.R=[];this.o=this.w=this.l=this.Oa=this.g=null;this.P=a;this.R.push(g.$q(window,"beforeunload",(0,g.x)(this.aC,this)));this.i=[];this.Oa=new W7;this.M=b.id;this.g=vqa(this,c);this.g.subscribe("handlerOpened",this.hH,this);this.g.subscribe("handlerClosed",this.eH,this);this.g.subscribe("handlerError",this.fH,this);this.g.subscribe("handlerMessage",this.gH,this);fqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.aL()&&g.Vx("yt-remote-session-video-id",d)},this)},o8=function(a){W6("conn",a)},vqa=function(a,b){return new M6(Q6(a.P,"/bc"),b)},p8=function(a,b){a.N("proxyStateChange",b)},wqa=function(a){a.u=g.Do((0,g.x)(function(){o8("Connecting timeout");
this.Bh(1)},a),2E4)},q8=function(a){g.Fo(a.u);
a.u=NaN},r8=function(a){g.Fo(a.G);
a.G=NaN},xqa=function(a){s8(a);
a.D=g.Do((0,g.x)(function(){t8(this,"getNowPlaying")},a),2E4)},s8=function(a){g.Fo(a.D);
a.D=NaN},v8=function(a,b){b&&(q8(a),r8(a));
b==(O6(a.g)&&isNaN(a.u))?b&&(p8(a,1),t8(a,"getSubtitlesTrack")):b?(a.Mu()&&a.Oa.reset(),p8(a,1),t8(a,"getNowPlaying"),u8(a)):a.Bh(1)},yqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Zb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.N("remotePlayerChange"))},w8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;a8(a.Oa,c,d);a.N("remoteQueueChange")},zqa=function(a,b){b.params=b.params||{};
w8(a,b);x8(a,b);a.N("autoplayDismissed")},x8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
Z7(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.D=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.C=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?xqa(a):s8(a);a.N("remotePlayerChange")},Aqa=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);Z7(a.Oa,isNaN(c)?0:c);a.N("remotePlayerChange")}},Bqa=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.N("remotePlayerChange")},Cqa=function(a,b){a.w=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},Dqa=function(a,b){var c="true"==b.params.hasNext;
a.Oa.xe="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.N("previousNextChange")},u8=function(a){g.Fo(a.C);
a.C=g.Do((0,g.x)(a.Bh,a,1),864E5)},t8=function(a,b,c){c?o8("Sending: action="+b+", params="+g.Aj(c)):o8("Sending: action="+b);
a.g.sendMessage(b,c)},y8=function(a){$6.call(this,"ScreenServiceProxy");
this.Rc=a;this.i=[];this.i.push(this.Rc.$_s("screenChange",(0,g.x)(this.bM,this)));this.i.push(this.Rc.$_s("onlineScreenChange",(0,g.x)(this.HI,this)))},Iqa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.vo("MDX_CONFIG")||b;Npa();m5();z8||(z8=new P6(b?b.loungeApiHost:void 0),s5()&&(z8.g="/api/loungedev"));A8||(A8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",A8,void 0));Eqa();var c=B8();if(!c){var d=new m7(z8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=B8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);tqa(a,d,function(m){m?C8()&&V7(C8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){X4("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),D8("Initializing: "+g.Aj(b)),E8.push(g.Ko("yt-remote-cast2-availability-change",function(){X4("yt-remote-receiver-availability-change")})),E8.push(g.Ko("yt-remote-cast2-receiver-selected",function(){F8(null);
X4("yt-remote-auto-connect","cast-selector-receiver")})),E8.push(g.Ko("yt-remote-cast2-receiver-resumed",function(){X4("yt-remote-receiver-resumed","cast-selector-receiver")})),E8.push(g.Ko("yt-remote-cast2-session-change",Fqa)),E8.push(g.Ko("yt-remote-connection-change",function(m){m?V7(C8(),"YouTube TV"):G8()||(V7(null,null),R7())})),a=H8(),b.isAuto&&(a.id+="#dial"),g.sp("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),D8(" -- with channel params: "+
g.Aj(a)),Gqa(a),c.start(),C8()||Hqa())},Jqa=function(){var a=I8();
P7()&&g.Wx("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},I8=function(){var a=B8().Rc.$_gos();
var b=J8();b&&K8()&&(g5(a,b)||a.push(b));return Spa(a)},L8=function(){var a=Kqa();
!a&&P7()&&Q7()&&(a={key:"cast-selector-receiver",name:Q7()});return a},Kqa=function(){var a=I8(),b=J8();
b||(b=G8());return g.Ya(a,function(c){return b&&a5(b,c.key)?!0:!1})},J8=function(){var a=C8();
if(!a)return null;var b=B8().Kd();return h5(b,a)},Fqa=function(a){D8("remote.onCastSessionChange_: "+d5(a));
if(a){var b=J8();b&&b.id==a.id?V7(b.id,"YouTube TV"):(b&&M8(),N8(a,1))}else K8()&&M8()},M8=function(){T7()?M7().stopSession():J7("stopSession called before API ready.");
var a=K8();a&&(a.disconnect(1),O8(null))},P8=function(){var a=K8();
return!!a&&3!=a.getProxyState()},D8=function(a){W6("remote",a)},B8=function(){if(!Q8){var a=g.w("yt.mdx.remote.screenService_");
Q8=a?new y8(a):null}return Q8},C8=function(){return g.w("yt.mdx.remote.currentScreenId_")},R8=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},S8=function(){return g.w("yt.mdx.remote.connectData_")},F8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},K8=function(){return g.w("yt.mdx.remote.connection_")},O8=function(a){var b=K8();
F8(null);a||R8("");g.Ga("yt.mdx.remote.connection_",a,void 0);A8&&((0,g.z)(A8,function(c){c(a)}),A8.length=0);
b&&!a?X4("yt-remote-connection-change",!1):!b&&a&&X4("yt-remote-connection-change",!0)},G8=function(){var a=g.aL();
if(!a)return null;var b=B8().Kd();return h5(b,a)},N8=function(a,b){J8()&&J8();
if(T8)U8=a;else{R8(a.id);var c=new n8(z8,a,H8());c.connect(b,S8());c.subscribe("beforeDisconnect",function(d){X4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){K8()&&O8(null)});
O8(c)}},Hqa=function(){var a=G8();
a?(D8("Resume connection to: "+d5(a)),N8(a,0)):(q5(),R7(),D8("Skipping connecting because no session screen found."))},Eqa=function(){var a=H8();
if(g.Zb(a)){a=l5();var b=g.Wx("yt-remote-session-name")||"",c=g.Wx("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},H8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Gqa=function(a){a?(g.Vx("yt-remote-session-app",a.app),g.Vx("yt-remote-session-name",a.name)):(Y4("yt-remote-session-app"),Y4("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},V8=function(a,b,c){g.F.call(this);
this.u=a;this.i=b;this.l=new g.Ks(this);g.H(this,this.l);this.l.J(b,"onCaptionsTrackListChanged",this.cI);this.l.J(b,"captionschanged",this.bH);this.l.J(b,"captionssettingschanged",this.iz);this.l.J(b,"videoplayerreset",this.bn);this.l.J(b,"mdxautoplaycancel",this.bB);this.P=this.l.J(b,"onVolumeChange",this.Ex);this.C=!1;this.g=c;c.subscribe("proxyStateChange",this.Sx,this);c.subscribe("remotePlayerChange",this.ak,this);c.subscribe("remoteQueueChange",this.bn,this);c.subscribe("autoplayUpNext",this.tx,
this);c.subscribe("previousNextChange",this.Px,this);c.subscribe("nowAutoplaying",this.Lx,this);c.subscribe("autoplayDismissed",this.sx,this);this.suggestion=null;this.D=new g.vt(64);this.o=new g.J(this.gz,500,this);g.H(this,this.o);this.w=new g.J(this.hz,1E3,this);g.H(this,this.w);this.I=new z5(this.GL,0,this);g.H(this,this.I);this.B={};this.R=new g.J(this.Iz,1E3,this);g.H(this,this.R);this.G=new g.kl(this.yE,1E3,this);g.H(this,this.G);this.M=g.Ha;this.iz();this.bn();this.ak()},W8=function(a,b){var c=
a.u,d=a.i.getVideoData().lengthSeconds;
c.R=b||0;c.player.N("progresssync",b,d)},Y8=function(a){W8(a,0);
a.o.stop();X8(a,new g.vt(64))},$8=function(a,b){if(Z8(a)&&!a.C){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.Xy(a.i.getVideoData(1).videoId,c);a.B=f8(a.g).g}},a9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Qa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.ze,T4(c));X8(a,new g.vt(1))},b9=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{PP:1});
c&&c.length?(a.i.setOption("captions","track",b),a.C=!1):(a.i.loadModule("captions"),a.C=!0)}else a.i.setOption("captions","track",{})},Z8=function(a){return f8(a.g).videoId==a.i.getVideoData(1).videoId},X8=function(a,b){a.w.stop();
var c=a.D;if(!g.Ct(c,b)){var d=g.R(b,2);d!=g.R(a.D,2)&&g.VR(a.i.app,d);a.D=b;c9(a.u,c,b)}},d9=function(){g.T.call(this,{A:"div",
F:"ytp-mdx-popup-dialog",K:{role:"dialog"},H:[{A:"div",F:"ytp-mdx-popup-dialog-inner-content",H:[{A:"div",F:"ytp-mdx-popup-title",T:"You're signed out"},{A:"div",F:"ytp-mdx-popup-description",T:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{A:"div",F:"ytp-mdx-privacy-popup-buttons",H:[{A:"button",U:["ytp-button","ytp-mdx-privacy-popup-cancel"],T:"Cancel"},{A:"button",U:["ytp-button","ytp-mdx-privacy-popup-confirm"],
T:"Confirm"}]}]}]});this.l=new g.gL(this,250);g.H(this,this.l);this.B=this.i["ytp-mdx-privacy-popup-cancel"];this.J(this.B,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.J(this.u,"click",this.w)},f9=function(a){g.T.call(this,{A:"div",
F:"ytp-remote",H:[{A:"div",F:"ytp-remote-display-status",H:[{A:"div",F:"ytp-remote-display-status-icon",H:[g.iL()]},{A:"div",F:"ytp-remote-display-status-text",T:"{{statustext}}"}]}]});this.l=new g.gL(this,250);g.H(this,this.l);this.o=a;this.J(a,"presentingplayerstatechange",this.u);e9(this,g.dK(a))},e9=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.R(b,128)?g.NL("Error on $RECEIVER_NAME",c):g.Dt(b)||g.R(b,4)?g.NL("Playing on $RECEIVER_NAME",c):g.NL("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},g9=function(a,b){g.JN.call(this,"Play on",0,a,b);
this.l=a;this.B={};this.J(a,"onMdxReceiversChange",this.I);this.J(a,"presentingplayerstatechange",this.I);this.I()},h9=function(a){g.SO.call(this,a);
this.i={key:f5(),name:"This computer"};this.u=null;this.o=[];this.M=this.g=null;this.G=[this.i];this.l=this.i;this.B=new g.vt(64);this.R=0;this.D=-1;this.w=null;if(!g.$y(this.player.L())){a=this.player;var b=g.LC(a);b&&(b=b.Jm())&&(b=new g9(a,b),g.H(this,b));b=new f9(a);g.H(this,b);g.vK(a,b.element,4);this.w=new d9;g.H(this,this.w);g.vK(a,this.w.element,4);this.I=!!G8()}this.C=null},i9=function(a){a.C&&(a.player.removeEventListener("presentingplayerstatechange",a.C),a.C=null)},c9=function(a,b,c){a.B=
c;
a.player.N("presentingplayerstatechange",new g.bD(c,b))},j9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)M8();
else{var c;(c=!g.P(a.player.L().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.vo("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.vo("SESSION_INDEX")&&!g.vo("LOGGED_IN")))||a.I||!a.w);if(c?0:"WEB"==a.player.L().deviceParams.c||"WEB_EMBEDDED_PLAYER"==a.player.L().deviceParams.c)g.Dt(g.dK(a.player))?a.player.pauseVideo():(a.C=(0,g.x)(a.FK,a),a.player.addEventListener("presentingplayerstatechange",a.C)),a.w&&a.w.l.show(),K8()||(T8=!0);a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ra(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.ze,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=T4(c))&&(d.locationInfo=c);c=d}else c=null;D8("Connecting to: "+g.Aj(b));"cast-selector-receiver"==b.key?(F8(c||null),T7()?M7().setLaunchParams(c||null):J7("setLaunchParams called before ready.")):
!c&&P8()&&C8()==b.key?X4("yt-remote-connection-change",!0):(M8(),F8(c||null),c=B8().Kd(),(c=h5(c,b.key))&&N8(c,1))}},T5={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},S5={"'":"\\'"},Lqa={},Qpa={EM:"atp",bP:"ska",QO:"que",rO:"mus",aP:"sus",FN:"dsp",XO:"seq"};
Z4.prototype.Rf=function(){var a=new Z4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var r5,k5="",Xpa=t5("loadCastFramework")||t5("loadCastApplicationFramework"),sqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Ta(z5,g.F);g.h=z5.prototype;g.h.WB=function(a){this.o=arguments;this.g=!1;this.Aa?this.l=(0,g.A)()+this.Sc:this.Aa=g.il(this.u,this.Sc)};
g.h.stop=function(){this.Aa&&(g.u.clearTimeout(this.Aa),this.Aa=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.w.apply(null,this.o)))};
g.h.V=function(){this.stop();z5.xb.V.call(this)};
g.h.XB=function(){this.l?(this.Aa=g.il(this.u,this.l-(0,g.A)()),this.l=null):(this.Aa=null,this.i?this.g=!0:(this.g=!1,this.w.apply(null,this.o)))};B5.prototype.stringify=function(a){return g.u.JSON.stringify(a,void 0)};
B5.prototype.parse=function(a){return g.u.JSON.parse(a,void 0)};C5.prototype.g=null;C5.prototype.getOptions=function(){var a;(a=this.g)||(a={},E5(this)&&(a[0]=!0,a[1]=!0),a=this.g=a);return a};var k9;g.Ta(D5,C5);k9=new D5;g.h=G5.prototype;g.h.Ng=null;g.h.ne=!1;g.h.Gi=null;g.h.Ur=null;g.h.pi=null;g.h.Kh=null;g.h.Kf=null;g.h.rg=null;g.h.fh=null;g.h.oc=null;g.h.Ek=0;g.h.re=null;g.h.Nn=null;g.h.cg=null;g.h.qj=-1;g.h.Sy=!0;g.h.Cg=!1;g.h.lp=0;g.h.hn=null;var N5={},L5={};g.h=G5.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.RK=function(a){a=a.target;var b=this.hn;b&&3==j6(a)?b.Tl():this.Qz(a)};
g.h.Qz=function(a){try{if(a==this.oc)a:{var b=j6(this.oc),c=this.oc.w,d=this.oc.getStatus();if(g.Jd&&!g.md(10)||g.Ld&&!g.ld("420+")){if(4>b)break a}else if(3>b||3==b&&!g.ag&&!n6(this.oc))break a;this.Cg||4!=b||7==c||(8==c||0>=d?this.g.me(3):this.g.me(2));X5(this);var e=this.oc.getStatus();this.qj=e;var f=n6(this.oc);(this.ne=200==e)?(4==b&&P5(this),this.u?(R5(this,b,f),g.ag&&this.ne&&3==b&&(this.ba.ea(this.i,"tick",this.LK),this.i.start())):O5(this,f),this.ne&&!this.Cg&&(4==b?this.g.Ym(this):(this.ne=
!1,K5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.cg=3,M5(13)):(this.cg=0,M5(14)),P5(this),Q5(this))}}catch(k){this.oc&&n6(this.oc)}finally{}};
g.h.LK=function(){var a=j6(this.oc),b=n6(this.oc);this.Ek<b.length&&(X5(this),R5(this,a,b),this.ne&&4!=a&&K5(this))};
g.h.hK=function(a){W5((0,g.x)(this.gK,this,a),0)};
g.h.gK=function(a){this.Cg||(X5(this),O5(this,a),K5(this))};
g.h.Zx=function(a){W5((0,g.x)(this.fK,this,a),0)};
g.h.fK=function(a){this.Cg||(P5(this),this.ne=a,this.g.Ym(this),this.g.me(4))};
g.h.cancel=function(){this.Cg=!0;P5(this)};
g.h.pK=function(){this.Gi=null;var a=(0,g.A)();0<=a-this.Ur?(2!=this.Kh&&this.g.me(3),P5(this),this.cg=2,M5(18),Q5(this)):V5(this,this.Ur-a)};
g.h.getLastError=function(){return this.cg};g.h=a6.prototype;g.h.jp=null;g.h.Ad=null;g.h.jn=!1;g.h.Uu=null;g.h.El=null;g.h.Np=null;g.h.kp=null;g.h.Zd=null;g.h.qf=-1;g.h.pj=null;g.h.Qi=null;g.h.connect=function(a){this.kp=a;a=b6(this.g,null,this.kp);M5(3);this.Uu=(0,g.A)();var b=this.g.C;null!=b?(this.pj=b[0],(this.Qi=b[1])?(this.Zd=1,c6(this)):(this.Zd=2,e6(this))):(S4(a,"MODE","init"),this.Ad=new G5(this,void 0,void 0,void 0),this.Ad.Ng=this.jp,J5(this.Ad,a,!1,null,!0),this.Zd=0)};
g.h.cB=function(a){if(a)this.Zd=2,e6(this);else{M5(4);var b=this.g;b.we=b.Qf.qf;H6(b,9)}a&&this.me(2)};
g.h.Io=function(a){return this.g.Io(a)};
g.h.abort=function(){this.Ad&&(this.Ad.cancel(),this.Ad=null);this.qf=-1};
g.h.Tu=function(){return!1};
g.h.Tx=function(a,b){this.qf=a.qj;if(0==this.Zd)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.we=this.qf;H6(c,2);return}this.pj=c[0];this.Qi=c[1]}else c=this.g,c.we=this.qf,H6(c,2);else if(2==this.Zd)if(this.jn)M5(7),this.Np=(0,g.A)();else if("11111"==b){if(M5(6),this.jn=!0,this.El=(0,g.A)(),c=this.El-this.Uu,!g.Jd||g.md(10)||500>c)this.qf=200,this.Ad.cancel(),M5(12),d6(this.g,this,!0)}else M5(8),this.El=this.Np=(0,g.A)(),this.jn=!1};
g.h.Ym=function(){this.qf=this.Ad.qj;if(this.Ad.ne)0==this.Zd?this.Qi?(this.Zd=1,c6(this)):(this.Zd=2,e6(this)):2==this.Zd&&((!g.Jd||g.md(10)?!this.jn:200>this.Np-this.El)?(M5(11),d6(this.g,this,!1)):(M5(12),d6(this.g,this,!0)));else{0==this.Zd?M5(9):2==this.Zd&&M5(10);var a=this.g;this.Ad.getLastError();a.we=this.qf;H6(a,2)}};
g.h.qk=function(){return this.g.qk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.me=function(a){this.g.me(a)};g.Ta(f6,g.xk);var bqa=/^https?$/i,Mqa=["POST","PUT"];g.h=f6.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.o="";this.w=0;this.W=b;this.P=!1;this.l=!0;this.g=this.M?F5(this.M):F5(k9);this.R=this.M?this.M.getOptions():k9.getOptions();this.g.onreadystatechange=(0,g.x)(this.Vu,this);try{W4(k6(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){W4(k6(this,"Error opening Xhr: "+f.message));i6(this,f);return}a=c||"";
var e=this.headers.clone();d&&Lpa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Wd(),aqa);c=g.u.FormData&&a instanceof g.u.FormData;!g.ab(Mqa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.S&&(this.g.withCredentials=this.S);try{m6(this),0<this.B&&(this.I=$pa(this.g),W4(k6(this,"Will abort after "+this.B+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.B,this.g.ontimeout=(0,g.x)(this.Wu,this)):this.G=g.il(this.Wu,this.B,this)),W4(k6(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){W4(k6(this,"Send error: "+f.message)),i6(this,f)}};
g.h.Wu=function(){"undefined"!=typeof g.iZ&&this.g&&(this.o="Timed out after "+this.B+"ms, aborting",this.w=8,k6(this,this.o),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.l&&(k6(this,"Aborting"),this.l=!1,this.u=!0,this.g.abort(),this.u=!1,this.w=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),h6(this))};
g.h.V=function(){this.g&&(this.l&&(this.l=!1,this.u=!0,this.g.abort(),this.u=!1),h6(this,!0));f6.xb.V.call(this)};
g.h.Vu=function(){this.fa()||(this.aa||this.C||this.u?l6(this):this.gJ())};
g.h.gJ=function(){l6(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<j6(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Da(this.o)?this.o:String(this.o)};g.h=o6.prototype;g.h.cj=null;g.h.td=null;g.h.Mb=null;g.h.ip=null;g.h.Gl=null;g.h.qt=null;g.h.Ul=null;g.h.Vj=0;g.h.vG=0;g.h.Pc=null;g.h.Xf=null;g.h.bf=null;g.h.Gg=null;g.h.Qf=null;g.h.Ln=null;g.h.Wh=-1;g.h.Gv=-1;g.h.we=-1;g.h.Dh=0;g.h.xh=0;g.h.Dg=8;var I6=new g.xk;g.Ta(p6,g.ak);g.Ta(q6,g.ak);g.Ta(r6,g.ak);g.h=o6.prototype;g.h.connect=function(a,b,c,d,e){M5(0);this.ip=b;this.cj=c||{};d&&g.Ca(e)&&(this.cj.OSID=d,this.cj.OAID=e);this.w?(W5((0,g.x)(this.Pt,this,a),100),x6(this)):this.Pt(a)};
g.h.Pt=function(a){this.Qf=new a6(this);this.Qf.jp=null;this.Qf.i=this.u;this.Qf.connect(a)};
g.h.Tu=function(){return 0==this.g};
g.h.Yx=function(a){this.Xf=null;C6(this,a)};
g.h.Xx=function(){this.bf=null;this.Mb=new G5(this,this.l,"rpc",this.B);this.Mb.Ng=null;this.Mb.lp=0;var a=this.qt.clone();Q4(a,"RID","rpc");Q4(a,"SID",this.l);Q4(a,"CI",this.Ln?"0":"1");Q4(a,"AID",this.Wh);t6(this,a);if(!g.Jd||g.md(10))Q4(a,"TYPE","xmlhttp"),J5(this.Mb,a,!0,this.Ul,!1);else{Q4(a,"TYPE","html");var b=this.Mb,c=!!this.Ul;b.Kh=3;b.Kf=R4(a.clone());U5(b,c)}};
g.h.Tx=function(a,b){if(0!=this.g&&(this.Mb==a||this.td==a))if(this.we=a.qj,this.td==a&&3==this.g)if(7<this.Dg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.La(c)&&3==c.length)if(0==c[0])a:{if(!this.bf){if(this.Mb)if(this.Mb.pi+3E3<this.td.pi)y6(this),this.Mb.cancel(),this.Mb=null;else break a;F6(this);M5(19)}}else this.Gv=c[1],0<this.Gv-this.Wh&&37500>c[2]&&this.Ln&&0==this.xh&&!this.Gg&&(this.Gg=W5((0,g.x)(this.XG,this),6E3));else H6(this,11)}else b!=Lqa.dN.g&&H6(this,11);else if(this.Mb==a&&
y6(this),!g.yb(b)){c=this.u.parse(b);g.La(c);for(var d=0;d<c.length;d++){var e=c[d];this.Wh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Ul=e[2],e=e[3],null!=e?this.Dg=e:this.Dg=6,this.g=3,this.Pc&&this.Pc.Jt(),this.qt=b6(this,this.qk()?this.Ul:null,this.ip),D6(this)):"stop"==e[0]&&H6(this,7):3==this.g&&("stop"==e[0]?H6(this,7):"noop"!=e[0]&&this.Pc&&this.Pc.It(e),this.xh=0)}}};
g.h.XG=function(){null!=this.Gg&&(this.Gg=null,this.Mb.cancel(),this.Mb=null,F6(this),M5(20))};
g.h.Ym=function(a){if(this.Mb==a){y6(this);this.Mb=null;var b=2}else if(this.td==a)this.td=null,b=1;else return;this.we=a.qj;if(0!=this.g)if(a.ne)1==b?(b=(0,g.A)()-a.pi,I6.dispatchEvent(new q6(I6,a.fh?a.fh.length:0,b,this.Dh)),w6(this),this.o.length=0):D6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.we)){if(d=1==b)this.td||this.Xf||1==this.g||2<=this.Dh?d=!1:(this.Xf=W5((0,g.x)(this.Yx,this,a),E6(this,this.Dh)),this.Dh++,d=!0);d=!(d||2==b&&F6(this))}if(d)switch(c){case 1:H6(this,
5);break;case 4:H6(this,10);break;case 3:H6(this,6);break;case 7:H6(this,12);break;default:H6(this,2)}}};
g.h.wB=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.xL=function(a){a?M5(2):(M5(1),G6(this,8))};
g.h.Io=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new f6;a.S=!1;return a};
g.h.isActive=function(){return!!this.Pc&&this.Pc.isActive(this)};
g.h.me=function(a){I6.dispatchEvent(new r6(I6,a))};
g.h.qk=function(){return!(!g.Jd||g.md(10))};
g.h=J6.prototype;g.h.Jt=function(){};
g.h.It=function(){};
g.h.Ht=function(){};
g.h.Bo=function(){};
g.h.vu=function(){return{}};
g.h.isActive=function(){return!0};g.h=K6.prototype;g.h.isEmpty=function(){return g.bb(this.g)&&g.bb(this.i)};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.rna)(b,a);0<=c?(g.db(b,c),b=!0):b=!1;return b||g.eb(this.i,a)};
g.h.wd=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};g.Ta(L6,g.F);g.h=L6.prototype;g.h.YJ=function(){this.Sc=Math.min(3E5,2*this.Sc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Sc+15E3*Math.random();g.cn(this.g,a);this.i=(0,g.A)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Sc=5E3};g.Ta(M6,J6);g.h=M6.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.yf=function(a){return this.l.Og(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.bb||(this.bb=!0,g.Di(this.l),N6(this),g.Di(this.i),this.i=null)};
g.h.fa=function(){return this.bb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.D="";this.i.stop();this.u=a||null;this.o=b||0;a=this.G+"/test";b=this.G+"/bind";var d=new o6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Pc=null);d.Pc=this;this.g=d;e?this.g.connect(a,b,this.w,e.l,e.Wh):c?this.g.connect(a,b,this.w,c.sessionId,c.arrayId):this.g.connect(a,b,this.w)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):O6(this)&&z6(this.g,c)};
g.h.Jt=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)z6(this.g,a[b])}this.N("handlerOpened")};
g.h.Ht=function(a){var b=2==a&&401==this.g.we;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Bo=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.vu=function(){var a={v:2};this.D&&(a.gsessionid=this.D);0!=this.o&&(a.ui=""+this.o);0!=this.C&&(a.ui=""+this.C);this.u&&g.ec(a,this.u);return a};
g.h.It=function(a){"S"==a[0]?this.D=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),v6(this.g)):this.N("handlerMessage",new dqa(a[0],a[1]))};
g.h.bL=function(){this.i.isActive();var a=this.g,b=0;a.Mb&&b++;a.td&&b++;0==b&&this.connect(this.u,this.o)};P6.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
P6.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
P6.prototype.u=function(a){a(Error("request timed out"))};var jqa=(0,g.A)(),U6=null,Y6=Array(50),X6=-1,Z6=!1;g.Ta($6,g.O);$6.prototype.Kd=function(){return this.g};
$6.prototype.contains=function(a){return!!g5(this.g,a)};
$6.prototype.get=function(a){return a?h5(this.g,a):null};
$6.prototype.info=function(a){W6(this.B,a)};g.r(b7,g.O);g.h=b7.prototype;g.h.start=function(){!this.g&&isNaN(this.Aa)&&this.Uz()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Aa)||(g.Fo(this.Aa),this.Aa=NaN)};
g.h.V=function(){this.stop();g.O.prototype.V.call(this)};
g.h.Uz=function(){this.Aa=NaN;this.g=g.Bp(Q6(this.w,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.ZL,this),onError:(0,g.x)(this.YL,this),Nd:(0,g.x)(this.aM,this)})};
g.h.ZL=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new $4(c))};
g.h.YL=function(a){this.g=null;a.status&&404==a.status?this.i>=l9.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=l9[this.i],this.Aa=g.Do((0,g.x)(this.Uz,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.aM=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var l9=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(d7,$6);g.h=d7.prototype;g.h.start=function(){c7(this)&&this.N("screenChange");!g.Wx("yt-remote-lounge-token-expiration")&&e7(this);g.Fo(this.i);this.i=g.Do((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){c7(this);a7(this,a);f7(this,!1);this.N("screenChange");b(a);a.token||e7(this)};
g.h.remove=function(a,b){var c=c7(this);lqa(this,a)&&(f7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Hn=function(a,b,c,d){var e=c7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,f7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.V=function(){g.Fo(this.i);d7.xb.V.call(this)};
g.h.hC=function(a){c7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}f7(this,!b);b&&W6(this.B,"Missed "+b+" lounge tokens.")};
g.h.gC=function(a){W6(this.B,"Requesting lounge tokens failed: "+a)};g.r(h7,g.O);g.h=h7.prototype;g.h.start=function(){var a=parseInt(g.Wx("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.A)()-144E5<a?0:a)?k7(this):(this.o=(0,g.A)()+3E5,g.Vx("yt-remote-fast-check-period",this.o),this.ir())};
g.h.isEmpty=function(){return g.Zb(this.g)};
g.h.update=function(){g7("Updating availability on schedule.");var a=this.w(),b=g.Nb(this.g,function(c,d){return c&&!!h5(a,d)},this);
j7(this,b)};
g.h.V=function(){g.Fo(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.O.prototype.V.call(this)};
g.h.ir=function(){g.Fo(this.l);this.l=NaN;this.i&&this.i.abort();var a=l7(this);if(U4(a)){var b=Q6(this.u,"/pairing/get_screen_availability");this.i=R6(this.u,b,{lounge_token:g.Tb(a).join(",")},(0,g.x)(this.CJ,this,a),(0,g.x)(this.BJ,this))}else j7(this,{}),k7(this)};
g.h.CJ=function(a,b){this.i=null;var c=g.Tb(l7(this));if(g.sb(c,g.Tb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;j7(this,d);k7(this)}else this.Fb("Changing Screen set during request."),this.ir()};
g.h.BJ=function(a){this.Fb("Screen availability failed: "+a);this.i=null;k7(this)};
g.h.Fb=function(a){W6("OnlineScreenService",a)};g.Ta(m7,$6);g.h=m7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Hn=function(a,b,c,d){this.l.contains(a)?this.l.Hn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,W6(this.B,a),d(Error(a)))};
g.h.Kd=function(a){return a?this.g:g.gb(this.g,(0,g.Wd)(this.o,function(b){return!this.contains(b)},this))};
g.h.Vz=function(){return(0,g.Wd)(this.Kd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.Wz=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new b7(this.w,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.Di(f);d(n7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Di(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.cM=function(a,b,c,d){g.Bp(Q6(this.w,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new $4(f.screen||{});if(!k.name||p7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);p7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(n7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Nd:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.Di(this.l);g.Di(this.i);m7.xb.V.call(this)};
g.h.oC=function(){q7(this);this.N("screenChange");this.i.update()};
m7.prototype.dispose=m7.prototype.dispose;g.Ta(s7,g.O);g.h=s7.prototype;g.h.an=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Md=function(a){this.fa()||(a&&t7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){W6(this.R,a)};
g.h.Yz=function(){return null};
g.h.tr=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){t7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.tr("");s7.xb.V.call(this)};g.Ta(v7,s7);g.h=v7.prototype;g.h.sr=function(a){if(this.g){if(this.g==a)return;t7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.w);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.w);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);pqa(this)};
g.h.Xh=function(a){this.info("launchWithParams no-op for Cast: "+g.Aj(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Md()},this),(0,g.x)(function(){this.Md(Error("Failed to stop receiver app."))},this)):this.Md(Error("Stopping cast device witout session."))};
g.h.tr=g.Ha;g.h.V=function(){this.info("disposeInternal");g.Fo(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.w),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;v7.xb.V.call(this)};
g.h.AK=function(a,b){if(!this.fa())if(b){var c=A5(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Aj(c));switch(d){case "mdxSessionStatus":u7(this,c.screenId);break;default:t7(this,"Unknown youtube message: "+d)}}else t7(this,"Unable to parse message.")}else t7(this,"No data in message.")};
g.h.Ou=function(a,b,c,d){o7(this.D,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(t7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Do((0,g.x)(this.Ou,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.Yz=function(){return this.g};
g.h.dM=function(a){this.fa()||a||(t7(this,"Cast session died."),this.Md())};g.Ta(w7,s7);g.h=w7.prototype;g.h.sr=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.Xh=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ha;g.Fo(this.w);this.o?this.o.stop((0,g.x)(this.Md,this,null),(0,g.x)(this.Md,this,"Failed to stop DIAL device.")):this.Md()};
g.h.V=function(){this.g();this.g=g.Ha;g.Fo(this.w);this.o&&this.o.removeUpdateListener(this.I);this.o=null;w7.xb.V.call(this)};
g.h.gM=function(a){this.fa()||a||(t7(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Md())};
g.h.zp=function(a){this.G=f5();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,y7(this));a(b);x7(this)}else this.B=(0,g.x)(function(){g.Fo(this.w);this.B=g.Ha;this.w=NaN;var c=new chrome.cast.DialLaunchResponse(!0,y7(this));a(c);x7(this)},this),this.w=g.Do((0,g.x)(function(){this.B()},this),100)};
g.h.IC=function(a,b,c){o7(this.D,this.C.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.an(d),b(new chrome.cast.DialLaunchResponse(!1))):this.zp(b,c)},this),(0,g.x)(function(d){t7(this,"Failed to get DIAL screen: "+d);
this.zp(b,c)},this))};g.Ta(z7,s7);z7.prototype.stop=function(){this.Md()};
z7.prototype.sr=g.Ha;z7.prototype.Xh=function(){g.Fo(this.g);this.g=NaN;var a=h5(this.D.Kd(),this.i.label);a?this.an(a):this.Md(Error("No such screen"))};
z7.prototype.V=function(){g.Fo(this.g);this.g=NaN;z7.xb.V.call(this)};g.Ta(A7,g.O);g.h=A7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.C||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.lJ,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.Vx,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.xH,this);chrome.cast.initialize(c,(0,g.x)(function(){this.fa()||
(chrome.cast.addReceiverActionListener(this.o),gqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.Xz,this)),this.l=F7(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(k){this.Fb("Failed to set initial custom receivers: "+g.Aj(k))},this)),this.N("yt-remote-cast2-availability-change",D7(this)),b(!0))},this),(0,g.x)(function(k){this.Fb("Failed to initialize API: "+g.Aj(k));
b(!1)},this))};
g.h.jL=function(a,b){C7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)C7("Unsetting old screen status: "+this.g.i.friendlyName),E7(this,null)}if(a&&b){if(!this.g){c=h5(this.i.Kd(),a);if(!c){C7("setConnectedScreenStatus: Unknown screen.");return}var d=B7(this,c);d||(C7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.x)(function(e){this.Fb("Failed to set initial custom receivers: "+g.Aj(e))},this)));
C7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);E7(this,new z7(this.i,d),!0)}this.g.tr(b)}else C7("setConnectedScreenStatus: no screen.")};
g.h.kL=function(a){this.fa()?this.Fb("Setting connection data on disposed cast v2"):this.g?this.g.Xh(a):this.Fb("Setting connection data without a session")};
g.h.fM=function(){this.fa()?this.Fb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),E7(this,null)):C7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.Vx,this),(0,g.x)(this.IJ,this))};
g.h.V=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.Xz,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.eb(g.w("yt.mdx.remote.debug.handlers_")||[],S6);g.Di(this.g);A7.xb.V.call(this)};
g.h.Fb=function(a){W6("Controller",a)};
g.h.Wx=function(a,b){this.g==a&&(b||E7(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.hJ=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),C7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)C7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{C7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:E7(this,
new z7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:E7(this,new w7(this.i,a,this.w));break;case chrome.cast.ReceiverType.CAST:E7(this,new v7(this.i,a));break;default:this.Fb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Fb("Stopping receiver w/o session: "+a.friendlyName)}else this.Fb("onReceiverAction_ called without receiver.")};
g.h.xH=function(a){if(this.fa())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Fb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Fb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return C7("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Fb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);E7(this,new w7(this.i,b,this.w))}b=this.g;b.C=a;return b.C.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.IC,b,(b.C.extraData||{}).screenId||null)):new Promise((0,g.x)(b.zp,b))};
g.h.Vx=function(a){if(!this.fa()){C7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)C7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),E7(this,new v7(this.i,b),!0);else{this.Fb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=h5(this.i.Kd(),c.label);d&&a5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(C7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Di(this.g),this.g=new v7(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.Wx,this,this.g)),this.g.Xh(null));this.g.sr(a)}}};
g.h.eM=function(){return this.g?this.g.Yz():null};
g.h.IJ=function(a){this.fa()||(this.Fb("Failed to estabilish a session: "+g.Aj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&E7(this,null))};
g.h.lJ=function(a){C7("Receiver availability updated: "+a);if(!this.fa()){var b=D7(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;D7(this)!=b&&this.N("yt-remote-cast2-availability-change",D7(this))}};
g.h.Xz=function(){this.fa()||(this.l=F7(this),C7("Updating custom receivers: "+g.Aj(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(){this.Fb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",D7(this)))};
A7.prototype.setLaunchParams=A7.prototype.kL;A7.prototype.setConnectedScreenStatus=A7.prototype.jL;A7.prototype.stopSession=A7.prototype.fM;A7.prototype.getCastSession=A7.prototype.eM;A7.prototype.requestSession=A7.prototype.requestSession;A7.prototype.init=A7.prototype.init;A7.prototype.dispose=A7.prototype.dispose;var O7=[];W7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";X7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.xe=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.w=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.C=a.duration,this.D=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
W7.prototype.isAdPlaying=function(){return 1081==this.playerState};
W7.prototype.getDuration=function(){return this.u?this.C+Y7(this):this.C};
W7.prototype.clone=function(){return new W7(b8(this))};g.r(e8,g.O);g.h=e8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,m8(this,"play")):k8(this,"play"),j8(this,1,$7(f8(this))),this.N("remotePlayerChange")):h8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,m8(this,"pause")):k8(this,"pause"),j8(this,2,$7(f8(this))),this.N("remotePlayerChange")):h8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=f8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,m8(this,"seekTo",{newTime:a}))}else k8(this,"seekTo",{newTime:a});j8(this,3,a);this.N("remotePlayerChange")}else h8(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,m8(this,"stopVideo")):k8(this,"stopVideo");var a=f8(this);a.index=-1;a.videoId="";X7(a);i8(this,a);this.N("remotePlayerChange")}else h8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=f8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){W6("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Fb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){W6("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Fb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);k8(this,"setVolume",e)}c.muted=b;c.volume=a;i8(this,c)}else h8(this,g.Ra(this.setVolume,a,b))};
g.h.Xy=function(a,b){if(1==this.g){var c=f8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Aj(b.style),g.ec(d,c.g));k8(this,"setSubtitlesTrack",d);i8(this,c)}else h8(this,g.Ra(this.Xy,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();k8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=f8(this);d.audioTrackId=c;i8(this,d)}else h8(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=f8(this);c=c||0;var m={videoId:a,currentIndex:c};a8(l,a,c);g.Ca(b)&&(Z7(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Aj(k));k8(this,"setPlaylist",m);d||i8(this,l)};
g.h.Tz=function(a,b){if(1==this.g){if(a&&b){var c=f8(this);a8(c,a,b);i8(this,c)}k8(this,"previous")}else h8(this,g.Ra(this.Tz,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=f8(this);a8(c,a,b);i8(this,c)}k8(this,"next")}else h8(this,g.Ra(this.nextVideo,a,b))};
g.h.Xt=function(){1==this.g?k8(this,"dismissAutoplay"):h8(this,this.Xt)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.O.prototype.dispose.call(this)};
g.h.V=function(){g8(this);this.o=null;this.u.clear();d8(this,null);g.O.prototype.V.call(this)};
g.h.Xr=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,g.bb(b.g)&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.eJ=function(a,b){this.N(a,b)};
g.h.dH=function(a){if(!a)this.Yj(null),d8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=f8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)W6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,i8(this,b)}};
g.h.Yj=function(a){W6("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.C);if(this.i=a)this.i.addUpdateListener(this.C),l8(this),this.N("remotePlayerChange")};
g.h.cH=function(a){a?(l8(this),this.N("remotePlayerChange")):this.Yj(null)};
g.h.pH=function(){var a=S7();a&&d8(this,a)};
g.h.Fb=function(a){W6("CP",a)};g.r(n8,g.O);g.h=n8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;Z7(this.Oa,m);this.o="UNSUPPORTED";o8("Connecting with setPlaylist and params: "+g.Aj(l));this.g.connect({method:"setPlaylist",
params:g.Aj(l)},a,n5())}else o8("Connecting without params"),this.g.connect({},a,n5());wqa(this)};
g.h.dispose=function(){this.fa()||(this.N("beforeDispose"),p8(this,3));g.O.prototype.dispose.call(this)};
g.h.V=function(){q8(this);s8(this);r8(this);g.Fo(this.B);this.B=NaN;g.Fo(this.C);this.C=NaN;this.l=null;g.ar(this.R);this.R.length=0;this.g.dispose();g.O.prototype.V.call(this);this.o=this.w=this.i=this.Oa=this.g=null};
g.h.aC=function(){this.Bh(2)};
g.h.hH=function(){o8("Channel opened");this.I&&(this.I=!1,r8(this),this.G=g.Do((0,g.x)(function(){o8("Timing out waiting for a screen.");this.Bh(1)},this),15E3));
Vpa(eqa(this.g),this.M)};
g.h.eH=function(){o8("Channel closed");isNaN(this.u)?q5(!0):q5();this.dispose()};
g.h.fH=function(a){q5();isNaN(this.jj())?(o8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,o8("Channel error: "+a+" with reconnection in "+this.jj()+" ms"),p8(this,2))};
g.h.gH=function(a){a.params?o8("Received: action="+a.action+", params="+g.Aj(a.params)):o8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=A5(a.params.devices);this.i=(0,g.fe)(a,function(c){return new Z4(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
v8(this,a);break;case "loungeScreenDisconnected":g.fb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
v8(this,!1);break;case "remoteConnected":var b=new Z4(A5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||Ipa(this.i,b);
break;case "remoteDisconnected":b=new Z4(A5(a.params.device));g.fb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":w8(this,a);break;case "nowPlaying":zqa(this,a);break;case "onStateChange":x8(this,a);break;case "onAdStateChange":Aqa(this,a);break;case "onVolumeChanged":Bqa(this,a);break;case "onSubtitlesTrackChanged":yqa(this,a);break;case "nowAutoplaying":Cqa(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.w=a.params.videoId||null;this.N("autoplayUpNext",this.w);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":Dqa(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:o8("Unrecognized action: "+a.action)}};
g.h.YK=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&t8(this,"getNowPlaying")}};
g.h.QB=function(){var a=3;this.fa()||(a=0,isNaN(this.jj())?O6(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Bh=function(a){o8("Disconnecting with "+a);q8(this);this.N("beforeDisconnect",a);1==a&&q5();N6(this.g,a);this.dispose()};
g.h.PB=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),a8(a,this.l,a.index));return b8(a)};
g.h.lL=function(a){var b=new W7(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.Fo(this.B),this.B=g.Do((0,g.x)(this.YK,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&$7(this.Oa)==$7(b)&&g.Aj(this.Oa.g)==g.Aj(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.z)(c,function(d){this.N(d)},this)};
g.h.Mu=function(){var a=this.g.w.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.jj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.A)():NaN};
g.h.JB=function(){return this.o||"UNSUPPORTED"};
g.h.KB=function(){return this.w||""};
g.h.XL=function(){if(!isNaN(this.jj())){var a=this.g.i;g.dn(a.g);a.start()}};
g.h.gL=function(a,b){t8(this,a,b);u8(this)};
n8.prototype.subscribe=n8.prototype.subscribe;n8.prototype.unsubscribeByKey=n8.prototype.yf;n8.prototype.getProxyState=n8.prototype.QB;n8.prototype.disconnect=n8.prototype.Bh;n8.prototype.getPlayerContextData=n8.prototype.PB;n8.prototype.setPlayerContextData=n8.prototype.lL;n8.prototype.getOtherConnectedRemoteId=n8.prototype.Mu;n8.prototype.getReconnectTimeout=n8.prototype.jj;n8.prototype.getAutoplayMode=n8.prototype.JB;n8.prototype.getAutoplayVideoId=n8.prototype.KB;n8.prototype.reconnect=n8.prototype.XL;
n8.prototype.sendMessage=n8.prototype.gL;g.r(y8,$6);g.h=y8.prototype;g.h.Kd=function(a){return this.Rc.$_gs(a)};
g.h.contains=function(a){return!!this.Rc.$_c(a)};
g.h.get=function(a){return this.Rc.$_g(a)};
g.h.start=function(){this.Rc.$_st()};
g.h.add=function(a,b,c){this.Rc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Rc.$_r(a,b,c)};
g.h.Hn=function(a,b,c,d){this.Rc.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.i.length;a<b;++a)this.Rc.$_ubk(this.i[a]);this.i.length=0;this.Rc=null;$6.prototype.V.call(this)};
g.h.bM=function(){this.N("screenChange")};
g.h.HI=function(){this.N("onlineScreenChange")};
m7.prototype.$_st=m7.prototype.start;m7.prototype.$_gspc=m7.prototype.cM;m7.prototype.$_gsppc=m7.prototype.Wz;m7.prototype.$_c=m7.prototype.contains;m7.prototype.$_g=m7.prototype.get;m7.prototype.$_a=m7.prototype.add;m7.prototype.$_un=m7.prototype.Hn;m7.prototype.$_r=m7.prototype.remove;m7.prototype.$_gs=m7.prototype.Kd;m7.prototype.$_gos=m7.prototype.Vz;m7.prototype.$_s=m7.prototype.subscribe;m7.prototype.$_ubk=m7.prototype.yf;var U8=null,T8=!1,z8=null,A8=null,Q8=null,E8=[];g.r(V8,g.F);g.h=V8.prototype;
g.h.V=function(){g.F.prototype.V.call(this);this.o.stop();this.w.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Sx,this);this.g.unsubscribe("remotePlayerChange",this.ak,this);this.g.unsubscribe("remoteQueueChange",this.bn,this);this.g.unsubscribe("autoplayUpNext",this.tx,this);this.g.unsubscribe("previousNextChange",this.Px,this);this.g.unsubscribe("nowAutoplaying",this.Lx,this);this.g.unsubscribe("autoplayDismissed",this.sx,this);this.g=this.u=null};
g.h.ow=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(Z8(this)){if(!f8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==f8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.G.Tl(c[0],c[1]);break;case "control_subtitles_set_track":$8(this,c[0]);break;case "control_set_audio_track":c=c[0],Z8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();a9(this,0==c?void 0:c);break;case "control_seek":a9(this,c[0]);break;case "control_subtitles_set_track":$8(this,c[0]);break;case "control_set_audio_track":c=c[0],Z8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.bH=function(a){this.I.WB(a)};
g.h.GL=function(a){this.ow("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.iz=function(){var a=this.i.getOption("captions","track");g.Zb(a)||$8(this,a)};
g.h.Ex=function(a){if(Z8(this)){this.g.unsubscribe("remotePlayerChange",this.ak,this);var b=Math.round(a.volume);a=!!a.muted;var c=f8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.R.start();this.g.subscribe("remotePlayerChange",this.ak,this)}};
g.h.cI=function(){g.Zb(this.B)||b9(this,this.B);this.C=!1};
g.h.Sx=function(a,b){this.w.stop();2==b&&this.hz()};
g.h.ak=function(){if(Z8(this)){this.o.stop();var a=f8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.D=1;break;case 1082:case 1083:this.u.D=0;break;default:this.u.D=-1}switch(a.playerState){case 1081:case 1:X8(this,new g.vt(8));this.gz();break;case 1085:case 3:X8(this,new g.vt(9));break;case 1083:case 0:X8(this,new g.vt(2));this.G.stop();W8(this,this.i.getVideoData().lengthSeconds);break;case 1084:X8(this,new g.vt(4));break;case 2:X8(this,new g.vt(4));W8(this,$7(a));
break;case -1:X8(this,new g.vt(64));break;case -1E3:X8(this,new g.vt(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=f8(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,b9(this,a));a=f8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.R.isActive()||this.Iz()}else Y8(this)};
g.h.Px=function(){this.i.N("mdxpreviousnextchange")};
g.h.bn=function(){Z8(this)||Y8(this)};
g.h.bB=function(){this.g.Xt()};
g.h.tx=function(a){a&&!g.P(this.i.L().experiments,"disable_legacy_desktop_remote_queue")&&(a=g.Bp("/watch_queue_ajax",{method:"GET",pd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.jK,this)}))&&(this.M=(0,g.x)(a.abort,a))};
g.h.jK=function(a,b){var c=new g.FB(this.i.L(),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Lx=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.sx=function(){this.i.N("mdxautoplaycanceled")};
g.h.yE=function(a,b){-1==f8(this.g).playerState?a9(this,a):b&&this.g.seekTo(a)};
g.h.Iz=function(){if(Z8(this)){var a=f8(this.g);this.l.Sa(this.P);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.P=this.l.J(this.i,"onVolumeChange",this.Ex)}};
g.h.gz=function(){this.o.stop();if(!this.g.fa()){var a=f8(this.g);1==a.playerState&&X8(this,new g.vt(8));W8(this,$7(a));this.o.start()}};
g.h.hz=function(){this.w.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.w.start()};g.r(d9,g.T);d9.prototype.o=function(){X4("mdx-privacy-popup-cancel");this.l.hide()};
d9.prototype.w=function(){X4("mdx-privacy-popup-confirm");this.l.hide()};g.r(f9,g.T);f9.prototype.u=function(a){e9(this,a.state)};g.r(g9,g.JN);g9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.B=g.ub(a,this.w,this),g.LN(this,(0,g.fe)(a,this.w)),a=this.l.getOption("remote","currentReceiver"),this.de(this.w(a)),this.enable(!0)):this.enable(!1)};
g9.prototype.w=function(a){return a.key};
g9.prototype.le=function(a){return"cast-selector-receiver"==a?"Cast...":this.B[a].name};
g9.prototype.Jc=function(a){g.JN.prototype.Jc.call(this,a);this.l.setOption("remote","currentReceiver",this.B[a]);this.o.gb()};g.r(h9,g.SO);g.h=h9.prototype;
g.h.create=function(){Iqa(g.Ry(this.player.L()));this.o.push(g.Ko("yt-remote-before-disconnect",this.YG,this));this.o.push(g.Ko("yt-remote-connection-change",this.mJ,this));this.o.push(g.Ko("yt-remote-receiver-availability-change",this.Qx,this));this.o.push(g.Ko("yt-remote-auto-connect",this.kJ,this));this.o.push(g.Ko("yt-remote-receiver-resumed",this.jJ,this));this.o.push(g.Ko("mdx-privacy-popup-confirm",this.OK,this));this.o.push(g.Ko("mdx-privacy-popup-cancel",this.NK,this));this.Qx()};
g.h.load=function(){this.player.cancelPlayback();g.SO.prototype.load.call(this);this.u=new V8(this,this.player,this.g);var a=(a=S8())?a.currentTime:0;var b=P8()?new e8(K8(),void 0):null;0==a&&b&&(a=$7(f8(b)));0!=a&&(this.R=a||0,this.player.N("progresssync",a,void 0));c9(this,this.B,this.B);g.bS(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.Ei(this.u,this.g);this.g=this.u=null;g.SO.prototype.unload.call(this);g.bS(this.player.app,5);i9(this)};
g.h.V=function(){g.Lo(this.o);g.SO.prototype.V.call(this)};
g.h.Lj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.ow.apply(this.u,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.D};
g.h.SB=function(){return this.loaded?this.u.suggestion:null};
g.h.xe=function(){return this.g?f8(this.g).xe:!1};
g.h.hasNext=function(){return this.g?f8(this.g).hasNext:!1};
g.h.getCurrentTime=function(){return this.R};
g.h.getProgressState=function(){var a=f8(this.g),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.L().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.gc():!a.isAdPlaying()&&this.player.gc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+Y7(a):a.l,isAtLiveHead:1>=(a.u?a.i+Y7(a):a.i)-this.getCurrentTime(),loaded:a.D,seekableEnd:a.u?a.i+Y7(a):a.i,seekableStart:0<a.o?a.o+Y7(a):
a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.mE=function(){this.g&&this.g.Tz()};
g.h.YG=function(a){1==a&&(this.M=this.g?f8(this.g):null)};
g.h.mJ=function(){var a=P8()?new e8(K8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.M=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.Di(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.M)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,$7(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Qx=function(){this.G=[this.i].concat(Jqa());var a=L8()||this.i;j9(this,a);this.player.ha("onMdxReceiversChange")};
g.h.FK=function(a){!this.I&&g.dD(a,8)&&(this.player.pauseVideo(),i9(this))};
g.h.kJ=function(){var a=L8();j9(this,a)};
g.h.jJ=function(){this.l=L8()};
g.h.OK=function(){this.I=!0;i9(this);T8=!1;U8&&N8(U8,1);U8=null};
g.h.NK=function(){this.I=!1;i9(this);j9(this,this.i);this.l=this.i;T8=!1;U8=null;this.player.playVideo()};
g.h.qc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?U7():j9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&U7(),!0):!1}};
g.h.nE=function(){k8(this.g,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ne=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.fP.remote=h9;})(_yt_player);
