(function(g){var window=this;var rFa=function(a,b){return g.Sb(a,b)},$5=function(a,b,c){a.A.set(b,c)},a6=function(a){$5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.z()).toString(36));
return a},b6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.hn(a.A,b,c)},sFa=function(a,b){var c=[];
g.Zi(b,function(d){try{var e=g.Vn.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Un(e)&&c.push(d)},a);
return c},tFa=function(a,b){var c=sFa(a,b);
g.Gb(c,function(d){g.Vn.prototype.remove.call(this,d)},a)},uFa=function(a){if(a.Fd){if(a.Fd.locationOverrideToken)return{locationOverrideToken:a.Fd.locationOverrideToken};
if(null!=a.Fd.latitudeE7&&null!=a.Fd.longitudeE7)return{latitudeE7:a.Fd.latitudeE7,longitudeE7:a.Fd.longitudeE7}}return null},vFa=function(a,b){g.lb(a,b)||a.push(b)},c6=function(a){var b=0,c;
for(c in a)b++;return b},wFa=function(a,b){var c=b instanceof g.Ec?b:g.Kc(b,/^data:image\//i.test(b));
a.src=g.Fc(c)},d6=function(){},xFa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},yFa=function(a){if(a.Fe&&"function"==typeof a.Fe)return a.Fe();
if("string"===typeof a)return a.split("");if(g.Pa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Ob(a)},zFa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Pa(a)||"string"===typeof a)g.Gb(a,b,void 0);else{if(a.Qf&&"function"==typeof a.Qf)var c=a.Qf();else if(a.Fe&&"function"==typeof a.Fe)c=void 0;else if(g.Pa(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Pb(a);d=yFa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},AFa=function(a,b,c,d){var e=new g.Wm(null,void 0);
a&&g.Xm(e,a);b&&g.Ym(e,b);c&&g.Zm(e,c);d&&(e.u=d);return e},e6=function(a,b){g.Jo[a]=!0;
var c=g.Ho();c&&c.publish.apply(c,arguments);g.Jo[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Tm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",BFa(this,a.capabilities||""),CFa(this,a.experiments||""))},BFa=function(a,b){a.capabilities.clear();
g.Ie(b.split(","),g.Ua(rFa,DFa)).forEach(function(c){a.capabilities.add(c)})},CFa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},EFa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},FFa=function(a){return new g6(a)},GFa=function(a){return Array.isArray(a)?g.Oc(a,FFa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return Array.isArray(a)?"["+g.Oc(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},HFa=function(a){return g.Oc(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.gb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.gb(a,function(c){return h6(c,b)})},IFa=function(){var a=(0,g.lt)();
a&&tFa(a,a.o.Th(!0))},n6=function(){var a=g.ot("yt-remote-connected-devices")||[];
g.Cb(a);return a},JFa=function(a){if(g.nb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Oc(a,function(d,e){return 0==e?d:d.substring(c.length)})},KFa=function(a){g.nt("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.ot("yt-remote-device-id");a||(a=k6(),g.nt("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.lb(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.lb(a,b);g.qt()&&g.Fb(a,b);a=JFa(a);if(g.nb(a))try{g.wq("remote_sid")}catch(c){}else try{g.uq("remote_sid",a.join(","),-1)}catch(c){}},LFa=function(){return g.ot("yt-remote-session-browser-channel")},MFa=function(){return g.ot("yt-remote-local-screens")||[]},NFa=function(){g.nt("yt-remote-lounge-token-expiration",!0,86400)},OFa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Oc(MFa(),function(d){return d.loungeToken}),c=g.Oc(a,function(d){return d.loungeToken});
g.gh(c,function(d){return!g.lb(b,d)})&&NFa();
g.nt("yt-remote-local-screens",a,31536E3)},PFa=function(a,b){g.nt("yt-remote-session-browser-channel",a);
g.nt("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.lb(c,d)||c.push(d);KFa(c);q6()},r6=function(a){a||(g.pt("yt-remote-session-screen-id"),g.pt("yt-remote-session-video-id"));
q6();a=n6();g.qb(a,p6());KFa(a)},QFa=function(){if(!s6){var a=g.fo();
a&&(s6=new g.Pn(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},RFa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},SFa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?TFa(a.shift(),function(){t6(a)}):u6()},UFa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},TFa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.hd(d,g.jg(a));(document.head||document.documentElement).appendChild(d)},u6=function(){var a=SFa();
a&&a(!1,"No cast extension found")},WFa=function(){if(VFa){var a=2,b=SFa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;TFa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},XFa=function(){WFa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},v6=function(a,b,c){g.B.call(this);
this.F=null!=c?(0,g.y)(a,c):a;this.qe=b;this.C=(0,g.y)(this.QH,this);this.o=!1;this.u=0;this.A=this.La=null;this.B=[]},w6=function(a,b,c){g.B.call(this);
this.B=null!=c?a.bind(c):a;this.qe=b;this.A=null;this.o=!1;this.u=0;this.La=null},x6=function(a){a.La=g.Rm(function(){a.La=null;
a.o&&!a.u&&(a.o=!1,x6(a))},a.qe);
var b=a.A;a.A=null;a.B.apply(null,b)},y6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return xFa(a)},z6=function(){},A6=function(){},YFa=function(){},$Fa=function(a){return(a=ZFa(a))?new ActiveXObject(a):new XMLHttpRequest},ZFa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},B6=function(a,b,c,d){this.o=a;
this.u=b;this.J=c;this.H=d||1;this.C=45E3;this.B=new g.Z0(this);this.A=new g.Qm;this.A.setInterval(250)},bGa=function(a,b,c){a.Wm=1;
a.Ri=a6(b.clone());a.ll=c;a.F=!0;aGa(a,null)},C6=function(a,b,c,d,e){a.Wm=1;
a.Ri=a6(b.clone());a.ll=null;a.F=c;e&&(a.GE=!1);aGa(a,d)},aGa=function(a,b){a.Qm=g.z();
D6(a);a.Ij=a.Ri.clone();b6(a.Ij,"t",a.H);a.Fp=0;a.Gd=a.o.Du(a.o.np()?b:null);0<a.tv&&(a.Ns=new w6((0,g.y)(a.FF,a,a.Gd),a.tv));a.B.ia(a.Gd,"readystatechange",a.dP);var c=a.yk?g.Yb(a.yk):{};a.ll?(a.Gt="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Gd.send(a.Ij,a.Gt,a.ll,c)):(a.Gt="GET",a.GE&&!g.ye&&(c.Connection="close"),a.Gd.send(a.Ij,a.Gt,null,c));a.o.Jg(1)},fGa=function(a,b,c){for(var d=!0;!a.ck&&a.Fp<c.length;){var e=cGa(a,c);
if(e==E6){4==b&&(a.gj=4,F6(15),d=!1);break}else if(e==dGa){a.gj=4;F6(16);d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.gj=1,F6(17),d=!1);a.Sg=a.Sg&&d;d||(H6(a),I6(a))},cGa=function(a,b){var c=a.Fp,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if(isNaN(c))return dGa;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.Fp=d+c;return e},hGa=function(a,b){a.Qm=g.z();
D6(a);var c=b?window.location.hostname:"";a.Ij=a.Ri.clone();$5(a.Ij,"DOMAIN",c);$5(a.Ij,"t",a.H);try{a.Xg=new ActiveXObject("htmlfile")}catch(n){H6(a);a.gj=7;F6(22);I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)e+="\\x3c";else if(">"==h)e+="\\x3e";else{var l=h;if(l in J6)h=J6[l];else if(l in gGa)h=J6[l]=gGa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)h=l;else{if(256>m){if(h="\\x",16>m||256<m)h+="0"}else h="\\u",4096>m&&(h+="0");h+=m.toString(16).toUpperCase()}h=
J6[l]=h}e+=h}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.ed(g.jc("b/12014412"),d+"</body></html>");a.Xg.open();a.Xg.write(g.ad(c));a.Xg.close();a.Xg.parentWindow.m=(0,g.y)(a.qO,a);a.Xg.parentWindow.d=(0,g.y)(a.FD,a,!0);a.Xg.parentWindow.rpcClose=(0,g.y)(a.FD,a,!1);c=a.Xg.createElement("DIV");a.Xg.parentWindow.document.body.appendChild(c);d=g.Jc(a.Ij.toString());d=g.ld(g.Fc(d));d=g.ed(g.jc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.fd(c,d);a.o.Jg(1)},D6=function(a){a.jy=g.z()+a.C;
iGa(a,a.C)},iGa=function(a,b){if(null!=a.cn)throw Error("WatchDog timer not null");
a.cn=K6((0,g.y)(a.CO,a),b)},L6=function(a){a.cn&&(g.v.clearTimeout(a.cn),a.cn=null)},I6=function(a){a.o.IA()||a.ck||a.o.fr(a)},H6=function(a){L6(a);
g.ag(a.Ns);a.Ns=null;a.A.stop();g.pza(a.B);if(a.Gd){var b=a.Gd;a.Gd=null;b.abort();b.dispose()}a.Xg&&(a.Xg=null)},G6=function(a,b){try{a.o.xD(a,b),a.o.Jg(4)}catch(c){}},kGa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;jGa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){kGa(a,b,c,d,f)},f)})}},jGa=function(a,b,c){var d=new Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
wFa(d,a)},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},lGa=function(a){this.o=a;
this.u=new z6},mGa=function(a){var b=N6(a.o,a.qn,"/mail/images/cleardot.gif");
a6(b);kGa(b.toString(),5E3,(0,g.y)(a.OG,a),3,2E3);a.Jg(1)},P6=function(a){var b=a.o.J;
if(null!=b)F6(5),b?(F6(11),O6(a.o,a,!1)):(F6(12),O6(a.o,a,!0));else if(a.ff=new B6(a,void 0,void 0,void 0),a.ff.yk=a.ov,b=a.o,b=N6(b,b.np()?a.Vn:null,a.qv),F6(5),!g.we||g.Yd(10))b6(b,"TYPE","xmlhttp"),C6(a.ff,b,!1,a.Vn,!1);else{b6(b,"TYPE","html");var c=a.ff;a=!!a.Vn;c.Wm=3;c.Ri=a6(b.clone());hGa(c,a)}},Q6=function(a){g.fm.call(this);
this.headers=new g.Tm;this.W=a||null;this.A=!1;this.U=this.o=null;this.na=this.M="";this.F=0;this.B="";this.C=this.ca=this.J=this.X=!1;this.H=0;this.P=null;this.oa="";this.S=this.aa=!1},nGa=function(a){return g.we&&g.Xd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},oGa=function(a){return"content-type"==a.toLowerCase()},qGa=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.F=5;pGa(a);R6(a)},pGa=function(a){a.X||(a.X=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},sGa=function(a){if(a.A&&"undefined"!=typeof g.d1)if(a.U[1]&&4==S6(a)&&2==a.getStatus())T6(a,"Local request error detected and ignored");
else if(a.J&&4==S6(a))g.Rm(a.tD,0,a);else if(a.dispatchEvent("readystatechange"),4==S6(a)){T6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.vd(1,String(a.M));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!rGa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.F=6;try{var l=2<S6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";pGa(a)}}finally{R6(a)}}},R6=function(a,b){if(a.o){tGa(a);
var c=a.o,d=a.U[0]?g.Ma:null;a.o=null;a.U=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},tGa=function(a){a.o&&a.S&&(a.o.ontimeout=null);
a.P&&(g.v.clearTimeout(a.P),a.P=null)},S6=function(a){return a.o?a.o.readyState:0},U6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},T6=function(a,b){return b+" ["+a.na+" "+a.M+" "+a.getStatus()+"]"},V6=function(a,b,c){this.va=1;
this.o=[];this.A=[];this.B=new z6;this.H=a||null;this.J=null!=b?b:null;this.C=c||!1},uGa=function(a,b){this.o=a;
this.map=b;this.context=null},vGa=function(a){g.Jl.call(this,"statevent",a)},wGa=function(a,b,c,d){g.Jl.call(this,"timingevent",a);
this.size=b;this.ep=d},xGa=function(a){g.Jl.call(this,"serverreachability",a)},AGa=function(a){yGa(a);
if(3==a.va){var b=a.Fo++,c=a.Mq.clone();$5(c,"SID",a.u);$5(c,"RID",b);$5(c,"TYPE","terminate");W6(a,c);b=new B6(a,a.u,b,void 0);b.Wm=2;b.Ri=a6(c.clone());wFa(new Image,b.Ri.toString());b.Qm=g.z();D6(b)}zGa(a)},BGa=function(a){a.mH(1,0);
a.Mq=N6(a,null,a.lv);X6(a)},yGa=function(a){a.Ui&&(a.Ui.abort(),a.Ui=null);
a.Zc&&(a.Zc.cancel(),a.Zc=null);a.Uh&&(g.v.clearTimeout(a.Uh),a.Uh=null);Y6(a);a.Ve&&(a.Ve.cancel(),a.Ve=null);a.Yi&&(g.v.clearTimeout(a.Yi),a.Yi=null)},CGa=function(a,b){if(0==a.va)throw Error("Invalid operation: sending map when state is closed");
a.o.push(new uGa(a.aL++,b));2!=a.va&&3!=a.va||X6(a)},X6=function(a){a.Ve||a.Yi||(a.Yi=K6((0,g.y)(a.ED,a),0),a.Xl=0)},EGa=function(a,b){if(1==a.va){if(!b){a.Fo=Math.floor(1E5*Math.random());
var c=a.Fo++,d=new B6(a,"",c,void 0);d.yk=a.em;var e=Z6(a),f=a.Mq.clone();$5(f,"RID",c);$5(f,"CVER","1");W6(a,f);bGa(d,f,e);a.Ve=d;a.va=2}}else 3==a.va&&(b?DGa(a,b):0==a.o.length||a.Ve||DGa(a))},DGa=function(a,b){if(b)if(6<a.dk){a.o=a.A.concat(a.o);
a.A.length=0;var c=a.Fo-1;var d=Z6(a)}else c=b.J,d=b.ll;else c=a.Fo++,d=Z6(a);var e=a.Mq.clone();$5(e,"SID",a.u);$5(e,"RID",c);$5(e,"AID",a.qm);W6(a,e);c=new B6(a,a.u,c,a.Xl+1);c.yk=a.em;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Ve=c;bGa(c,e,d)},W6=function(a,b){if(a.ne){var c=a.ne.jA();
c&&g.Ib(c,function(d,e){$5(b,e,d)})}},Z6=function(a){var b=Math.min(a.o.length,1E3),c=["count="+b];
if(6<a.dk&&0<b){var d=a.o[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.o[e].o,h=a.o[e].map;f=6>=a.dk?e:f-d;try{g.Ib(h,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.o.splice(0,b));
return c.join("&")},FGa=function(a){a.Zc||a.Uh||(a.F=1,a.Uh=K6((0,g.y)(a.DD,a),0),a.Il=0)},$6=function(a){if(a.Zc||a.Uh||3<=a.Il)return!1;
a.F++;a.Uh=K6((0,g.y)(a.DD,a),GGa(a,a.Il));a.Il++;return!0},O6=function(a,b,c){a.Et=c;
a.oh=b.ki;a.C||BGa(a)},Y6=function(a){null!=a.ik&&(g.v.clearTimeout(a.ik),a.ik=null)},GGa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.ne&&(c=null);var d=(0,g.y)(a.MP,a);c||(c=new g.Wm("//www.google.com/images/cleardot.gif"),a6(c));jGa(c.toString(),1E4,d)}else F6(2);HGa(a,b)},HGa=function(a,b){a.va=0;
a.ne&&a.ne.yz(b);zGa(a);yGa(a)},zGa=function(a){a.va=0;
a.oh=-1;if(a.ne)if(0==a.A.length&&0==a.o.length)a.ne.qu();else{g.tb(a.A);var b=g.tb(a.o);a.A.length=0;a.o.length=0;a.ne.qu(b)}},N6=function(a,b,c){var d=g.dn(c);
if(""!=d.o)b&&g.Ym(d,b+"."+d.o),g.Zm(d,d.B);else{var e=window.location;d=AFa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Jn&&g.Ib(a.Jn,function(f,h){$5(d,h,f)});
$5(d,"VER",a.dk);W6(a,d);return d},K6=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},F6=function(a){b7.dispatchEvent(new vGa(b7,a))},IGa=function(){},JGa=function(){this.o=[];
this.u=[]},KGa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.B.call(this);
this.o=new g.G(this.jO,0,this);g.C(this,this.o);this.qe=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.y)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},d7=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
this.P=a;this.F=b;this.A=new g.On;this.u=new c7(this.pP,this);this.o=null;this.sd=!1;this.C=null;this.M="";this.J=this.B=0;this.H=[];this.U=c;this.S=d},LGa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Et,sessionId:a.o.u,arrayId:a.o.qm}},MGa=function(a,b){a.J=b||0;
a.u.stop();e7(a);a.o&&(3==a.o.va&&EGa(a.o),AGa(a.o));a.J=0},f7=function(a){return!!a.o&&3==a.o.va},e7=function(a){if(a.o){var b=a.S(),c=a.o.em||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.o.em=c}},NGa=function(a,b){(a.F.loungeIdToken=b)||a.u.stop()},g7=function(a){this.scheme="https";
this.port=this.domain="";this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.vd(4,a))||"";b&&(this.port=":"+b);this.domain=g.wd(a)||"";a=g.Uc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Cc(a,"10.0")&&(this.u=!1))},h7=function(a,b){var c=a.o;
a.u&&(c=a.scheme+"://"+a.domain+a.port+a.o);return g.Jd(c+b,{})},i7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ua(a.B,d,!0),onError:g.Ua(a.A,e),Gf:g.Ua(a.C,e)};c&&(a.Lb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.mq(b,a)},RGa=function(){var a=OGa;
PGa();j7.push(a);QGa(j7)},k7=function(a,b){PGa();
var c=j7,d=SGa(a,String(b));g.nb(c)?TGa(d):(QGa(c),g.Gb(c,function(e){e(d)}))},PGa=function(){j7||(j7=g.La("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",j7,void 0))},TGa=function(a){var b=(l7+1)%50;
l7=b;m7[b]=a;n7||(n7=49==b)},QGa=function(a){var b=m7;
if(b[0]){var c=l7,d=n7?c:-1;do{d=(d+1)%50;var e=b[d];g.Gb(a,function(f){f(e)})}while(d!=c);
m7=Array(50);l7=-1;n7=!1}},SGa=function(a,b){var c=(g.z()-UGa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},o7=function(a){g.N.call(this);
this.F=a;this.screens=[]},VGa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},WGa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ie(a.screens,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=VGa(a,b[d])||c;return c},XGa=function(a,b){var c=a.screens.length;
a.screens=g.Ie(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},p7=function(a,b,c,d){g.N.call(this);
this.F=a;this.C=b;this.A=c;this.B=d;this.u=0;this.o=null;this.La=NaN},r7=function(a){o7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;q7(this);this.info("Initializing with "+j6(this.screens))},YGa=function(a){if(a.screens.length){var b=g.Oc(a.screens,function(d){return d.id}),c=h7(a.u,"/pairing/get_lounge_token_batch");
i7(a.u,c,{screen_ids:b.join(",")},(0,g.y)(a.ZH,a),(0,g.y)(a.YH,a))}},q7=function(a){var b=GFa(MFa());
b=g.Ie(b,function(c){return!c.uuid});
return WGa(a,b)},s7=function(a,b){OFa(g.Oc(a.screens,EFa));
b&&NFa()},u7=function(a,b){g.N.call(this);
this.F=b;var c=g.ot("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.lb(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;t7("Initialized with "+g.Bj(this.o))},ZGa=function(a,b,c){var d=h7(a.C,"/pairing/get_screen_availability");
i7(a.C,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},v7=function(a,b){a:if(c6(b)!=c6(a.o))var c=!1;
else{c=g.Pb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(t7("Updated online screens: "+g.Bj(a.o)),a.o=b,a.R("screenChange"));$Ga(a)},w7=function(a){isNaN(a.A)||g.Go(a.A);
a.A=g.Eo((0,g.y)(a.hx,a),0<a.B&&a.B<g.z()?2E4:1E4)},t7=function(a){k7("OnlineScreenService",a)},aHa=function(a){var b={};
g.Gb(a.F(),function(c){c.token?b[c.token]=c.id:this.Lc("Requesting availability of screen w/o lounge token.")});
return b},$Ga=function(a){a=g.Pb(g.Jb(a.o,function(b){return b}));
g.Cb(a);a.length?g.nt("yt-remote-online-screen-ids",a.join(","),60):g.pt("yt-remote-online-screen-ids")},x7=function(a){o7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};bHa(this)},dHa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var h=a.wf();if(h=(c?m6(h,c):null)||m6(h,b)){h.uuid=b;var l=y7(a,h);ZGa(a.o,l,function(m){e(m?l:null)})}else c?cHa(a,c,(0,g.y)(function(m){var n=y7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));ZGa(this.o,n,function(p){e(p?n:null)})},a),f):e(null)},eHa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},cHa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Lb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.mq(h7(a.C,"/pairing/get_lounge_token_batch"),e)},fHa=function(a){a.screens=a.u.wf();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.screens))},bHa=function(a){z7(a);
a.u=new r7(a.C);a.u.subscribe("screenChange",(0,g.y)(a.gI,a));fHa(a);a.A=GFa(g.ot("yt-remote-automatic-screen-cache")||[]);z7(a);a.info("Initializing automatic screens: "+j6(a.A));a.o=new u7(a.C,(0,g.y)(a.wf,a,!0));a.o.subscribe("screenChange",(0,g.y)(function(){this.R("onlineScreenChange")},a))},y7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.nt("yt-remote-automatic-screen-cache",g.Oc(a.A,EFa)));z7(a);a.B[b.uuid]=b.id;g.nt("yt-remote-device-id-map",a.B,31536E3);return b},z7=function(a){a.B=g.ot("yt-remote-device-id-map")||{}},A7=function(a,b,c){g.N.call(this);
this.U=c;this.J=a;this.o=b;this.H=null},B7=function(a,b){k7(a.U,b)},C7=function(a,b){A7.call(this,a,b,"CastSession");
this.u=null;this.A=0;this.C=(0,g.y)(this.wQ,this);this.B=(0,g.y)(this.KO,this);this.A=g.Eo((0,g.y)(function(){gHa(this,null)},this),12E4)},hHa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Bj(void 0));
var b={type:"getMdxSessionStatus"};a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ma,(0,g.y)(function(){B7(this,"Failed to send message: getMdxSessionStatus.")},a)):B7(a,"Sending yt message without session: "+g.Bj(b))},gHa=function(a,b){g.Go(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.y)(a.Ds,a),d=(0,g.y)(a.Ff,a);a.BA(b,c,d,5)}}else a.Ff(Error("Waiting for session status timed out."))},D7=function(a,b,c){A7.call(this,a,b,"DialSession");
this.A=this.F=null;this.M="";this.W=c;this.P=null;this.C=g.Ma;this.B=NaN;this.S=(0,g.y)(this.zQ,this);this.u=g.Ma},iHa=function(a){a.u=a.J.MF(a.M,a.o.label,a.o.friendlyName,(0,g.y)(function(b){this.u=g.Ma;
this.Ds(b)},a),(0,g.y)(function(b){this.u=g.Ma;
this.Ff(b)},a))},jHa=function(a){var b={};
b.pairingCode=a.M;b.theme=a.W;QFa()&&(b.env_useStageMdx=1);return g.Hd(b)},E7=function(a,b){A7.call(this,a,b,"ManualSession");
this.u=g.Eo((0,g.y)(this.rm,this,null),150)},F7=function(a,b,c,d){g.N.call(this);
this.u=a;this.H=b||"233637DE";this.F=c||"cl";this.J=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.y)(this.AN,this)},kHa=function(a,b){return b?g.gb(a.A,function(c){return h6(b,c.label)},a):null},G7=function(a){k7("Controller",a)},OGa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},H7=function(a){return a.C||!!a.A.length||!!a.o},I7=function(a,b,c){b!=a.o&&(g.ag(a.o),(a.o=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.o):a.R("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.y)(a.BD,a,b)),b.getScreen()?a.R("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.rm(null)):a.R("yt-remote-cast2-session-change",null))},lHa=function(a){var b=a.u.LF(),c=a.o&&a.o.o;
a=g.Oc(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=kHa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},rHa=function(a,b,c,d,e,f,h){mHa()?nHa(b,e,f,h)&&(K7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?oHa(a,c):(window.__onGCastApiAvailable=function(l,m){l?oHa(a,c):(L7("Failed to load cast API: "+m),M7(!1),K7(!1),g.pt("yt-remote-cast-available"),g.pt("yt-remote-cast-receiver"),pHa(),c(!1))},d?g.Qo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?XFa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(WFa(),t6(qHa.map(UFa))))):J7("Cannot initialize because not running Chrome")},pHa=function(){J7("dispose");
var a=N7();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);sHa(!1);g.Mo(O7);O7.length=0},P7=function(){return!!g.ot("yt-remote-cast-installed")},tHa=function(){var a=g.ot("yt-remote-cast-receiver");
return a?a.friendlyName:null},uHa=function(){J7("clearCurrentReceiver");
g.pt("yt-remote-cast-receiver")},vHa=function(){return P7()?N7()?N7().getCastSession():(L7("getCastSelector: Cast is not initialized."),null):(L7("getCastSelector: Cast API is not installed!"),null)},R7=function(){P7()?N7()?Q7()?(J7("Requesting cast selector."),N7().requestSession()):(J7("Wait for cast API to be ready to request the session."),O7.push(g.Lo("yt-remote-cast2-api-ready",R7))):L7("requestCastSelector: Cast is not initialized."):L7("requestCastSelector: Cast API is not installed!")},S7=
function(a,b){Q7()?N7().setConnectedScreenStatus(a,b):L7("setConnectedScreenStatus called before ready.")},mHa=function(){var a=0<=g.Uc.search(/ (CrMo|Chrome|CriOS)\//);
return g.nB||a},wHa=function(a,b){N7().init(a,b)},nHa=function(a,b,c,d){var e=!1;
N7()||(a=new F7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.nt("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){J7("onReceiverSelected: "+f.friendlyName);
g.nt("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){J7("onReceiverResumed: "+f.friendlyName);
g.nt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){J7("onSessionChange: "+i6(f));
f||g.pt("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
J7("cloudview.createSingleton_: "+e);return e},N7=function(){return g.La("yt.mdx.remote.cloudview.instance_")},oHa=function(a,b){M7(!0);
K7(!1);wHa(a,function(c){c?(sHa(!0),g.No("yt-remote-cast2-api-ready")):(L7("Failed to initialize cast API."),M7(!1),g.pt("yt-remote-cast-available"),g.pt("yt-remote-cast-receiver"),pHa());b(c)})},J7=function(a){k7("cloudview",a)},L7=function(a){k7("cloudview",a)},M7=function(a){J7("setCastInstalled_ "+a);
g.nt("yt-remote-cast-installed",a)},Q7=function(){return!!g.La("yt.mdx.remote.cloudview.apiReady_")},sHa=function(a){J7("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},K7=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},T7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.H=0;this.o=null;this.hasNext=this.ph=!1;this.M=this.J=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},U7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.ph=!1;a.hasNext=!1;a.H=0;a.F=g.z();a.C=0;a.u=0;a.J=0;a.M=0;a.B=NaN;a.A=!1},V7=function(a){return a.ub()?(g.z()-a.F)/1E3:0},W7=function(a,b){a.H=b;
a.F=g.z()},X7=function(a){switch(a.playerState){case 1:case 1081:return(g.z()-a.F)/1E3+a.H;
case -1E3:return 0}return a.H},Y7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&U7(a)},Z7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Zb(a.o);b.hasPrevious=a.ph;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.J;b.loadedTime=a.M;b.liveIngestionTime=a.B;return b},a8=function(a,b){g.N.call(this);
this.va=0;this.A=a;this.C=[];this.B=new JGa;this.u=this.o=null;this.J=(0,g.y)(this.ML,this);this.F=(0,g.y)(this.Jo,this);this.H=(0,g.y)(this.LL,this);this.M=(0,g.y)(this.UL,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.my,this),xHa(this))):c=3;0!=c&&(b?this.my(c):g.Eo((0,g.y)(function(){this.my(c)},this),0));
var d=vHa();d&&$7(this,d);this.subscribe("yt-remote-cast2-session-change",this.M)},b8=function(a){return new T7(a.A.getPlayerContextData())},xHa=function(a){g.Gb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Ua(this.wN,b),this))},a)},yHa=function(a){g.Gb(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},c8=function(a,b){var c=a.B;
50>c.o.length+c.u.length&&a.B.u.push(b)},e8=function(a,b,c){var d=b8(a);
W7(d,c);-1E3!=d.playerState&&(d.playerState=b);d8(a,d)},f8=function(a,b,c){a.A.sendMessage(b,c)},d8=function(a,b){yHa(a);
a.A.setPlayerContextData(Z7(b));xHa(a)},$7=function(a,b){a.u&&(a.u.removeUpdateListener(a.J),a.u.removeMediaListener(a.F),a.Jo(null));
a.u=b;a.u&&(k7("CP","Setting cast session: "+a.u.sessionId),a.u.addUpdateListener(a.J),a.u.addMediaListener(a.F),a.u.media.length&&a.Jo(a.u.media[0]))},zHa=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=b8(a);b.contentId!=d.videoId&&k7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;W7(d,a.o.getEstimatedTime());d8(a,d)}else k7("CP","No cast media video. Ignoring state update.")},g8=function(a,b,c){return(0,g.y)(function(d){this.Lc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Lc("Retrying "+b+" using MDx browser channel."),f8(this,b,c))},a)},h8=function(a,b,c){g.N.call(this);
this.C=NaN;this.S=!1;this.J=this.H=this.M=this.P=NaN;this.U=[];this.B=this.F=this.A=this.rb=this.o=null;this.X=a;this.U.push(g.ap(window,"beforeunload",(0,g.y)(this.SH,this)));this.u=[];this.rb=new T7;this.W=b.id;this.o=AHa(this,c);this.o.subscribe("handlerOpened",this.QL,this);this.o.subscribe("handlerClosed",this.NL,this);this.o.subscribe("handlerError",this.OL,this);this.o.subscribe("handlerMessage",this.PL,this);NGa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.rb.videoId;
g.qt()&&g.nt("yt-remote-session-video-id",d)},this)},i8=function(a){k7("conn",a)},AHa=function(a,b){return new d7(h7(a.X,"/bc"),b,!1,function(){return a.IF()})},j8=function(a,b){a.R("proxyStateChange",b)},BHa=function(a){a.C=g.Eo((0,g.y)(function(){i8("Connecting timeout");
this.Sl(1)},a),2E4)},k8=function(a){g.Go(a.C);
a.C=NaN},l8=function(a){g.Go(a.P);
a.P=NaN},CHa=function(a){m8(a);
a.M=g.Eo((0,g.y)(function(){n8(this,"getNowPlaying")},a),2E4)},m8=function(a){g.Go(a.M);
a.M=NaN},EHa=function(a,b){b&&(k8(a),l8(a));
b==(f7(a.o)&&isNaN(a.C))?b&&(j8(a,1),n8(a,"getSubtitlesTrack")):b?(a.zA()&&a.rb.reset(),j8(a,1),n8(a,"getNowPlaying"),DHa(a)):a.Sl(1)},FHa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.rb.videoId&&(g.Vb(b.params)?a.rb.o=null:a.rb.o=b.params,a.R("remotePlayerChange"))},GHa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.rb.listId=b.params.listId||a.rb.listId;Y7(a.rb,c,d);a.R("remoteQueueChange")},IHa=function(a,b){b.params=b.params||{};
GHa(a,b);HHa(a,b);a.R("autoplayDismissed")},HHa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
W7(a.rb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.rb.playerState&&(c=-1E3);a.rb.playerState=c;c=Number(b.params.loadedTime);a.rb.M=isNaN(c)?0:c;c=Number(b.params.duration);a.rb.J=isNaN(c)?0:c;c=a.rb;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.rb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.rb.playerState?CHa(a):m8(a);a.R("remotePlayerChange")},JHa=function(a,b){if(-1E3!=
a.rb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.rb.playerState=c;c=parseInt(b.params.currentTime,10);W7(a.rb,isNaN(c)?0:c);a.R("remotePlayerChange")}},KHa=function(a,b){var c="true"==b.params.muted;
a.rb.volume=parseInt(b.params.volume,10);a.rb.muted=c;a.R("remotePlayerChange")},LHa=function(a,b){a.F=b.params.videoId;
a.R("nowAutoplaying",parseInt(b.params.timeout,10))},MHa=function(a,b){var c="true"==b.params.hasNext;
a.rb.ph="true"==b.params.hasPrevious;a.rb.hasNext=c;a.R("previousNextChange")},DHa=function(a){g.Go(a.J);
a.J=g.Eo((0,g.y)(a.Sl,a,1),864E5)},n8=function(a,b,c){c?i8("Sending: action="+b+", params="+g.Bj(c)):i8("Sending: action="+b);
a.o.sendMessage(b,c)},o8=function(a){o7.call(this,"ScreenServiceProxy");
this.pe=a;this.o=[];this.o.push(this.pe.$_s("screenChange",(0,g.y)(this.uQ,this)));this.o.push(this.pe.$_s("onlineScreenChange",(0,g.y)(this.cN,this)))},RHa=function(a,b){b=g.K("MDX_CONFIG")||b;
IFa();q6();p8||(p8=new g7(b?b.loungeApiHost:void 0),QFa()&&(p8.o="/api/loungedev"));q8||(q8=g.La("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",q8,void 0));NHa();var c=r8();if(!c){var d=new x7(p8);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=r8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);rHa(a,d,function(m){m?s8()&&S7(s8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){e6("yt-remote-receiver-availability-change")})},
e,f,h,l)}b&&!g.La("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),t8("Initializing: "+g.Bj(b)),u8.push(g.Lo("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),u8.push(g.Lo("yt-remote-cast2-receiver-selected",function(){v8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),u8.push(g.Lo("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),u8.push(g.Lo("yt-remote-cast2-session-change",OHa)),u8.push(g.Lo("yt-remote-connection-change",function(m){m?S7(s8(),"YouTube TV"):w8()||(S7(null,null),uHa())})),e=x8(),b.isAuto&&(e.id+="#dial"),g.ro("desktop_enable_autoplay")&&(e.capabilities=["atp"]),e.name=b.device,e.app=b.app,(h=b.theme)&&(e.theme=h),t8(" -- with channel params: "+
g.Bj(e)),PHa(e),c.start(),s8()||QHa())},THa=function(){var a=SHa();
P7()&&g.ot("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},SHa=function(){var a=r8().pe.$_gos();
var b=y8();b&&z8()&&(l6(a,b)||a.push(b));return HFa(a)},A8=function(){var a=UHa();
!a&&P7()&&tHa()&&(a={key:"cast-selector-receiver",name:tHa()});return a},UHa=function(){var a=SHa(),b=y8();
b||(b=w8());return g.gb(a,function(c){return b&&h6(b,c.key)?!0:!1})},y8=function(){var a=s8();
if(!a)return null;var b=r8().wf();return m6(b,a)},OHa=function(a){t8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=y8();b&&b.id==a.id?S7(b.id,"YouTube TV"):(b&&B8(),C8(a,1))}else z8()&&B8()},B8=function(){Q7()?N7().stopSession():L7("stopSession called before API ready.");
var a=z8();a&&(a.disconnect(1),D8(null))},E8=function(){var a=z8();
return!!a&&3!=a.getProxyState()},t8=function(a){k7("remote",a)},r8=function(){if(!F8){var a=g.La("yt.mdx.remote.screenService_");
F8=a?new o8(a):null}return F8},s8=function(){return g.La("yt.mdx.remote.currentScreenId_")},VHa=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},WHa=function(){return g.La("yt.mdx.remote.connectData_")},v8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},z8=function(){return g.La("yt.mdx.remote.connection_")},D8=function(a){var b=z8();
v8(null);a||VHa("");g.Ha("yt.mdx.remote.connection_",a,void 0);q8&&(g.Gb(q8,function(c){c(a)}),q8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},w8=function(){var a=g.qt();
if(!a)return null;var b=r8();if(!b)return null;b=b.wf();return m6(b,a)},C8=function(a,b){s8();
y8()&&y8();if(G8)H8=a;else{VHa(a.id);var c=new h8(p8,a,x8());c.connect(b,WHa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){z8()&&(z8(),D8(null))});
D8(c)}},QHa=function(){var a=w8();
a?(t8("Resume connection to: "+i6(a)),C8(a,0)):(r6(),uHa(),t8("Skipping connecting because no session screen found."))},NHa=function(){var a=x8();
if(g.Vb(a)){a=p6();var b=g.ot("yt-remote-session-name")||"",c=g.ot("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},x8=function(){return g.La("yt.mdx.remote.channelParams_")||{}},PHa=function(a){a?(g.nt("yt-remote-session-app",a.app),g.nt("yt-remote-session-name",a.name)):(g.pt("yt-remote-session-app"),g.pt("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.B.call(this);
var d=this;this.module=a;this.G=b;this.eb=c;this.events=new g.ns(this);this.M=this.events.K(this.G,"onVolumeChange",this.dD);this.B=!1;this.suggestion=null;this.C=new g.PK(64);this.o=new g.G(this.QE,500,this);this.u=new g.G(this.RE,1E3,this);this.H=new v6(this.ZP,0,this);this.A={};this.J=new g.G(this.tF,1E3,this);this.F=new w6(this.seekTo,1E3,this);this.P=g.Ma;g.C(this,this.events);this.events.K(b,"onCaptionsTrackListChanged",this.DM);this.events.K(b,"captionschanged",this.KL);this.events.K(b,"captionssettingschanged",
this.UE);this.events.K(b,"videoplayerreset",this.Es);this.events.K(b,"mdxautoplaycancel",function(){d.eb.Qz()});
a=this.eb;a.ea();a.subscribe("proxyStateChange",this.wD,this);a.subscribe("remotePlayerChange",this.Po,this);a.subscribe("remoteQueueChange",this.Es,this);a.subscribe("previousNextChange",this.sD,this);a.subscribe("nowAutoplaying",this.nD,this);a.subscribe("autoplayDismissed",this.NC,this);g.C(this,this.o);g.C(this,this.u);g.C(this,this.H);g.C(this,this.J);g.C(this,this.F);this.UE();this.Es();this.Po()},XHa=function(a){a.wc(0);
a.o.stop();a.qd(new g.PK(64))},K8=function(a,b){if(J8(a)&&!a.B){var c=null;
b&&(c={style:a.G.getSubtitlesUserSettings()},g.ac(c,b));a.eb.JF(a.G.getVideoData(1).videoId,c);a.A=b8(a.eb).o}},L8=function(a,b){var c=a.G.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.G.getVideoData(1);a.eb.playVideo(c.videoId,b,d,e,c.playerParams,c.Sf,uFa(c));a.qd(new g.PK(1))},YHa=function(a,b){if(b){var c=a.G.getOption("captions","tracklist",{YA:1});
c&&c.length?(a.G.setOption("captions","track",b),a.B=!1):(a.G.loadModule("captions"),a.B=!0)}else a.G.setOption("captions","track",{})},J8=function(a){return b8(a.eb).videoId===a.G.getVideoData(1).videoId},M8=function(){g.V.call(this,{D:"div",
I:"ytp-mdx-manual-pairing-popup-dialog",O:{role:"dialog"},L:[{D:"div",I:"ytp-mdx-manual-pairing-popup-dialog-inner-content",L:[{D:"div",I:"ytp-mdx-manual-pairing-popup-title",T:"Connecting to your TV on web using a code will be going away soon"},{D:"div",I:"ytp-mdx-manual-pairing-popup-buttons",L:[{D:"button",da:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],T:"Learn more"},{D:"button",da:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],T:"OK"}]}]}]});this.o=new g.yN(this,250);this.learnMoreButton=
this.ba("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ba("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.o);this.K(this.learnMoreButton,"click",this.u);this.K(this.okButton,"click",this.A)},N8=function(){g.V.call(this,{D:"div",
I:"ytp-mdx-popup-dialog",O:{role:"dialog"},L:[{D:"div",I:"ytp-mdx-popup-dialog-inner-content",L:[{D:"div",I:"ytp-mdx-popup-title",T:"You're signed out"},{D:"div",I:"ytp-mdx-popup-description",T:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",I:"ytp-mdx-privacy-popup-buttons",L:[{D:"button",da:["ytp-button","ytp-mdx-privacy-popup-cancel"],T:"Cancel"},{D:"button",da:["ytp-button","ytp-mdx-privacy-popup-confirm"],
T:"Confirm"}]}]}]});this.o=new g.yN(this,250);this.cancelButton=this.ba("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ba("ytp-mdx-privacy-popup-confirm");g.C(this,this.o);this.K(this.cancelButton,"click",this.u);this.K(this.confirmButton,"click",this.A)},O8=function(a){g.V.call(this,{D:"div",
I:"ytp-remote",L:[{D:"div",I:"ytp-remote-display-status",L:[{D:"div",I:"ytp-remote-display-status-icon",L:[g.SM()]},{D:"div",I:"ytp-remote-display-status-text",T:"{{statustext}}"}]}]});this.api=a;this.o=new g.yN(this,250);g.C(this,this.o);this.K(a,"presentingplayerstatechange",this.u);ZHa(this,g.mI(a))},ZHa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.S(b,128)?g.dJ("Error on $RECEIVER_NAME",c):b.ub()||g.S(b,4)?g.dJ("Playing on $RECEIVER_NAME",c):g.dJ("Connected to $RECEIVER_NAME",c);a.ka("statustext",c);a.o.show()}else a.o.hide()},P8=function(a,b){g.OZ.call(this,"Play on",0,a,b);
this.G=a;this.Hj={};this.K(a,"onMdxReceiversChange",this.B);this.K(a,"presentingplayerstatechange",this.B);this.B()},Q8=function(a){g.FS.call(this,a);
this.Dg={key:k6(),name:"This computer"};this.eh=null;this.subscriptions=[];this.Sw=this.eb=null;this.Hj=[this.Dg];this.Wi=this.Dg;this.sc=new g.PK(64);this.sB=0;this.Ld=-1;this.tm=null;this.So=this.Ir=!1;this.kl=this.Mm=null;if(!g.lC(this.player.N())){a=this.player;var b=g.OW(a);b&&(b=b.uk())&&(b=new P8(a,b),g.C(this,b));b=new O8(a);g.C(this,b);g.OO(a,b.element,4);this.Mm=new N8;g.C(this,this.Mm);g.OO(a,this.Mm.element,4);g.Q(this.player.N().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.tm=new M8,g.C(this,this.tm),g.OO(a,this.tm.element,4));this.So=!!w8();this.Ir=!!g.ot("yt-remote-manual-pairing-warning-shown")}},R8=function(a){a.kl&&(a.player.removeEventListener("presentingplayerstatechange",a.kl),a.kl=null)},$Ha=function(a,b,c){a.sc=c;
a.player.R("presentingplayerstatechange",new g.uI(c,b))},aIa=function(a,b,c){var d=!1;
1===b?d=!a.So:2===b&&(d=!a.Ir);d&&g.wI(c,8)&&(a.player.pauseVideo(),R8(a))},S8=function(a,b){if(b.key!==a.Wi.key)if(b.key===a.Dg.key)B8();
else{if(a.tm&&!a.Ir&&b!==a.Dg&&"cast-selector-receiver"!==b.key&&g.uC(a.player.N()))bIa(a);else{var c;(c=!g.Q(a.player.N().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.K("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.K("SESSION_INDEX")&&!g.K("LOGGED_IN")))||a.So||!a.Mm);(c?0:g.uC(a.player.N())||g.yC(a.player.N()))&&cIa(a)}a.Wi=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.Q(a.player.N().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Ba(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Sf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=uFa(c))&&(d.locationInfo=c);c=d}t8("Connecting to: "+g.Bj(b));"cast-selector-receiver"==b.key?(v8(c||null),c=
c||null,Q7()?N7().setLaunchParams(c):L7("setLaunchParams called before ready.")):!c&&E8()&&s8()==b.key?e6("yt-remote-connection-change",!0):(B8(),v8(c||null),c=r8().wf(),(c=m6(c,b.key))&&C8(c,1))}},cIa=function(a){g.mI(a.player).ub()?a.player.pauseVideo():(a.kl=function(b){aIa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.kl));
a.Mm&&a.Mm.dc();z8()||(G8=!0)},bIa=function(a){g.mI(a.player).ub()?a.player.pauseVideo():(a.kl=function(b){aIa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.kl));
a.tm&&a.tm.dc();z8()||(G8=!0)},gGa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},J6={"'":"\\'"},dIa={},DFa={bR:"atp",RT:"ska",BT:"que",QS:"mus",QT:"sus",YR:"dsp",IT:"seq"},s6,o6="",VFa=RFa("loadCastFramework")||RFa("loadCastApplicationFramework"),qHa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Xa(v6,g.B);g.k=v6.prototype;g.k.PH=function(a){this.B=arguments;this.o=!1;this.La?this.A=g.z()+this.qe:this.La=g.Rm(this.C,this.qe)};
g.k.stop=function(){this.La&&(g.v.clearTimeout(this.La),this.La=null);this.A=null;this.o=!1;this.B=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.k.V=function(){this.stop();v6.Pc.V.call(this)};
g.k.QH=function(){this.A?(this.La=g.Rm(this.C,this.A-g.z()),this.A=null):(this.La=null,this.u?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};g.u(w6,g.B);g.k=w6.prototype;g.k.IB=function(a){this.A=arguments;this.La||this.u?this.o=!0:x6(this)};
g.k.stop=function(){this.La&&(g.v.clearTimeout(this.La),this.La=null,this.o=!1,this.A=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.o||this.La||(this.o=!1,x6(this))};
g.k.V=function(){g.B.prototype.V.call(this);this.stop()};z6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
z6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};A6.prototype.o=null;A6.prototype.getOptions=function(){var a;(a=this.o)||(a={},ZFa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var T8;g.Xa(YFa,A6);T8=new YFa;g.k=B6.prototype;g.k.yk=null;g.k.Sg=!1;g.k.cn=null;g.k.jy=null;g.k.Qm=null;g.k.Wm=null;g.k.Ri=null;g.k.Ij=null;g.k.ll=null;g.k.Gd=null;g.k.Fp=0;g.k.Xg=null;g.k.Gt=null;g.k.gj=null;g.k.Wn=-1;g.k.GE=!0;g.k.ck=!1;g.k.tv=0;g.k.Ns=null;var dGa={},E6={};g.k=B6.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.dP=function(a){a=a.target;var b=this.Ns;b&&3==S6(a)?b.IB():this.FF(a)};
g.k.FF=function(a){try{if(a==this.Gd)a:{var b=S6(this.Gd),c=this.Gd.F,d=this.Gd.getStatus();if(g.we&&!g.Yd(10)||g.ye&&!g.Xd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.ng&&!U6(this.Gd))break a;this.ck||4!=b||7==c||(8==c||0>=d?this.o.Jg(3):this.o.Jg(2));L6(this);var e=this.Gd.getStatus();this.Wn=e;var f=U6(this.Gd);(this.Sg=200==e)?(4==b&&H6(this),this.F?(fGa(this,b,f),g.ng&&this.Sg&&3==b&&(this.B.ia(this.A,"tick",this.XO),this.A.start())):G6(this,f),this.Sg&&!this.ck&&(4==b?this.o.fr(this):(this.Sg=
!1,D6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.gj=3,F6(13)):(this.gj=0,F6(14)),H6(this),I6(this))}}catch(h){this.Gd&&U6(this.Gd)}finally{}};
g.k.XO=function(){var a=S6(this.Gd),b=U6(this.Gd);this.Fp<b.length&&(L6(this),fGa(this,a,b),this.Sg&&4!=a&&D6(this))};
g.k.qO=function(a){K6((0,g.y)(this.pO,this,a),0)};
g.k.pO=function(a){this.ck||(L6(this),G6(this,a),D6(this))};
g.k.FD=function(a){K6((0,g.y)(this.oO,this,a),0)};
g.k.oO=function(a){this.ck||(H6(this),this.Sg=a,this.o.fr(this),this.o.Jg(4))};
g.k.cancel=function(){this.ck=!0;H6(this)};
g.k.CO=function(){this.cn=null;var a=g.z();0<=a-this.jy?(2!=this.Wm&&this.o.Jg(3),H6(this),this.gj=2,F6(18),I6(this)):iGa(this,this.jy-a)};
g.k.getLastError=function(){return this.gj};g.k=lGa.prototype;g.k.ov=null;g.k.ff=null;g.k.Os=!1;g.k.JA=null;g.k.Kq=null;g.k.Vv=null;g.k.qv=null;g.k.va=null;g.k.ki=-1;g.k.Vn=null;g.k.qn=null;g.k.connect=function(a){this.qv=a;a=N6(this.o,null,this.qv);F6(3);this.JA=g.z();var b=this.o.H;null!=b?(this.Vn=b[0],(this.qn=b[1])?(this.va=1,mGa(this)):(this.va=2,P6(this))):(b6(a,"MODE","init"),this.ff=new B6(this,void 0,void 0,void 0),this.ff.yk=this.ov,C6(this.ff,a,!1,null,!0),this.va=0)};
g.k.OG=function(a){if(a)this.va=2,P6(this);else{F6(4);var b=this.o;b.oh=b.Ui.ki;a7(b,9)}a&&this.Jg(2)};
g.k.Du=function(a){return this.o.Du(a)};
g.k.abort=function(){this.ff&&(this.ff.cancel(),this.ff=null);this.ki=-1};
g.k.IA=function(){return!1};
g.k.xD=function(a,b){this.ki=a.Wn;if(0==this.va)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.oh=this.ki;a7(c,2);return}this.Vn=c[0];this.qn=c[1]}else c=this.o,c.oh=this.ki,a7(c,2);else if(2==this.va)if(this.Os)F6(7),this.Vv=g.z();else if("11111"==b){if(F6(6),this.Os=!0,this.Kq=g.z(),c=this.Kq-this.JA,!g.we||g.Yd(10)||500>c)this.ki=200,this.ff.cancel(),F6(12),O6(this.o,this,!0)}else F6(8),this.Kq=this.Vv=g.z(),this.Os=!1};
g.k.fr=function(){this.ki=this.ff.Wn;if(this.ff.Sg)0==this.va?this.qn?(this.va=1,mGa(this)):(this.va=2,P6(this)):2==this.va&&((!g.we||g.Yd(10)?!this.Os:200>this.Vv-this.Kq)?(F6(11),O6(this.o,this,!1)):(F6(12),O6(this.o,this,!0)));else{0==this.va?F6(9):2==this.va&&F6(10);var a=this.o;this.ff.getLastError();a.oh=this.ki;a7(a,2)}};
g.k.np=function(){return this.o.np()};
g.k.isActive=function(){return this.o.isActive()};
g.k.Jg=function(a){this.o.Jg(a)};g.Xa(Q6,g.fm);var rGa=/^https?$/i,eIa=["POST","PUT"];g.k=Q6.prototype;
g.k.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.M+"; newUri="+a);b=b?b.toUpperCase():"GET";this.M=a;this.B="";this.F=0;this.na=b;this.X=!1;this.A=!0;this.o=this.W?$Fa(this.W):$Fa(T8);this.U=this.W?this.W.getOptions():T8.getOptions();this.o.onreadystatechange=(0,g.y)(this.tD,this);try{d6(T6(this,"Opening Xhr")),this.ca=!0,this.o.open(b,String(a),!0),this.ca=!1}catch(f){d6(T6(this,"Error opening Xhr: "+f.message));qGa(this,f);return}a=
c||"";var e=this.headers.clone();d&&zFa(d,function(f,h){e.set(h,f)});
d=g.gb(e.Qf(),oGa);c=g.v.FormData&&a instanceof g.v.FormData;!g.lb(eIa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.o.setRequestHeader(h,f)},this);
this.oa&&(this.o.responseType=this.oa);"withCredentials"in this.o&&this.o.withCredentials!==this.aa&&(this.o.withCredentials=this.aa);try{tGa(this),0<this.H&&(this.S=nGa(this.o),d6(T6(this,"Will abort after "+this.H+"ms if incomplete, xhr2 "+this.S)),this.S?(this.o.timeout=this.H,this.o.ontimeout=(0,g.y)(this.KA,this)):this.P=g.Rm(this.KA,this.H,this)),d6(T6(this,"Sending request")),this.J=!0,this.o.send(a),this.J=!1}catch(f){d6(T6(this,"Send error: "+f.message)),qGa(this,f)}};
g.k.KA=function(){"undefined"!=typeof g.d1&&this.o&&(this.B="Timed out after "+this.H+"ms, aborting",this.F=8,T6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.o&&this.A&&(T6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.F=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),R6(this))};
g.k.V=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),R6(this,!0));Q6.Pc.V.call(this)};
g.k.tD=function(){this.ea()||(this.ca||this.J||this.C?sGa(this):this.zN())};
g.k.zN=function(){sGa(this)};
g.k.isActive=function(){return!!this.o};
g.k.getStatus=function(){try{return 2<S6(this)?this.o.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.k=V6.prototype;g.k.em=null;g.k.Jn=null;g.k.Ve=null;g.k.Zc=null;g.k.lv=null;g.k.Mq=null;g.k.nz=null;g.k.er=null;g.k.Fo=0;g.k.aL=0;g.k.ne=null;g.k.Yi=null;g.k.Uh=null;g.k.ik=null;g.k.Ui=null;g.k.Et=null;g.k.qm=-1;g.k.rB=-1;g.k.oh=-1;g.k.Xl=0;g.k.Il=0;g.k.dk=8;var b7=new g.fm;g.Xa(vGa,g.Jl);g.Xa(wGa,g.Jl);g.Xa(xGa,g.Jl);g.k=V6.prototype;g.k.connect=function(a,b,c,d,e){F6(0);this.lv=b;this.Jn=c||{};d&&void 0!==e&&(this.Jn.OSID=d,this.Jn.OAID=e);this.C?(K6((0,g.y)(this.Ez,this,a),100),BGa(this)):this.Ez(a)};
g.k.Ez=function(a){this.Ui=new lGa(this);this.Ui.ov=this.em;this.Ui.u=this.B;this.Ui.connect(a)};
g.k.IA=function(){return 0==this.va};
g.k.ED=function(a){this.Yi=null;EGa(this,a)};
g.k.DD=function(){this.Uh=null;this.Zc=new B6(this,this.u,"rpc",this.F);this.Zc.yk=this.em;this.Zc.tv=0;var a=this.nz.clone();$5(a,"RID","rpc");$5(a,"SID",this.u);$5(a,"CI",this.Et?"0":"1");$5(a,"AID",this.qm);W6(this,a);if(!g.we||g.Yd(10))$5(a,"TYPE","xmlhttp"),C6(this.Zc,a,!0,this.er,!1);else{$5(a,"TYPE","html");var b=this.Zc,c=!!this.er;b.Wm=3;b.Ri=a6(a.clone());hGa(b,c)}};
g.k.xD=function(a,b){if(0!=this.va&&(this.Zc==a||this.Ve==a))if(this.oh=a.Wn,this.Ve==a&&3==this.va)if(7<this.dk){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Uh){if(this.Zc)if(this.Zc.Qm+3E3<this.Ve.Qm)Y6(this),this.Zc.cancel(),this.Zc=null;else break a;$6(this);F6(19)}}else this.rB=c[1],0<this.rB-this.qm&&37500>c[2]&&this.Et&&0==this.Il&&!this.ik&&(this.ik=K6((0,g.y)(this.EL,this),6E3));else a7(this,11)}else b!=dIa.yR.o&&a7(this,11);else if(this.Zc==
a&&Y6(this),!g.rc(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.qm=e[0];e=e[1];2==this.va?"c"==e[0]?(this.u=e[1],this.er=e[2],e=e[3],null!=e?this.dk=e:this.dk=6,this.va=3,this.ne&&this.ne.Az(),this.nz=N6(this,this.np()?this.er:null,this.lv),FGa(this)):"stop"==e[0]&&a7(this,7):3==this.va&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.ne&&this.ne.zz(e),this.Il=0)}}};
g.k.EL=function(){null!=this.ik&&(this.ik=null,this.Zc.cancel(),this.Zc=null,$6(this),F6(20))};
g.k.fr=function(a){if(this.Zc==a){Y6(this);this.Zc=null;var b=2}else if(this.Ve==a)this.Ve=null,b=1;else return;this.oh=a.Wn;if(0!=this.va)if(a.Sg)1==b?(b7.dispatchEvent(new wGa(b7,a.ll?a.ll.length:0,g.z()-a.Qm,this.Xl)),X6(this),this.A.length=0):FGa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.oh)){if(d=1==b)this.Ve||this.Yi||1==this.va||2<=this.Xl?d=!1:(this.Yi=K6((0,g.y)(this.ED,this,a),GGa(this,this.Xl)),this.Xl++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,
5);break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.k.mH=function(a){if(!g.lb(arguments,this.va))throw Error("Unexpected channel state: "+this.va);};
g.k.MP=function(a){a?F6(2):(F6(1),HGa(this,8))};
g.k.Du=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new Q6;a.aa=!1;return a};
g.k.isActive=function(){return!!this.ne&&this.ne.isActive(this)};
g.k.Jg=function(a){b7.dispatchEvent(new xGa(b7,a))};
g.k.np=function(){return!(!g.we||g.Yd(10))};
g.k=IGa.prototype;g.k.Az=function(){};
g.k.zz=function(){};
g.k.yz=function(){};
g.k.qu=function(){};
g.k.jA=function(){return{}};
g.k.isActive=function(){return!0};g.k=JGa.prototype;g.k.isEmpty=function(){return g.nb(this.o)&&g.nb(this.u)};
g.k.clear=function(){this.o=[];this.u=[]};
g.k.contains=function(a){return g.lb(this.o,a)||g.lb(this.u,a)};
g.k.remove=function(a){var b=this.o;var c=(0,g.uza)(b,a);0<=c?(g.pb(b,c),b=!0):b=!1;return b||g.qb(this.u,a)};
g.k.Fe=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Xa(c7,g.B);g.k=c7.prototype;g.k.jO=function(){this.qe=Math.min(3E5,2*this.qe);this.A();this.u&&this.start()};
g.k.start=function(){var a=this.qe+15E3*Math.random();this.o.kb(a);this.u=g.z()+a};
g.k.stop=function(){this.o.stop();this.u=0};
g.k.isActive=function(){return this.o.isActive()};
g.k.reset=function(){this.o.stop();this.qe=5E3};g.Xa(d7,IGa);g.k=d7.prototype;g.k.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.k.yj=function(a){return this.A.zk(a)};
g.k.R=function(a,b){return this.A.R.apply(this.A,arguments)};
g.k.dispose=function(){this.sd||(this.sd=!0,g.ag(this.A),MGa(this),g.ag(this.u),this.u=null,this.S=function(){return""})};
g.k.ea=function(){return this.sd};
g.k.connect=function(a,b,c){if(!this.o||2!=this.o.va){this.M="";this.u.stop();this.C=a||null;this.B=b||0;a=this.P+"/test";b=this.P+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.U),e=this.o;e&&(e.ne=null);d.ne=this;this.o=d;e7(this);e?this.o.connect(a,b,this.F,e.u,e.qm):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.ac(c,b);this.u.isActive()||2==(this.o?this.o.va:0)?this.H.push(c):f7(this)&&(e7(this),CGa(this.o,c))};
g.k.Az=function(){this.u.reset();this.C=null;this.B=0;if(this.H.length){var a=this.H;this.H=[];for(var b=0,c=a.length;b<c;++b)CGa(this.o,a[b])}this.R("handlerOpened")};
g.k.yz=function(a){var b=2==a&&401==this.o.oh;4==a||b||this.u.start();this.R("handlerError",a)};
g.k.qu=function(a){if(!this.u.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.H.push(d)}};
g.k.jA=function(){var a={v:2};this.M&&(a.gsessionid=this.M);0!=this.B&&(a.ui=""+this.B);0!=this.J&&(a.ui=""+this.J);this.C&&g.ac(a,this.C);return a};
g.k.zz=function(a){"S"==a[0]?this.M=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),AGa(this.o)):this.R("handlerMessage",new KGa(a[0],a[1]))};
g.k.pP=function(){this.u.isActive();var a=this.o,b=0;a.Zc&&b++;a.Ve&&b++;0==b&&this.connect(this.C,this.B)};g7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
g7.prototype.C=function(a){a(Error("request timed out"))};var UGa=g.z(),j7=null,m7=Array(50),l7=-1,n7=!1;g.Xa(o7,g.N);o7.prototype.wf=function(){return this.screens};
o7.prototype.contains=function(a){return!!l6(this.screens,a)};
o7.prototype.get=function(a){return a?m6(this.screens,a):null};
o7.prototype.info=function(a){k7(this.F,a)};g.u(p7,g.N);g.k=p7.prototype;g.k.start=function(){!this.o&&isNaN(this.La)&&this.KF()};
g.k.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.La)||(g.Go(this.La),this.La=NaN)};
g.k.V=function(){this.stop();g.N.prototype.V.call(this)};
g.k.KF=function(){this.La=NaN;this.o=g.mq(h7(this.F,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:this.C},timeout:5E3,onSuccess:(0,g.y)(this.sQ,this),onError:(0,g.y)(this.rQ,this),Gf:(0,g.y)(this.tQ,this)})};
g.k.sQ=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.R("pairingComplete",new g6(c))};
g.k.rQ=function(a){this.o=null;a.status&&404==a.status?this.u>=fIa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=fIa[this.u],this.La=g.Eo((0,g.y)(this.KF,this),a),this.u++):this.R("pairingFailed",Error("Server error "+a.status))};
g.k.tQ=function(){this.o=null;this.R("pairingFailed",Error("Server not responding"))};
var fIa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Xa(r7,o7);g.k=r7.prototype;g.k.start=function(){q7(this)&&this.R("screenChange");!g.ot("yt-remote-lounge-token-expiration")&&YGa(this);g.Go(this.o);this.o=g.Eo((0,g.y)(this.start,this),1E4)};
g.k.add=function(a,b){q7(this);VGa(this,a);s7(this,!1);this.R("screenChange");b(a);a.token||YGa(this)};
g.k.remove=function(a,b){var c=q7(this);XGa(this,a)&&(s7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.k.Ct=function(a,b,c,d){var e=q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,s7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.k.V=function(){g.Go(this.o);r7.Pc.V.call(this)};
g.k.ZH=function(a){q7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}s7(this,!b);b&&k7(this.F,"Missed "+b+" lounge tokens.")};
g.k.YH=function(a){k7(this.F,"Requesting lounge tokens failed: "+a)};g.u(u7,g.N);g.k=u7.prototype;g.k.start=function(){var a=parseInt(g.ot("yt-remote-fast-check-period")||"0",10);(this.B=g.z()-144E5<a?0:a)?w7(this):(this.B=g.z()+3E5,g.nt("yt-remote-fast-check-period",this.B),this.hx())};
g.k.isEmpty=function(){return g.Vb(this.o)};
g.k.update=function(){t7("Updating availability on schedule.");var a=this.F(),b=g.Jb(this.o,function(c,d){return c&&!!m6(a,d)},this);
v7(this,b)};
g.k.V=function(){g.Go(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.N.prototype.V.call(this)};
g.k.hx=function(){g.Go(this.A);this.A=NaN;this.u&&this.u.abort();var a=aHa(this);if(c6(a)){var b=h7(this.C,"/pairing/get_screen_availability");this.u=i7(this.C,b,{lounge_token:g.Pb(a).join(",")},(0,g.y)(this.UN,this,a),(0,g.y)(this.TN,this))}else v7(this,{}),w7(this)};
g.k.UN=function(a,b){this.u=null;var c=g.Pb(aHa(this));if(g.Db(c,g.Pb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;v7(this,d);w7(this)}else this.Lc("Changing Screen set during request."),this.hx()};
g.k.TN=function(a){this.Lc("Screen availability failed: "+a);this.u=null;w7(this)};
g.k.Lc=function(a){k7("OnlineScreenService",a)};g.Xa(x7,o7);g.k=x7.prototype;g.k.start=function(){this.u.start();this.o.start();this.screens.length&&(this.R("screenChange"),this.o.isEmpty()||this.R("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.k.Ct=function(a,b,c,d){this.u.contains(a)?this.u.Ct(a,b,c,d):(a="Updating name of unknown screen: "+a.name,k7(this.F,a),d(Error(a)))};
g.k.wf=function(a){return a?this.screens:g.sb(this.screens,g.Ie(this.A,function(b){return!this.contains(b)},this))};
g.k.LF=function(){return g.Ie(this.wf(!0),function(a){return!!this.o.o[a.id]},this)};
g.k.MF=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new p7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(h){g.ag(f);d(y7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.ag(f);e(h)});
f.start();return(0,g.y)(f.stop,f)};
g.k.vQ=function(a,b,c,d){g.mq(h7(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var h=new g6(f.screen||{});if(!h.name||eHa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);eHa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(y7(this,h))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
Gf:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.k.V=function(){g.ag(this.u);g.ag(this.o);x7.Pc.V.call(this)};
g.k.gI=function(){fHa(this);this.R("screenChange");this.o.update()};
x7.prototype.dispose=x7.prototype.dispose;g.Xa(A7,g.N);g.k=A7.prototype;g.k.getScreen=function(){return this.H};
g.k.Ds=function(a){this.H=a;this.R("sessionScreen",this.H)};
g.k.Ff=function(a){this.ea()||(a&&B7(this,""+a),this.H=null,this.R("sessionScreen",null))};
g.k.info=function(a){k7(this.U,a)};
g.k.OF=function(){return null};
g.k.tx=function(a){var b=this.o;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){B7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.V=function(){this.tx("");A7.Pc.V.call(this)};g.u(C7,A7);g.k=C7.prototype;g.k.sx=function(a){if(this.u){if(this.u==a)return;B7(this,"Overriding cast sesison with new session object");this.u.removeUpdateListener(this.C);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.u=a;this.u.addUpdateListener(this.C);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);hHa(this)};
g.k.rm=function(a){this.info("launchWithParams no-op for Cast: "+g.Bj(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.y)(function(){this.Ff()},this),(0,g.y)(function(){this.Ff(Error("Failed to stop receiver app."))},this)):this.Ff(Error("Stopping cast device witout session."))};
g.k.tx=function(){};
g.k.V=function(){this.info("disposeInternal");g.Go(this.A);this.A=0;this.u&&(this.u.removeUpdateListener(this.C),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.u=null;A7.prototype.V.call(this)};
g.k.KO=function(a,b){if(!this.ea())if(b){var c=y6(b);if(g.Ra(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Bj(c));switch(d){case "mdxSessionStatus":gHa(this,c.screenId);break;default:B7(this,"Unknown youtube message: "+d)}}else B7(this,"Unable to parse message.")}else B7(this,"No data in message.")};
g.k.BA=function(a,b,c,d){dHa(this.J,this.o.label,a,this.o.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(B7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Eo((0,g.y)(this.BA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.OF=function(){return this.u};
g.k.wQ=function(a){this.ea()||a||(B7(this,"Cast session died."),this.Ff())};g.u(D7,A7);g.k=D7.prototype;g.k.sx=function(a){this.A=a;this.A.addUpdateListener(this.S)};
g.k.rm=function(a){this.P=a;this.C()};
g.k.stop=function(){this.u();this.u=g.Ma;g.Go(this.B);this.A?this.A.stop((0,g.y)(this.Ff,this,null),(0,g.y)(this.Ff,this,"Failed to stop DIAL device.")):this.Ff()};
g.k.V=function(){this.u();this.u=g.Ma;g.Go(this.B);this.A&&this.A.removeUpdateListener(this.S);this.A=null;A7.prototype.V.call(this)};
g.k.zQ=function(a){this.ea()||a||(B7(this,"DIAL session died."),this.u(),this.u=g.Ma,this.Ff())};
g.k.Dv=function(a){this.M=k6();if(this.P){var b=new chrome.cast.DialLaunchResponse(!0,jHa(this));a(b);iHa(this)}else this.C=(0,g.y)(function(){g.Go(this.B);this.C=g.Ma;this.B=NaN;var c=new chrome.cast.DialLaunchResponse(!0,jHa(this));a(c);iHa(this)},this),this.B=g.Eo((0,g.y)(function(){this.C()},this),100)};
g.k.wI=function(a,b,c){dHa(this.J,this.F.receiver.label,a,this.o.friendlyName,(0,g.y)(function(d){d&&d.token?(this.Ds(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Dv(b,c)},this),(0,g.y)(function(d){B7(this,"Failed to get DIAL screen: "+d);
this.Dv(b,c)},this))};g.u(E7,A7);E7.prototype.stop=function(){this.Ff()};
E7.prototype.sx=function(){};
E7.prototype.rm=function(){g.Go(this.u);this.u=NaN;var a=m6(this.J.wf(),this.o.label);a?this.Ds(a):this.Ff(Error("No such screen"))};
E7.prototype.V=function(){g.Go(this.u);this.u=NaN;A7.prototype.V.call(this)};g.u(F7,g.N);g.k=F7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.H);this.J||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.y)(this.EN,this);c=new chrome.cast.ApiConfig(c,(0,g.y)(this.zD,this),f,d,e);c.customDialLaunchCallback=(0,g.y)(this.ZL,this);chrome.cast.initialize(c,(0,g.y)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.B),RGa(),this.u.subscribe("onlineScreenChange",(0,g.y)(this.NF,this)),this.A=lHa(this),chrome.cast.setCustomReceivers(this.A,g.Ma,(0,g.y)(function(h){this.Lc("Failed to set initial custom receivers: "+g.Bj(h))},this)),this.R("yt-remote-cast2-availability-change",H7(this)),b(!0))},this),(0,g.y)(function(h){this.Lc("Failed to initialize API: "+g.Bj(h));
b(!1)},this))};
g.k.vP=function(a,b){G7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)G7("Unsetting old screen status: "+this.o.o.friendlyName),I7(this,null)}if(a&&b){if(!this.o){c=m6(this.u.wf(),a);if(!c){G7("setConnectedScreenStatus: Unknown screen.");return}var d=kHa(this,c);d||(G7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Ma,(0,g.y)(function(e){this.Lc("Failed to set initial custom receivers: "+g.Bj(e))},this)));
G7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);I7(this,new E7(this.u,d),!0)}this.o.tx(b)}else G7("setConnectedScreenStatus: no screen.")};
g.k.wP=function(a){this.ea()?this.Lc("Setting connection data on disposed cast v2"):this.o?this.o.rm(a):this.Lc("Setting connection data without a session")};
g.k.yQ=function(){this.ea()?this.Lc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),I7(this,null)):G7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.zD,this),(0,g.y)(this.WN,this))};
g.k.V=function(){this.u.unsubscribe("onlineScreenChange",(0,g.y)(this.NF,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=OGa,b=g.La("yt.mdx.remote.debug.handlers_");g.qb(b||[],a);g.ag(this.o);g.N.prototype.V.call(this)};
g.k.Lc=function(a){k7("Controller",a)};
g.k.BD=function(a,b){this.o==a&&(b||I7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.k.AN=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),G7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.o.label!=a.label)G7("onReceiverAction_: Stopping active receiver: "+this.o.o.friendlyName),this.o.stop();else{G7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.R("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:I7(this,
new E7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:I7(this,new D7(this.u,a,this.F));break;case chrome.cast.ReceiverType.CAST:I7(this,new C7(this.u,a));break;default:this.Lc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.o.label==a.label?this.o.stop():this.Lc("Stopping receiver w/o session: "+a.friendlyName)}else this.Lc("onReceiverAction_ called without receiver.")};
g.k.ZL=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Lc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.o:null;if(!c||c.label!=b.label)return this.Lc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return G7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Lc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);I7(this,new D7(this.u,b,this.F))}b=this.o;b.F=a;return b.F.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.wI,b,(b.F.extraData||{}).screenId||null)):new Promise((0,g.y)(b.Dv,b))};
g.k.zD=function(a){if(!this.ea()){G7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)G7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),I7(this,new C7(this.u,b),!0);else{this.Lc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.o,d=m6(this.u.wf(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(G7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.ag(this.o),this.o=new C7(this.u,b),this.o.subscribe("sessionScreen",(0,g.y)(this.BD,this,this.o)),this.o.rm(null));this.o.sx(a)}}};
g.k.xQ=function(){return this.o?this.o.OF():null};
g.k.WN=function(a){this.ea()||(this.Lc("Failed to estabilish a session: "+g.Bj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&I7(this,null))};
g.k.EN=function(a){G7("Receiver availability updated: "+a);if(!this.ea()){var b=H7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;H7(this)!=b&&this.R("yt-remote-cast2-availability-change",H7(this))}};
g.k.NF=function(){this.ea()||(this.A=lHa(this),G7("Updating custom receivers: "+g.Bj(this.A)),chrome.cast.setCustomReceivers(this.A,g.Ma,(0,g.y)(function(){this.Lc("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",H7(this)))};
F7.prototype.setLaunchParams=F7.prototype.wP;F7.prototype.setConnectedScreenStatus=F7.prototype.vP;F7.prototype.stopSession=F7.prototype.yQ;F7.prototype.getCastSession=F7.prototype.xQ;F7.prototype.requestSession=F7.prototype.requestSession;F7.prototype.init=F7.prototype.init;F7.prototype.dispose=F7.prototype.dispose;var O7=[];g.k=T7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";U7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.ph=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.J=a.duration,this.M=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.k.ub=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.A?this.J+V7(this):this.J};
g.k.clone=function(){return new T7(Z7(this))};g.u(a8,g.N);g.k=a8.prototype;g.k.play=function(){1==this.va?(this.o?this.o.play(null,g.Ma,g8(this,"play")):f8(this,"play"),e8(this,1,X7(b8(this))),this.R("remotePlayerChange")):c8(this,this.play)};
g.k.pause=function(){1==this.va?(this.o?this.o.pause(null,g.Ma,g8(this,"pause")):f8(this,"pause"),e8(this,2,X7(b8(this))),this.R("remotePlayerChange")):c8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.va){if(this.o){var b=b8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.ub()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.Ma,g8(this,"seekTo",{newTime:a}))}else f8(this,"seekTo",{newTime:a});e8(this,3,a);this.R("remotePlayerChange")}else c8(this,g.Ua(this.seekTo,a))};
g.k.stop=function(){if(1==this.va){this.o?this.o.stop(null,g.Ma,g8(this,"stopVideo")):f8(this,"stopVideo");var a=b8(this);a.index=-1;a.videoId="";U7(a);d8(this,a);this.R("remotePlayerChange")}else c8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.va){var c=b8(this);if(this.u){if(c.volume!=a){var d=Math.round(a)/100;this.u.setReceiverVolumeLevel(d,(0,g.y)(function(){k7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Lc("failed to set receiver volume.")},this))}c.muted!=b&&this.u.setReceiverMuted(b,(0,g.y)(function(){k7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Lc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f8(this,"setVolume",e)}c.muted=b;c.volume=a;d8(this,c)}else c8(this,g.Ua(this.setVolume,a,b))};
g.k.JF=function(a,b){if(1==this.va){var c=b8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Bj(b.style),g.ac(d,c.o));f8(this,"setSubtitlesTrack",d);d8(this,c)}else c8(this,g.Ua(this.JF,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.va){var c=b.getLanguageInfo().getId();f8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=b8(this);d.audioTrackId=c;d8(this,d)}else c8(this,g.Ua(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=b8(this);c=c||0;var m={videoId:a,currentIndex:c};Y7(l,a,c);void 0!==b&&(W7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Bj(h));f8(this,"setPlaylist",m);d||d8(this,l)};
g.k.Js=function(a,b){if(1==this.va){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"previous")}else c8(this,g.Ua(this.Js,a,b))};
g.k.nextVideo=function(a,b){if(1==this.va){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"next")}else c8(this,g.Ua(this.nextVideo,a,b))};
g.k.Qz=function(){1==this.va?f8(this,"dismissAutoplay"):c8(this,this.Qz)};
g.k.dispose=function(){if(3!=this.va){var a=this.va;this.va=3;this.R("proxyStateChange",a,this.va)}g.N.prototype.dispose.call(this)};
g.k.V=function(){yHa(this);this.A=null;this.B.clear();$7(this,null);g.N.prototype.V.call(this)};
g.k.my=function(a){if((a!=this.va||2==a)&&3!=this.va&&0!=a){var b=this.va;this.va=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.nb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.k.wN=function(a,b){this.R(a,b)};
g.k.ML=function(a){if(!a)this.Jo(null),$7(this,null);else if(this.u.receiver.volume){a=this.u.receiver.volume;var b=b8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)k7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d8(this,b)}};
g.k.Jo=function(a){k7("CP","Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.H);if(this.o=a)this.o.addUpdateListener(this.H),zHa(this),this.R("remotePlayerChange")};
g.k.LL=function(a){a?(zHa(this),this.R("remotePlayerChange")):this.Jo(null)};
g.k.Lx=function(){f8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.UL=function(){var a=vHa();a&&$7(this,a)};
g.k.Lc=function(a){k7("CP",a)};g.u(h8,g.N);g.k=h8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.rb.listId=c);this.rb.videoId=d;this.rb.index=h||0;this.rb.state=3;W7(this.rb,m);this.B="UNSUPPORTED";i8("Connecting with setPlaylist and params: "+g.Bj(l));this.o.connect({method:"setPlaylist",
params:g.Bj(l)},a,LFa())}else i8("Connecting without params"),this.o.connect({},a,LFa());BHa(this)};
g.k.dispose=function(){this.ea()||(this.R("beforeDispose"),j8(this,3));g.N.prototype.dispose.call(this)};
g.k.V=function(){k8(this);m8(this);l8(this);g.Go(this.H);this.H=NaN;g.Go(this.J);this.J=NaN;this.A=null;g.bp(this.U);this.U.length=0;this.o.dispose();g.N.prototype.V.call(this);this.B=this.F=this.u=this.rb=this.o=null};
g.k.SH=function(){this.Sl(2)};
g.k.QL=function(){i8("Channel opened");this.S&&(this.S=!1,l8(this),this.P=g.Eo((0,g.y)(function(){i8("Timing out waiting for a screen.");this.Sl(1)},this),15E3));
PFa(LGa(this.o),this.W)};
g.k.NL=function(){i8("Channel closed");isNaN(this.C)?r6(!0):r6();this.dispose()};
g.k.OL=function(a){r6();isNaN(this.Rn())?(i8("Channel error: "+a+" without reconnection"),this.dispose()):(this.S=!0,i8("Channel error: "+a+" with reconnection in "+this.Rn()+" ms"),j8(this,2))};
g.k.PL=function(a){a.params?i8("Received: action="+a.action+", params="+g.Bj(a.params)):i8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=y6(a.params.devices);this.u=g.Oc(a,function(c){return new f6(c)});
a=!!g.gb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
EHa(this,a);break;case "loungeScreenDisconnected":g.rb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
EHa(this,!1);break;case "remoteConnected":var b=new f6(y6(a.params.device));g.gb(this.u,function(c){return b?c.id==b.id:!1})||vFa(this.u,b);
break;case "remoteDisconnected":b=new f6(y6(a.params.device));g.rb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":GHa(this,a);break;case "nowPlaying":IHa(this,a);break;case "onStateChange":HHa(this,a);break;case "onAdStateChange":JHa(this,a);break;case "onVolumeChanged":KHa(this,a);break;case "onSubtitlesTrackChanged":FHa(this,a);break;case "nowAutoplaying":LHa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.R("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.R("autoplayModeChange",this.B);"DISABLED"==this.B&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":MHa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:i8("Unrecognized action: "+a.action)}};
g.k.lP=function(){if(this.A){var a=this.A;this.A=null;this.rb.videoId!=a&&n8(this,"getNowPlaying")}};
g.k.JH=function(){var a=3;this.ea()||(a=0,isNaN(this.Rn())?f7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Sl=function(a){i8("Disconnecting with "+a);k8(this);this.R("beforeDisconnect",a);1==a&&r6();MGa(this.o,a);this.dispose()};
g.k.HH=function(){var a=this.rb;this.A&&(a=this.rb.clone(),Y7(a,this.A,a.index));return Z7(a)};
g.k.xP=function(a){var b=new T7(a);b.videoId&&b.videoId!=this.rb.videoId&&(this.A=b.videoId,g.Go(this.H),this.H=g.Eo((0,g.y)(this.lP,this),5E3));var c=[];this.rb.listId==b.listId&&this.rb.videoId==b.videoId&&this.rb.index==b.index||c.push("remoteQueueChange");this.rb.playerState==b.playerState&&this.rb.volume==b.volume&&this.rb.muted==b.muted&&X7(this.rb)==X7(b)&&g.Bj(this.rb.o)==g.Bj(b.o)||c.push("remotePlayerChange");this.rb.reset(a);g.Gb(c,function(d){this.R(d)},this)};
g.k.zA=function(){var a=this.o.F.id,b=g.gb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Rn=function(){var a=this.o;return a.u.isActive()?a.u.u-g.z():NaN};
g.k.vH=function(){return this.B||"UNSUPPORTED"};
g.k.wH=function(){return this.F||""};
g.k.qQ=function(){if(!isNaN(this.Rn())){var a=this.o.u;g.qn(a.o);a.start()}};
g.k.tP=function(a,b){n8(this,a,b);DHa(this)};
g.k.IF=function(){var a=g.vq("SID","")||"",b=g.vq("SAPISID","")||"",c=g.vq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.mf(g.Se(a),2);b=g.mf(g.Se(b),2);c=g.mf(g.Se(c),2);return g.mf(g.Se(a+","+b+","+c),2)};
h8.prototype.subscribe=h8.prototype.subscribe;h8.prototype.unsubscribeByKey=h8.prototype.yj;h8.prototype.getProxyState=h8.prototype.JH;h8.prototype.disconnect=h8.prototype.Sl;h8.prototype.getPlayerContextData=h8.prototype.HH;h8.prototype.setPlayerContextData=h8.prototype.xP;h8.prototype.getOtherConnectedRemoteId=h8.prototype.zA;h8.prototype.getReconnectTimeout=h8.prototype.Rn;h8.prototype.getAutoplayMode=h8.prototype.vH;h8.prototype.getAutoplayVideoId=h8.prototype.wH;h8.prototype.reconnect=h8.prototype.qQ;
h8.prototype.sendMessage=h8.prototype.tP;h8.prototype.getXsrfToken=h8.prototype.IF;g.u(o8,o7);g.k=o8.prototype;g.k.wf=function(a){return this.pe.$_gs(a)};
g.k.contains=function(a){return!!this.pe.$_c(a)};
g.k.get=function(a){return this.pe.$_g(a)};
g.k.start=function(){this.pe.$_st()};
g.k.add=function(a,b,c){this.pe.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.pe.$_r(a,b,c)};
g.k.Ct=function(a,b,c,d){this.pe.$_un(a,b,c,d)};
g.k.V=function(){for(var a=0,b=this.o.length;a<b;++a)this.pe.$_ubk(this.o[a]);this.o.length=0;this.pe=null;o7.prototype.V.call(this)};
g.k.uQ=function(){this.R("screenChange")};
g.k.cN=function(){this.R("onlineScreenChange")};
x7.prototype.$_st=x7.prototype.start;x7.prototype.$_gspc=x7.prototype.vQ;x7.prototype.$_gsppc=x7.prototype.MF;x7.prototype.$_c=x7.prototype.contains;x7.prototype.$_g=x7.prototype.get;x7.prototype.$_a=x7.prototype.add;x7.prototype.$_un=x7.prototype.Ct;x7.prototype.$_r=x7.prototype.remove;x7.prototype.$_gs=x7.prototype.wf;x7.prototype.$_gos=x7.prototype.LF;x7.prototype.$_s=x7.prototype.subscribe;x7.prototype.$_ubk=x7.prototype.yj;var H8=null,G8=!1,p8=null,q8=null,F8=null,u8=[];g.u(I8,g.B);g.k=I8.prototype;g.k.V=function(){g.B.prototype.V.call(this);this.o.stop();this.u.stop();this.H.stop();this.P();var a=this.eb;a.unsubscribe("proxyStateChange",this.wD,this);a.unsubscribe("remotePlayerChange",this.Po,this);a.unsubscribe("remoteQueueChange",this.Es,this);a.unsubscribe("previousNextChange",this.sD,this);a.unsubscribe("nowAutoplaying",this.nD,this);a.unsubscribe("autoplayDismissed",this.NC,this);this.eb=this.module=null};
g.k.YB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.eb.va)if(J8(this)){if(!b8(this.eb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":b8(this.eb).ub()?this.eb.pause():this.eb.play();break;case "control_play":this.eb.play();break;case "control_pause":this.eb.pause();break;case "control_seek":this.F.IB(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.G.getCurrentTime();L8(this,0===c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.KL=function(a){this.H.PH(a)};
g.k.ZP=function(a){this.YB("control_subtitles_set_track",g.Vb(a)?null:a)};
g.k.UE=function(){var a=this.G.getOption("captions","track");g.Vb(a)||K8(this,a)};
g.k.wc=function(a){this.module.wc(a,this.G.getVideoData().lengthSeconds)};
g.k.dD=function(a){if(J8(this)){this.eb.unsubscribe("remotePlayerChange",this.Po,this);var b=Math.round(a.volume);a=!!a.muted;var c=b8(this.eb);if(b!==c.volume||a!==c.muted)this.eb.setVolume(b,a),this.J.start();this.eb.subscribe("remotePlayerChange",this.Po,this)}};
g.k.DM=function(){g.Vb(this.A)||YHa(this,this.A);this.B=!1};
g.k.wD=function(a,b){this.u.stop();2===b&&this.RE()};
g.k.Po=function(){if(J8(this)){this.o.stop();var a=b8(this.eb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.Ld=1;break;case 1082:case 1083:this.module.Ld=0;break;default:this.module.Ld=-1}switch(a.playerState){case 1081:case 1:this.qd(new g.PK(8));this.QE();break;case 1085:case 3:this.qd(new g.PK(9));break;case 1083:case 0:this.qd(new g.PK(2));this.F.stop();this.wc(this.G.getVideoData().lengthSeconds);break;case 1084:this.qd(new g.PK(4));break;case 2:this.qd(new g.PK(4));
this.wc(X7(a));break;case -1:this.qd(new g.PK(64));break;case -1E3:this.qd(new g.PK(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=b8(this.eb).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,YHa(this,a));a=b8(this.eb);-1===a.volume||Math.round(this.G.getVolume())===a.volume&&this.G.isMuted()===a.muted||this.J.isActive()||this.tF()}else XHa(this)};
g.k.sD=function(){this.G.R("mdxpreviousnextchange")};
g.k.Es=function(){J8(this)||XHa(this)};
g.k.nD=function(a){isNaN(a)||this.G.R("mdxnowautoplaying",a)};
g.k.NC=function(){this.G.R("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J8(this)&&this.eb.setAudioTrack(this.G.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===b8(this.eb).playerState?L8(this,a):b&&this.eb.seekTo(a)};
g.k.tF=function(){if(J8(this)){var a=b8(this.eb);this.events.sb(this.M);a.muted?this.G.mute():this.G.unMute();this.G.setVolume(a.volume);this.M=this.events.K(this.G,"onVolumeChange",this.dD)}};
g.k.QE=function(){this.o.stop();if(!this.eb.ea()){var a=b8(this.eb);a.ub()&&this.qd(new g.PK(8));this.wc(X7(a));this.o.start()}};
g.k.RE=function(){this.u.stop();this.o.stop();var a=this.eb.A.getReconnectTimeout();2==this.eb.va&&!isNaN(a)&&this.u.start()};
g.k.qd=function(a){this.u.stop();var b=this.C;if(!g.UK(b,a)){var c=g.S(a,2);c!==g.S(this.C,2)&&g.x0(this.G.app,c);this.C=a;$Ha(this.module,b,a)}};g.u(M8,g.V);M8.prototype.dc=function(){this.o.show()};
M8.prototype.Ta=function(){this.o.hide()};
M8.prototype.u=function(){g.mK("https://support.google.com/youtube/answer/7640706")};
M8.prototype.A=function(){e6("mdx-manual-pairing-popup-ok");this.Ta()};g.u(N8,g.V);N8.prototype.dc=function(){this.o.show()};
N8.prototype.Ta=function(){this.o.hide()};
N8.prototype.u=function(){e6("mdx-privacy-popup-cancel");this.Ta()};
N8.prototype.A=function(){e6("mdx-privacy-popup-confirm");this.Ta()};g.u(O8,g.V);O8.prototype.u=function(a){ZHa(this,a.state)};g.u(P8,g.OZ);P8.prototype.B=function(){var a=this.G.getOption("remote","receivers");a&&1<a.length&&!this.G.getOption("remote","quickCast")?(this.Hj=g.Hb(a,this.o,this),g.PZ(this,g.Oc(a,this.o)),a=this.G.getOption("remote","currentReceiver"),this.hc(this.o(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.o=function(a){return a.key};
P8.prototype.Gg=function(a){return"cast-selector-receiver"===a?"Cast...":this.Hj[a].name};
P8.prototype.Yd=function(a){g.OZ.prototype.Yd.call(this,a);this.G.setOption("remote","currentReceiver",this.Hj[a]);this.Ka.Ta()};g.u(Q8,g.FS);g.k=Q8.prototype;
g.k.create=function(){var a=this.player.N(),b=g.bC(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.Q(a.experiments,"mdx_load_cast_api_bootstrap_script")};RHa(b,a);this.subscriptions.push(g.Lo("yt-remote-before-disconnect",this.IL,this));this.subscriptions.push(g.Lo("yt-remote-connection-change",this.FN,this));this.subscriptions.push(g.Lo("yt-remote-receiver-availability-change",this.uD,this));this.subscriptions.push(g.Lo("yt-remote-auto-connect",this.DN,this));this.subscriptions.push(g.Lo("yt-remote-receiver-resumed",
this.CN,this));this.subscriptions.push(g.Lo("mdx-privacy-popup-confirm",this.bP,this));this.subscriptions.push(g.Lo("mdx-privacy-popup-cancel",this.aP,this));this.subscriptions.push(g.Lo("mdx-manual-pairing-popup-ok",this.LI,this));this.uD()};
g.k.load=function(){this.player.cancelPlayback();g.FS.prototype.load.call(this);this.eh=new I8(this,this.player,this.eb);var a=(a=WHa())?a.currentTime:0;var b=E8()?new a8(z8(),void 0):null;0==a&&b&&(a=X7(b8(b)));0!==a&&this.wc(a);$Ha(this,this.sc,this.sc);g.F0(this.player.app,6)};
g.k.unload=function(){this.player.R("mdxautoplaycanceled");this.Wi=this.Dg;g.bg(this.eh,this.eb);this.eb=this.eh=null;g.FS.prototype.unload.call(this);g.F0(this.player.app,5);R8(this)};
g.k.V=function(){g.Mo(this.subscriptions);g.FS.prototype.V.call(this)};
g.k.Dh=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.eh.YB.apply(this.eh,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.Ld};
g.k.LH=function(){return this.loaded?this.eh.suggestion:null};
g.k.ph=function(){return this.eb?b8(this.eb).ph:!1};
g.k.hasNext=function(){return this.eb?b8(this.eb).hasNext:!1};
g.k.wc=function(a,b){this.sB=a||0;this.player.R("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.sB};
g.k.getProgressState=function(){var a=b8(this.eb),b=this.player.getVideoData();return{allowSeeking:g.Q(this.player.N().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Kd():!a.isAdPlaying()&&this.player.Kd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+V7(a):a.B,isAtLiveHead:1>=(a.A?a.u+V7(a):a.u)-this.getCurrentTime(),loaded:a.M,seekableEnd:a.A?a.u+V7(a):a.u,seekableStart:0<a.C?a.C+
V7(a):a.C}};
g.k.nextVideo=function(){this.eb&&this.eb.nextVideo()};
g.k.Js=function(){this.eb&&this.eb.Js()};
g.k.IL=function(a){1===a&&(this.Sw=this.eb?b8(this.eb):null)};
g.k.FN=function(){var a=E8()?new a8(z8(),void 0):null;if(a){var b=this.Wi;this.loaded&&this.unload();this.eb=a;this.Sw=null;b.key!==this.Dg.key&&(this.Wi=b,this.load())}else g.ag(this.eb),this.eb=null,this.loaded&&(this.unload(),(a=this.Sw)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,X7(a)));this.player.R("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.uD=function(){this.Hj=[this.Dg].concat(THa());var a=A8()||this.Dg;S8(this,a);this.player.la("onMdxReceiversChange")};
g.k.DN=function(){var a=A8();S8(this,a)};
g.k.CN=function(){this.Wi=A8()};
g.k.bP=function(){this.So=!0;R8(this);G8=!1;H8&&C8(H8,1);H8=null};
g.k.aP=function(){this.So=!1;R8(this);S8(this,this.Dg);this.Wi=this.Dg;G8=!1;H8=null;this.player.playVideo()};
g.k.LI=function(){this.Ir=!0;R8(this);g.nt("yt-remote-manual-pairing-warning-shown",!0,2592E3);G8=!1;H8&&C8(H8,1);H8=null};
g.k.Hd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Hj;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?R7():S8(this,b)),this.loaded?this.Wi:this.Dg;case "quickCast":return 2===this.Hj.length&&"cast-selector-receiver"===this.Hj[1].key?(b&&R7(),!0):!1}};
g.k.Lx=function(){this.eb.Lx()};
g.k.Rg=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.vX.remote=Q8;})(_yt_player);
